- .travis.yml
- README.md
- pom.xml
GeoSpark is now hosted in Maven Central!
> Update some simple docs

- README.md
- src/main/java/org/datasyslab/geospark/showcase/Example.java
- src/main/java/org/datasyslab/geospark/showcase/UserSuppliedPointMapper.java
- src/main/java/org/datasyslab/geospark/spatialRDD/LineStringRDD.java
- src/main/java/org/datasyslab/geospark/spatialRDD/PointRDD.java
- src/main/java/org/datasyslab/geospark/spatialRDD/PolygonRDD.java
- src/main/java/org/datasyslab/geospark/spatialRDD/RectangleRDD.java
- src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java
- src/test/java/org/datasyslab/geospark/spatialOperator/LineStringJoinTest.java
- src/test/java/org/datasyslab/geospark/spatialOperator/PointJoinTest.java
- src/test/java/org/datasyslab/geospark/spatialOperator/PolygonJoinTest.java
- src/test/java/org/datasyslab/geospark/spatialOperator/RectangleJoinTest.java
- src/test/java/org/datasyslab/geospark/utils/testGeoJSON.java
Prepare GeoSpark 0.5.2. Deprecate all old SpatialRDD constructors and add new constructors which have better performance on the "analyze" phase.
> Prepare GeoSpark 0.5.2

- core/src/main/java/org/datasyslab/geospark/spatialRDD/CircleRDD.java
- core/src/main/java/org/datasyslab/geospark/spatialRDD/LineStringRDD.java
- core/src/main/java/org/datasyslab/geospark/spatialRDD/PointRDD.java
- core/src/main/java/org/datasyslab/geospark/spatialRDD/PolygonRDD.java
- core/src/main/java/org/datasyslab/geospark/spatialRDD/RectangleRDD.java
- core/src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java
- core/src/test/java/org/datasyslab/geospark/spatialOperator/PointRangeTest.java
- core/src/test/java/org/datasyslab/geospark/spatialOperator/PolygonJoinTest.java
- core/src/test/java/org/datasyslab/geospark/utils/CRSTransformationTest.java
- core/src/test/java/org/datasyslab/geospark/utils/CorrectnessChecker.java
…tion when doing initialization based on another SpatialRDD.
> Fix a bug in DistanceJoinQuery: CircleRDD didn't copy CRS when initializing

- core/src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java
Sometimes the number of partitions in the original RDD is not the same as the number of desired spatial partitions. For these cases, instead of forcing the user to re-partition the original RDD, allow them to specify the number of desired spatial partitions by calling SpatialRDD.spatialPartitioning(gridType, numPartitions).
Also, fixed NullPointerException when analyzing empty RDD.
> Allow user to specify the desired number of spatial partitions

- core/pom.xml
- core/src/main/java/org/datasyslab/geospark/formatMapper/shapefileParser/parseUtils/shp/PolygonParser.java
- sql/pom.xml
- sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Constructors.scala
- sql/src/test/scala/org/datasyslab/geosparksql/constructorTestScala.scala
- viz/pom.xml
Fixed Bug reported by Issue https://github.com/DataSystemsLab/GeoSpark/issues/170 and Issue https://github.com/DataSystemsLab/GeoSpark/issues/171
> Fixed Issue 170 and 171 

- pom.xml
- sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Functions.scala
- sql/src/test/scala/org/datasyslab/geosparksql/functionTestScala.scala
Fix Issue https://github.com/DataSystemsLab/GeoSpark/issues/204
> Fix the wrong error bug in ST_Intersection

- docs/api/sql/GeoSparkSQL-Constructor.md
- sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Constructors.scala
- sql/src/main/scala/org/datasyslab/geosparksql/UDF/Catalog.scala
- sql/src/test/scala/org/datasyslab/geosparksql/constructorTestScala.scala
Yes, https://github.com/DataSystemsLab/GeoSpark/issues/245
Remove ST_Circle
Passed the regression test
Yes
> Drop ST_Circle in GeoSpark SQL

- README.md
- docs/contact/publication.md
- docs/index.md
Add publications to README and the website
> Add publications

- sql/.gitignore
- sql/pom.xml
- sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/AggregateFunctions.scala
- sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Constructors.scala
- sql/src/main/scala/org/datasyslab/geosparksql/UDF/Catalog.scala
- sql/src/test/scala/org/datasyslab/geosparksql/TestBaseScala.scala
- sql/src/test/scala/org/datasyslab/geosparksql/adapterTestScala.scala
- sql/src/test/scala/org/datasyslab/geosparksql/aggregateFunctionTestScala.scala
- sql/src/test/scala/org/datasyslab/geosparksql/constructorTestScala.scala
- sql/src/test/scala/org/datasyslab/geosparksql/functionTestScala.scala
- sql/src/test/scala/org/datasyslab/geosparksql/predicateJoinTestScala.scala
- sql/src/test/scala/org/datasyslab/geosparksql/predicateTestScala.scala
No
Fix ST_Union_Aggr bug, enable Hive Support, and clean up the tests, add ST_GeomFromText
ST_Union_Aggr doesn't support MultiPolygon before.
Passed unit tests.
No
> Fix ST_Union_Aggr bug, enable Hive Support, clean up the tests, add ST_GeomFromText

- docs/api/sql/GeoSparkSQL-Constructor.md
- docs/tutorial/rdd.md
#277 
Documentating "geospark.global.charset" property
Generated documentation via `mkdocs` and made sure it looks correct
Yep
> Document shapefile charset configuration

- docs/index.md
> Add mobike logo

- docs/api/sql/GeoSparkSQL-Function.md
- sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Functions.scala
- sql/src/main/scala/org/datasyslab/geosparksql/UDF/Catalog.scala
- sql/src/test/scala/org/datasyslab/geosparksql/functionTestScala.scala
-
added ST_Buffer function, little optimisation in ST_Intersection
unit tests 
yes
> ST_Buffer function added

- core/src/main/java/org/datasyslab/geospark/formatMapper/FormatMapper.java
Issue #320 
Fix the wrong array offset calculation
Passed the regression test
No need
> Fix Issue 320

- sql/src/main/scala/org/datasyslab/geosparksql/utils/Adapter.scala
- sql/src/test/scala/org/datasyslab/geosparksql/adapterTestScala.scala
https://github.com/DataSystemsLab/GeoSpark/issues/345
optimisation of Adapter.toDF function
unit tests
no need
> 345 to df optimization

- .gitmodules
#199 
add geospark R package based on sparklyr plugin.
Documentation could add R package support.
> add geospark R package

- docs/api/sql/GeoSparkSQL-Function.md
- sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Functions.scala
- sql/src/main/scala/org/datasyslab/geosparksql/UDF/Catalog.scala
- sql/src/test/scala/org/datasyslab/geosparksql/functionTestScala.scala
#200 
Add ST_NPoints function
add Unit Test in FunctionTest
yes I update
> Add ST_NPoints function

- viz/pom.xml
#378 
A simple update to `pom.xml`
`mvn clean package` and made sure all test pass
```
[INFO] Reactor Summary for geospark-parent 1.2.0:
[INFO]
[INFO] geospark-parent .................................... SUCCESS [  6.032 s]
[INFO] org.datasyslab:geospark ............................ SUCCESS [11:26 min]
[INFO] org.datasyslab:geospark-sql_2.3 .................... SUCCESS [02:32 min]
[INFO] org.datasyslab:geospark-viz_2.3 .................... SUCCESS [08:34 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22:39 min
[INFO] Finished at: 2019-08-04T15:04:39-05:00
[INFO] ------------------------------------------------------------------------ …
```
> Fix for #378

- docs/tutorial/rdd.md
No.
Minor grammatical updates were made to the Spatial RDD tutorial.
N/A
N/A
> Update rdd.md with minor grammatical fixes

- core/src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java
- core/src/test/java/org/datasyslab/geospark/spatialRDD/SpatialRDDWriterTest.java
- docs/tutorial/rdd.md
Created SpatialRDDWriterTest.java for testing the function and potentially more SpatialRDD Writers
[Implement WKB writer #399](https://github.com/DataSystemsLab/GeoSpark/issues/399)
Added saveAsWKB function
Added SpatialRDDWriterTest.java for testing the function
yes. at rdd.md
> Wkb writer

- docs/index.md
No code here, just a typo fix.
> Fix a typo on the main page

- sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Constructors.scala
- sql/src/test/scala/org/datasyslab/geosparksql/constructorTestScala.scala
#423
ST_Point and ST_PolygonFromEnvelope add type check
tested
no
> ST_Point and ST_PolygonFromEnvelope grant for double type

- pom.xml
This PR fixes issue #445 
It adds a scope provided to hadoop-hdfs, this is proposed in the issue and fixes the problem.
The Spark job that failed previously, is now working without problems. 
No changes necessary.
> Add scope provided to hadoop-hdfs #445

- sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Functions.scala
- sql/src/test/scala/org/datasyslab/geosparksql/functionTestScala.scala
#358,#456
instead of "org.geotools.referencing.forceXY", use Hints for XY order.
add tests of reverse patterns.
no need to change documaentation.
> ST_transform changes the forceXY option

- docs/api/sql/GeoSparkSQL-Function.md
- sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Functions.scala
- sql/src/main/scala/org/datasyslab/geosparksql/UDF/Catalog.scala
- sql/src/test/scala/org/datasyslab/geosparksql/functionTestScala.scala
#468 
Added ST_AsGeoJSON SQL function
Added tests
Yes
> Added ST_AsGeoJSON

- core/pom.xml
- core/src/main/java/org/apache/sedona/core/geometryObjects/Circle.java
- core/src/main/java/org/apache/sedona/core/spatialPartitioning/RtreePartitioning.java
- core/src/main/java/org/apache/sedona/core/utils/GeomUtils.java
- core/src/test/java/org/apache/sedona/core/formatMapper/shapefileParser/shapes/ShapefileRDDTest.java
- core/src/test/java/org/apache/sedona/core/formatMapper/shapefileParser/shapes/ShapefileReaderTest.java
- core/src/test/java/org/apache/sedona/core/spatialOperator/JoinTestBase.java
- core/src/test/java/org/apache/sedona/core/spatialOperator/PointKnnTest.java
- core/src/test/java/org/apache/sedona/core/spatialOperator/PointRangeTest.java
> Improve jts dependency

- .github/workflows/example.yml
- examples/rdd-colocation-mining/build.sbt
- examples/rdd-colocation-mining/project/plugins.sbt
- examples/sql/build.sbt
- examples/sql/project/plugins.sbt
- examples/viz/build.sbt
- examples/viz/project/plugins.sbt
Add the CI test for three example projects of Scala and Java
> Add the CI test for example projects

- docs/api/sql/GeoSparkSQL-Function.md
- sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
https://issues.apache.org/jira/browse/SEDONA-15
Add the new geometry processing functions:
- ST_MinimumBoundingRadius
- ST_MinimumBoundingCircle
See unit tests
Yes
> [SEDONA-15] Add ST_MinimumBoundingRadius and ST_MinimumBoundingCircle functions

- docs/api/sql/GeoSparkSQL-Function.md
- sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
[[SEDONA-24]](https://issues.apache.org/jira/browse/SEDONA-24)
add geometry processing functions:
- ST_LineSubString
- ST_LineInterpolatePoint
scala test extended
yes
> [SEDONA-24] Add LineString interpolation functions

- docs/api/viz/sql.md
- docs/tutorial/viz.md
- viz/src/main/scala/org/apache/sedona/viz/sql/UDF/Catalog.scala
- viz/src/main/scala/org/apache/spark/sql/sedona_viz/expressions/Render.scala
- viz/src/test/scala/org/apache/sedona/viz/sql/standardVizOperatorTest.scala
https://issues.apache.org/jira/browse/SEDONA-32
1. Change the internal algorithm in ST_Render to speed up the rendering
2. Accept one more parameter: zoom level. It will be able to render small tiles.
Passed the unit tests
Yes
> [SEDONA-32] Speed up ST_Render

- examples/viz/src/main/scala/ScalaExample.scala
https://issues.apache.org/jira/browse/SEDONA-29
Use explode to contain ST_Pixelize result
Unit tests
yes, included in the previous PR of SEDONA-29
> [SEDONA-29] Update the ST_Pixelize usage in the example projects

- .github/workflows/example.yml
N/A
Replace the old bintrary url with https://repo.scala-sbt.org/scalasbt/debian
Pass the Example CI
N/A
> Fix the failed CI in Example CI

- docs/api/sql/Overview.md
No
I added the import statement on the quickstart documentation
No
Yes
> [DOCS] Added import on Quick start documentation

- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/simplify/GeometryCollectionSimplifier.scala
https://issues.apache.org/jira/browse/SEDONA-40
Fix the order
Pass CI tests
N/A
> [SEDONA-40] Pattern Match Wrong Ordering in GeometryCollectionSimplifier.scala

- core/src/main/scala/org/apache/sedona/core/showcase/ScalaExample.scala
https://issues.apache.org/jira/browse/SEDONA-72
Fixed the bug when   ScalaExample in showcase run
Run the ScalaExample  in showcase
no
> [SEDONA-72 ] Fix showcase execution bug

- README.md
Broken link to docs
Change to point to the correct path.
> [DOCS] fixing bad doc link

- docs/setup/databricks.md
No
The Databricks docs had some broken links in the sample scripts that were used to install Sedona. Those links were fixed.
There are also some wording changes.
Yes
> Update Databricks installation docs

- core/src/main/java/org/apache/sedona/core/enums/GridType.java
- core/src/main/java/org/apache/sedona/core/formatMapper/FormatMapper.java
- core/src/main/java/org/apache/sedona/core/formatMapper/FormatUtils.java
- core/src/main/java/org/apache/sedona/core/geometryObjects/GeometrySerde.java
- core/src/main/java/org/apache/sedona/core/geometryObjects/SpatialIndexSerde.java
- core/src/main/java/org/apache/sedona/core/spatialPartitioning/EqualPartitioning.java
- core/src/main/java/org/apache/sedona/core/spatialPartitioning/FlatGridPartitioner.java
- core/src/main/java/org/apache/sedona/core/spatialPartitioning/KDB.java
- core/src/main/java/org/apache/sedona/core/spatialPartitioning/KDBTreePartitioner.java
- core/src/main/java/org/apache/sedona/core/spatialPartitioning/PartitioningUtils.java
- core/src/main/java/org/apache/sedona/core/spatialPartitioning/QuadTreePartitioner.java
- core/src/main/java/org/apache/sedona/core/spatialPartitioning/quadtree/StandardQuadTree.java
- core/src/main/java/org/apache/sedona/core/spatialRDD/SpatialRDD.java
- pom.xml
https://issues.apache.org/jira/browse/SEDONA-77
Refactor format readers and spatial partitioning tools, and remove the Spark dependency in these tools 
Should pass the existing tests
No needed
> [SEDONA-77] Refactor format readers and spatial partitioning functions

- docs/setup/databricks.md
It was discussed on https://gitter.im/apache/sedona?at=61eb6179742c3d4b21acbbc4
Updated the Databricks docs for DBR 8.x+
Yes
> [DOCS] Databricks DBR 8.x+ docs update

- .gitignore
https://issues.apache.org/jira/projects/SEDONA/issues/SEDONA-78
Add intellij files to gitignore
N/A
N/A
> [SEDONA-78] Add Intellij generated files to gitignore

- core/src/test/java/org/apache/sedona/core/formatMapper/shapefileParser/shapes/ShapefileReaderTest.java
- docs/api/sql/Function.md
- python/tests/sql/test_function.py
- sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
[SEDONA-65](https://issues.apache.org/jira/browse/SEDONA-65)
ST_Difference function
Scala, Python integration tests
Yes
> [SEDONA-65] Create ST_Difference function

- .github/workflows/r.yml
Update R build to Spark 3.2.1 to fix the failed CI test
Passed the R CI tests
> [CI] Update R build from Spark 3.2.0 to 3.2.1

- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
https://issues.apache.org/jira/browse/SEDONA-82
Fixes in ST_Difference, ST_SymDifference to handle null values.
New Scala unit tests added 
No
> [SEDONA-82] Fixes in ST_Difference and ST_SymDifference

- flink/src/main/java/org/apache/sedona/flink/expressions/Constructors.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Predicates.java
- flink/src/test/java/org.apache.sedona/flink/AdapterTest.java
- flink/src/test/java/org.apache.sedona/flink/FunctionTest.java
- flink/src/test/java/org.apache.sedona/flink/TestBase.java
https://issues.apache.org/jira/browse/SEDONA-87
Use  @DataTypeHint(value = "RAW", bridgedTo = org.locationtech.jts.geom.Geometry.class) for Geometry, instead of @DataTypeHint("RAW")
Added a new unit test
No
> [SEDONA-87] Support Flink Table and DataStream conversion

- docs/api/flink/Constructor.md
- docs/api/flink/Function.md
- docs/api/flink/Overview.md
- docs/api/flink/Predicate.md
- docs/setup/flink/install-scala.md
- docs/setup/flink/modules.md
- docs/setup/flink/platform.md
- docs/setup/maven-coordinates.md
- docs/setup/modules.md
- docs/setup/overview.md
- docs/setup/platform.md
- docs/setup/release-notes.md
- docs/tutorial/flink/sql.md
- mkdocs.yml
This is a doc-only PR. It refactored the website for Flink info.
> [DOCS] Add Flink tutorial and prepare docs for the next release

- docs/setup/publish.md
- pom.xml
> [DOCS] Add more details to software release

- docs/api/sql/Function.md
- python/tests/sql/test_function.py
- sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
[SEDONA-90](https://issues.apache.org/jira/browse/SEDONA-90)
ST_Union function
Scala, Python integration tests
Yes
> [SEDONA-90] Create ST_Union function

- docs/api/flink/Constructor.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Constructors.java
- flink/src/test/java/org/apache/sedona/flink/ConstructorTest.java
- flink/src/test/java/org/apache/sedona/flink/TestBase.java
[SEDONA-93](https://issues.apache.org/jira/browse/SEDONA-93)
Added ST_GeomFromGeoJSON to flink API
Added test
Yep
> [SEDONA-93] Add ST_GeomFromGeoJSON to flink API

- .github/workflows/scripts/install_r_deps.sh
- .github/workflows/scripts/install_system_deps_for_r_build.sh
- .github/workflows/scripts/prepare_sparklyr_sedona_test_env.sh
- NOTICE
Update the NOTICE file
Add ASF header in shell scripts
> [DOCS] Fix copyright issues

- docs/api/flink/Predicate.md
- docs/api/sql/Predicate.md
- docs/archive/api/sql/GeoSparkSQL-Predicate.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Predicates.java
- flink/src/test/java/org/apache/sedona/flink/PredicateTest.java
- sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Predicates.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
- sql/src/test/scala/org/apache/sedona/sql/predicateTestScala.scala
Yes - [SEDONA 95](https://issues.apache.org/jira/browse/SEDONA-95)
Added ST_Disjoint predicate
Yes I have added unit tests
Yes. Added descriptions in the source code.
> [SEDONA 95] Add ST_Disjoint predicate

- core/src/main/java/org/apache/sedona/core/utils/GeomUtils.java
- docs/api/flink/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
[SEDONA-112](https://issues.apache.org/jira/projects/SEDONA/issues/SEDONA-112)
ST_AsEWKT Function
Yes I have added unit tests
Yes.
> [SEDONA-112] Add ST_AsEWKT

- core/src/main/java/org/apache/sedona/core/utils/GeomUtils.java
- docs/api/flink/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- pom.xml
- python/tests/sql/test_function.py
- sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
[SEDONA-97](https://issues.apache.org/jira/browse/SEDONA-97)
ST_Force_2D function
I have added unit tests in Java, Scala and python.
Yes.
> [SEDONA-97] Add ST_Force_2D function to Apache Sedona

- docs/api/flink/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/projects/SEDONA/issues/SEDONA-116.
Added ST_YMax and ST_YMin functions
Added unit tests as well.
Yes it includes docs changes as well.
> [SEDONA-116] Add ST_YMax and ST_YMin function

- docs/api/flink/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/projects/SEDONA/issues/SEDONA-115.
Added ST_XMax and ST_XMin functions
Added unit tests as well.
Yes, it includes docs changes as well.
> [SEDONA-115] Add ST_XMax and ST_XMin function

- docs/api/flink/Constructor.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Constructors.java
- flink/src/test/java/org/apache/sedona/flink/ConstructorTest.java
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-110. The PR name follows the format `[SEDONA-110] my subject`.
Added STGeomFromGeohash to Flink API
Added 2 tests:
1. Regular case
2. Case without precision
> [SEDONA-110] Add STGeomFromGeohash to Flink API

- docs/api/flink/Predicate.md
- docs/api/sql/Function.md
- docs/api/sql/Predicate.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Predicates.java
- python/tests/sql/test_function.py
- python/tests/sql/test_predicate.py
- sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Predicates.scala
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- sql/src/test/scala/org/apache/sedona/sql/predicateTestScala.scala
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-109 The PR name follows the format `[SEDONA-109] my subject`.
ST_OrderingEquals function
Scala, Python integration tests
> [SEDONA-109] Add ST_OrderingEquals to Apache Sedona

- docs/api/sql/Function.md
- sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/collect/ST_CollectionExtract.scala
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-124. The PR name follows the format `[SEDONA-124] my subject`.
Added ST_CollectionExtract to Apache Sedona
Yes, I have updated the documentation update.
> [SEDONA-124] Add ST_CollectionExtract to Apache Sedona

- docs/setup/databricks.md
Clarify that the python package must still be installed via the web ui while using the init script method.
N/A
> [DOCS] clarify databricks install

- .github/workflows/java.yml
- .github/workflows/python.yml
- pom.xml
- python/sedona/utils/adapter.py
- python/sedona/utils/spatial_rdd_parser.py
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-129. The PR name follows the format `[SEDONA-XXX] my subject`.
Bump Spark version to 3.3.0. Update GitHub workflows to test this as well.
Updated workflows.
> [SEDONA-129] Bump spark to 3.3.0

- docs/tutorial/sql-r.md
> [DOCS] fix dplyr demo

- binder/NdviSentinelApacheSedona
Example using imagens from GEE collection Sentinel and Using Normalize to calculate NDVI
Did you read the Contributor Guide?
Yes, I have read [Contributor Rules](https://sedona.apache.org/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/community/develop/)
Is this PR related to a JIRA ticket?
Yes, The PR name follows the format python-vector-osm.md (PR #582).
What changes were proposed in this PR?
New example
Did this PR include necessary documentation updates?
No, this PR does not affect any public API so no need to change the docs.
> [DOCS] Create NdviSentinelApacheSedona

- binder/PostgresqlConnectionApacheSedona.ipynb
> [DOCS] Create PostgresqlConnectionApacheSedona.ipynb

- docs/tutorial/python-vector-osm.md
I've found it difficult to find more complex examples at this documentation so I made this one, that involves spark slaves, osm data and hdfs. I hope it can be helpfull to someone else in the future.
No
A new documentation example to guide other developers, in a more complex environment, closest to reality of some needs they may have as well
The examples were tested at jupyter, connected to a spark infrastruture, with 4 slaves machines
Yes
> [DOCS] Create python-vector-osm.md

- binder/ApacheSedonaImageFilter
Examples of image filters from apache sedona functions
Did you read the Contributor Guide?
Yes, I have read [Contributor Rules](https://sedona.apache.org/community/rule/) and [Contributor Development Guide](https://sedona.apache.org/community/develop/)
Is this PR related to a JIRA ticket?
Yes, The PR name follows the format python-vector-osm.md (PR #582).
What changes were proposed in this PR?
New example
Did this PR include necessary documentation updates?
No, this PR does not affect any public API so no need to change the docs.
> [DOCS] Create ApacheSedonaImageFilter

- binder/DownloadImageFromGEE.ipynb
One example of how to get data from GEE and save it inside hdfs to use with spark
- No, this PR does not affect any public API so no need to …
> [DOCS] Create DownloadImageFromGEE.ipynb

- .github/workflows/java.yml
- pom.xml
Currently, the CI only tested Spark 3.3 and Spark 2.4. This PR will enable the tests on all supported Spark versions.
> [DOCS] Enable CI on all supported Spark versions

- R/R/dependencies.R
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-140. The PR name follows the format `[SEDONA-XXX] my subject`.
- Updating the `dependencies.R` file to use Sedona version 1.2.0 instead of 1.0.0.
- Ran `devtools::test()` locally and all tests passed. 
> [SEDONA-140] Update Sedona Dependencies in R Package

- common/src/main/java/org/apache/sedona/common/Functions.java
- docs/api/flink/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-144. The PR name follows the format `[SEDONA-XXX] my subject`.
- This PR adds ST_AsGeoJSON to the Flink API.
- Ran `mvn clean install` and ensured that all compilations and tests succeeded.
> [SEDONA-144] Add ST_AsGeoJSON to the Flink API

- common/src/main/java/org/apache/sedona/common/Functions.java
- docs/api/flink/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-147. The PR name follows the format `[SEDONA-XXX] my subject`.
- This PR adds ST_SetSRID and ST_SRID to the Flink API
- Ran `mvn clean install` locally
> [SEDONA-147] Add SRID funtions to the Flink API

- common/src/main/java/org/apache/sedona/common/Functions.java
- common/src/main/java/org/apache/sedona/common/geometryObjects/Circle.java
- core/src/main/java/org/apache/sedona/core/geometryObjects/GeometrySerde.java
- core/src/main/java/org/apache/sedona/core/serde/SedonaKryoRegistrator.java
- core/src/main/java/org/apache/sedona/core/spatialOperator/JoinQuery.java
- core/src/main/java/org/apache/sedona/core/spatialRDD/CircleRDD.java
- core/src/test/java/org/apache/sedona/core/formatMapper/shapefileParser/shapes/GeometrySerdeTest.java
- core/src/test/java/org/apache/sedona/core/geometryObjects/CircleTest.java
- core/src/test/java/org/apache/sedona/core/utils/CRSTransformationTest.java
- docs/api/flink/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/SedonaFlinkRegistrator.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- python-adapter/src/main/scala/org.apache.sedona.python.wrapper/translation/CircleSerializer.scala
- python-adapter/src/main/scala/org.apache.sedona.python.wrapper/translation/PythonGeometrySerializer.scala
- python-adapter/src/main/scala/org.apache.sedona.python.wrapper/translation/PythonRDDToJavaConverter.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/collect/Collect.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/simplify/CircleSimplifier.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/simplify/GeometryCollectionSimplifier.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/simplify/GeometrySimplifier.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/DistanceJoinExec.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryBase.scala
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-148. The PR name follows the format `[SEDONA-XXX] my subject`.
- This PR adds ST_IsClosed, ST_IsRing, ST_IsSimple, and ST_IsValid to the Flink API.
- Ran `mvn clean install` and `mkdocs serve` locally.
> [SEDONA-148] Add boolean functions to the Flink API

- .github/workflows/java.yml
- .github/workflows/python.yml
- .github/workflows/r.yml
- common/pom.xml
- pom.xml
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-150. The PR name follows the format `[SEDONA-150] my subject`.
See the JIRA ticket for details.
Pass CI test
A documentation update will follow
> [SEDONA-150] Drop Spark 2.4 and Scala 2.11 support

- docs/api/sql/Function.md
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-158. The PR name follows the format `[SEDONA-XXX] my subject`.
- This PR fixes a wrong description about ST_GeometryN in the API document.
- Ran `mkdocs serve` and checked the generated document.
> [SEDONA-158] Fix wrong description about ST_GeometryN in the API docs

- common/src/main/java/org/apache/sedona/common/Functions.java
- docs/api/flink/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-162. The PR name follows the format `[SEDONA-XXX] my subject`.
This PR adds ST_Envelope to the Flink API.
- Ran `mvn clean install` locally
- Ran `mkdocs serve` and checked the generated documents
> [SEDONA-162] Add ST_Envelope to the Flink API

- docs/community/publish.md
- pom.xml
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-165. The PR name follows the format `[SEDONA-XXX] my subject`.
- This PR upgrades Apache Rat to the current latest version, 0.14.
- Ran `mvn apache-rat:check` locally and saw its output.
> [SEDONA-165] Upgrade Apache Rat to 0.14

- docs-overrides/partials/footer.html
- docs/asf/asf.md
- docs/asf/disclaimer.md
- docs/community/contributor.md
- docs/download.md
- docs/setup/compile.md
- mkdocs.yml
> [DOCS] Fix Sedona website to be compliant with ASF requirement

- R/DESCRIPTION
- R/R/spatial_queries.R
Remove DBI as a R dependency to comply with certain software licensing terms.
`R CMD build` followed by `R CMD check --as-cran`
> [DOCS] remove DBI as a R dependency

- common/src/main/java/org/apache/sedona/common/Functions.java
- docs/api/flink/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-168. The PR name follows the format `[SEDONA-XXX] my subject`.
- This PR introduces the `ST_Normalize` function to the Spark and Flink APIs.
- Ran `mvn clean install` locally
- Ran `mkdocs serve` and checked the generated documents
> [SEDONA-168] Add ST_Normalize to Apache Sedona

- common/src/main/java/org/apache/sedona/common/Functions.java
- common/src/main/java/org/apache/sedona/common/utils/GeomUtils.java
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-193. The PR name follows the format `[SEDONA-XXX] my subject`.
Fix a regression in ST_AsBinary
Unit test added
> [SEDONA-193] Regression in ST_AsBinary

- docs/community/publish.md
- docs/community/release-manager.md
- docs/community/snapshot.md
- pom.xml
> [DOCS] Further automate the release script

- sql/src/test/scala/org/apache/sedona/sql/ogc/GeometryTypesAndFunctionsTestScala.scala
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-179. The PR name follows the format `[SEDONA-XXX] my subject`.
Implemented three tests from the OGC compliance test suite.
If you are happy with the overall structure you can go ahead and merge and I will implement the remainder of the tests.
Unit tests.
> [SEDONA-179] Claim OGC compliance.

- pom.xml
- sql/pom.xml
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-210. The PR name follows the format `[SEDONA-210] my subject`.
Move scala-collection-compat to SQL module
> [SEDONA-210] Package scala-collection-compat dependency to sql module

- .github/workflows/java.yml
> [SEDONA-211] Use CI to ensure source code work for both JDK 8 and 11

- pom.xml
- sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-XXX. The PR name follows the format `[[SEDONA-216](https://issues.apache.org/jira/browse/SEDONA-216)] Upgrate jts version to 1.19.0`.
Upgrade jts version to the latest.
Scala, Python, and Java integration and Unit tests.
> [SEDONA-216] Upgrade jts version to 1.19.0

- R/tests/testthat/test-spatial-queries.R
> [DOCS] remove DBI call in test-spatial-queries.R

- .github/workflows/docs.yml
- docs-overrides/main.html
- docs/community/publish.md
- docs/download.md
- docs/index.md
- docs/setup/maven-coordinates.md
- mkdocs.yml
> [DOCS] Add the news about Sedona 1.3.1-incubating and fix a bunch of typos

- common/src/main/java/org/apache/sedona/common/geometrySerde/UnsafeGeometryBuffer.java
- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-207. The PR name follows the format `[SEDONA-XXX] my subject`.
Remove dependency to spark from `sedona-common`. This change is requested by https://github.com/apache/incubator-sedona/pull/739#discussion_r1059687208.
The existing unit tests are sufficient to test this patch.
> [SEDONA-207] Remove dependency to spark from UnsafeGeometryBuffer in sedona-common

- R/R/data_interface.R
- mkdocs.yml
- python/sedona/core/SpatialRDD/spatial_rdd.py
- sql/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoDateTimeUtils.scala
- sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/Functions.scala
- sql/src/test/scala/org/apache/sedona/sql/adapterTestScala.scala
> [DOCS] Fix spelling

- docs/api/flink/Aggregator.md
- docs/api/flink/Constructor.md
- docs/api/flink/Function.md
- docs/api/flink/Predicate.md
- docs/api/sql/AggregateFunction.md
- docs/api/sql/Constructor.md
- docs/api/sql/Function.md
- docs/api/sql/Optimizer.md
- docs/api/sql/Overview.md
- docs/api/sql/Parameter.md
- docs/api/sql/Predicate.md
- docs/api/sql/Raster-loader.md
- docs/api/sql/Raster-operators.md
- docs/api/viz/sql.md
- docs/setup/databricks.md
- docs/setup/install-python.md
- docs/setup/install-r.md
- docs/tutorial/Advanced-Tutorial-Tune-your-Application.md
- docs/tutorial/core-python.md
- docs/tutorial/flink/sql.md
- docs/tutorial/rdd-r.md
- docs/tutorial/rdd.md
- docs/tutorial/sql-r.md
- docs/tutorial/sql.md
- docs/tutorial/viz-r.md
Remove unneeded whitespace and use lowercase
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml
Remove whitespace at end of code blocks
Standardizing the Markdown code blocks
> [DOCS] Markdown: Standardize code block linguist languages

- sql/src/test/scala/org/apache/sedona/sql/rasterIOTest.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-252. The PR name follows the format `[SEDONA-XXX] my subject`.
Improve the RS_Base64 test
Pass the unit tests
> [SEDONA-252] Fix RS_Base64 test

- binder/ApacheSedonaRaster.ipynb
> [DOCS] Fix typo

- R/R/dependencies.R
See https://issues.apache.org/jira/projects/SEDONA/issues/SEDONA-255
Remove casting to decimal(24,20) for coordinates
Ran all tests
> [SEDONA-255] R – Translation issue for ST_Point and ST_PolygonFromEnvelope

- .github/workflows/scripts/prepare_sparklyr_sedona_test_env.sh
- R/R/dependencies.R
- R/apache.sedona.Rproj
- R/tests/testthat/helper-initialize.R
https://issues.apache.org/jira/projects/SEDONA/issues/SEDONA-250?
Update dependencies to 28.2
Remove support for Spark 2.4
Ran the tests
> [SEDONA-250][SEDONA-253] R - Update dependencies + drop 2.4

- R/tests/testthat/test-data-interface-raster.R
https://issues.apache.org/jira/projects/SEDONA/issues/SEDONA-254?
Adding tests for binary raster functions
Created and ran tests
> [SEDONA-254] R – Add tests for RasterUDT

- docs/setup/release-notes.md
- docs/tutorial/geopandas-shapely.md
- No, this is a documentation update.
- Minor typo fix I noticed while viewing the release notes
N/A
> [DOCS] Fix to v1.4.0 release docs

- binder/ApacheSedonaSQL.ipynb
- binder/Pipfile
Change GeoPandas version to 0.11.1 which pins Shapely version < 2.0
Pass binder notebook check
> [DOCS] Fix GeoPandas version in notebooks

- docs/api/sql/Raster-loader.md
> [DOCS] Fix spelling in Markdown

- README.md
- Typos that were present in the documentation.
- This is a documentation update
> [DOCS] update: documentation typos

- docs/tutorial/viz.md
Just added "spark-" in the link because the example folder was moved.
> [DOCS] Fix broken link

- docs/community/publish.md
Remove the DISCLAIMER step from the checklist for votes.
N/A
> [DOCS] Remove the DISCLAIMER step from the checklist for votes

- sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-311. The PR name follows the format `[SEDONA-XXX] my subject`.
Fixed conflicts with the ST_Dimension patch
Existing unit tests
> [SEDONA-311] Fix conflict with ST_Dimension (20e0de4)

- docs/api/flink/Predicate.md
- docs/api/sql/Predicate.md
Editing docs of each function in Predicate for Spark and Flink.
On my local Ubuntu VM
> [DOCS] Add example outputs to all Sedona functions - 8

- docs/api/flink/Aggregator.md
- docs/api/sql/AggregateFunction.md
Editing docs of each function in Aggregate for Spark and Flink.
On my local Ubuntu VM
> [DOCS] Add example outputs to all Sedona functions - 9

- common/src/main/java/org/apache/sedona/common/raster/RasterAccessors.java
- common/src/test/java/org/apache/sedona/common/raster/RasterAccessorsTest.java
- docs/api/sql/Raster-operators.md
- sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterAccessors.scala
- sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-359. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add RS_GeoReference
- Passed new tests
> [SEDONA-359] Add RS_GeoReference

- docs/api/sql/Raster-operators.md
- sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/MapAlgebra.scala
- sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-365. The PR name follows the format `[SEDONA-XXX] my subject`.
- Renamed RS_Count to RS_CountValue
- With existing tests.
> [SEDONA-365] Refactor RS_Count to RS_CountValue

- common/src/main/java/org/apache/sedona/common/raster/PixelFunctions.java
- common/src/test/java/org/apache/sedona/common/raster/FunctionsTest.java
- docs/api/sql/Raster-operators.md
- sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/PixelFunctions.scala
- sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-363. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add RS_PixelAsPolygon
- Passed all added tests
> [SEDONA-363] Add RS_PixelAsPolygon

- common/src/main/java/org/apache/sedona/common/raster/GeometryFunctions.java
- common/src/main/java/org/apache/sedona/common/raster/RasterConstructors.java
- common/src/test/java/org/apache/sedona/common/raster/GeometryFunctionsTest.java
- docs/api/sql/Raster-operators.md
- sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/GeometryFunctions.scala
- sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-364. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add RS_MinConvexHull
- Added new tests
> [SEDONA-364] Add RS_MinConvexHull

- common/src/main/java/org/apache/sedona/common/raster/PixelFunctions.java
- common/src/test/java/org/apache/sedona/common/raster/FunctionsTest.java
- docs/api/sql/Raster-operators.md
- sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/PixelFunctions.scala
- sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-367. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add RS_PixelAsCentroid
- Passed all added tests
> [SEDONA-367] Add RS_PixelAsCentroid

- common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
- common/src/test/java/org/apache/sedona/common/raster/RasterBandEditorsTest.java
- docs/api/sql/Raster-operators.md
- sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterBandEditors.scala
- sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-375. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add RS_SetBandNoDataValue
- Passed added tests
> [SEDONA-375] Add RS_SetBandNoDataValue

- docs/community/contributor.md
- docs/community/release-manager.md
> [DOCS] Fix spelling change `Github` to `GitHub`

- examples/flink-sql/pom.xml
- examples/spark-rdd-colocation-mining/build.sbt
- examples/spark-sql/build.sbt
- examples/spark-viz/build.sbt
- pom.xml
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-385. The PR name follows the format `[SEDONA-385] my subject`.
Set Maven Central repo to be the first repo to check
Passed existing tests
> [SEDONA-385] Set the Maven Central to be the first repository to check

- docs/api/flink/Function.md
- docs/api/sql/Function.md
- docs/api/sql/Optimizer.md
- docs/setup/release-notes.md
- docs/tutorial/flink/sql.md
Standardized the Markdown files for whitespace
> [DOCS] Fix whitespace in Markdown files

- README.md
> [DOCS] Fix typo in README

- common/src/main/java/org/apache/sedona/common/raster/PixelFunctionEditors.java
- common/src/test/java/org/apache/sedona/common/raster/FunctionEditorsTest.java
- common/src/test/java/org/apache/sedona/common/raster/RasterConstructorsTest.java
- docs/api/sql/Raster-operators.md
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/PixelFunctionEditors.scala
- spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-396. The PR name follows the format `[SEDONA-XXX] my subject`.
- add RS_SetValues geometry variant.
- add java docs for all functions in PixelFunctionEditors
- passed added tests
> [SEDONA-396] Add RS_SetValues Geometry variant

- docs/api/flink/Aggregator.md
- docs/api/flink/Constructor.md
- docs/api/flink/Function.md
- docs/api/flink/Predicate.md
- docs/api/sql/AggregateFunction.md
- docs/api/sql/Constructor.md
- docs/api/sql/Function.md
- docs/api/sql/Predicate.md
- docs/api/sql/Raster-loader.md
- docs/api/sql/Raster-operators.md
- docs/api/sql/Raster-visualizer.md
- docs/api/sql/Raster-writer.md
- docs/api/viz/sql.md
> [DOCS] Docs cleaning

- README.md
HTML changes to standardize the images
> [DOCS] README: Add `alt` to images and add links

- README.md
Removes the duplicate Discord button
> [DOCS] Remove duplicate Discord button from README

- common/src/main/java/org/apache/sedona/common/raster/RasterOutputs.java
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-401. The PR name follows the format `[SEDONA-XXX] my subject`.
- Fix bugs in RS_AsMatrix to handle null values
- Tested asMatrix with a raster having null values 
> [SEDONA-401] Handle null values in RS_AsMatrix

- common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-402. The PR name follows the format `[SEDONA-XXX] my subject`.
- Floor grid coordinates received from geotools
- Tested grid coordinates
> [SEDONA-402] Floor grid coordinates received from geotools to handle floating point grid coordinates.

- common/src/main/java/org/apache/sedona/common/raster/RasterOutputs.java
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-403. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add null tolerance to RS_AddBandFromArray
- Tested null arguments in RS_AddBandFromArray
> [SEDONA-403] Add null tolerance to RS_AddBandFromArray

- docs/api/sql/Raster-visualizer.md
- docs/tutorial/raster.md
- Fix a typo in raster tutorial
- Fix incorrect API name in raster-visualizer
- Compiled documentation
> [DOCS] Fix typo and incorrect API name

- docs/tutorial/raster.md
> [DOCS] Few grammatical fix in raster tutorial

- R/man/apache.sedona-package.Rd
- R/man/crs_transform.Rd
- R/man/spark_read_shapefile.Rd
- R/man/spark_write_geojson.Rd
Use roxygen to regenerate docs in R/man
> [DOCS] R: Update roxygen docs

- docs/api/java-api.md
- docs/api/sql/Overview.md
- docs/api/viz/java-api.md
- docs/community/publish.md
- docs/download.md
- docs/index.md
- docs/setup/compile.md
- docs/setup/release-notes.md
- docs/tutorial/sql.md
- mkdocs.yml
Add news and corresponding website update
> [DOCS] Add news for 1.5.0

- R/man/apache.sedona-package.Rd
- R/man/spark_read_shapefile.Rd
- R/man/spark_write_geojson.Rd
- docs/community/discord-invite-form.html
Fix a couple of doc issues raised by the official CRAN release check 
Passed the official CRAN check
> [DOSC] Fix CRAN failure

- R/README.md
- R/vignettes/articles/apache-sedona.Rmd
- README.md
- docs/api/flink/Function.md
- docs/api/sql/Function.md
Standardized the start of the Markdown code blocks
> [DOCS] Standardize Markdown code blocks: word case and whitespace

- docs/setup/emr.md
Just a small fix. Set apache-sedona version to correct version. ☺️
N/A
> [DOCS] set correct apache-sedona version

- docker/sedona-spark-jupyterlab/requirements.txt
- docker/sedona-spark-jupyterlab/sedona-jupyterlab.dockerfile
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-418. The PR name follows the format `[SEDONA-418] my subject`.
Update Sedona docker to use Sedona 1.5.0
Tested all notebooks locally in the container
> [SEDONA-418] Update Sedona docker image to 1.5.0

- R/tests/testthat/test-data-interface.R
- R/tests/testthat/test-sdf-interface.R
Fixing failing R tests (changes in the tests themselves)
> [DOCS] Fix failing R tests after update of dbplyr

- .github/workflows/java.yml
- Yes
Add postfix to each job so the name is unique, as recommended by https://github.com/actions/upload-artifact
Testing in this PR
> [SEDONA-503] Fix the upload-artifact 503 error

- .github/workflows/docs.yml
- .github/workflows/example.yml
- .github/workflows/java.yml
- .github/workflows/python-extension.yml
- .github/workflows/python-wheel.yml
- .github/workflows/python.yml
- .github/workflows/r.yml
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-339. The PR name follows the format `[SEDONA-339] my subject`.
Scala/Java build should only be triggered when scala/java files get modified
Python build should only be triggered when scala/java/python files get modified
R build should only be triggered when scala/java/R files get modified
Testing in this PR
> [SEDONA-339] Skip irrelevant GitHub actions

- docs/image/sedona_logo_symbol_white.svg
- mkdocs.yml
- Add Sedona logo to the upper left corner.
> [DOCS] add Sedona logo

- .github/workflows/java.yml
- .github/workflows/python.yml
- .github/workflows/r.yml
- docs/setup/platform.md
- pom.xml
- spark/common/pom.xml
- spark/pom.xml
- spark/spark-3.5/.gitignore
- spark/spark-3.5/pom.xml
- spark/spark-3.5/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
- spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetFileFormat.scala
- spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetReadSupport.scala
- spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetRecordMaterializer.scala
- spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetRowConverter.scala
- spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetSchemaConverter.scala
- spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetUtils.scala
- spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetWriteSupport.scala
- spark/spark-3.5/src/test/resources/log4j2.properties
- spark/spark-3.5/src/test/scala/org/apache/sedona/sql/GeoParquetSpatialFilterPushDownSuite.scala
- spark/spark-3.5/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala
- spark/spark-3.5/src/test/scala/org/apache/sedona/sql/geoparquetIOTests.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-450. The PR name follows the format `[SEDONA-XXX] my subject`.
Add a submodule `spark-3.5` to support reading/writing GeoParquet files in Spark 3.5
Passing existing tests.
> [SEDONA-450] Support Spark 3.5

- Makefile
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-463. The PR name follows the format `[SEDONA-XXX] my subject`.
The Makefile will contain the three main commands for using pre-commit locally
Ran each command from the Makefile on my local machine
> [SEDONA-463] Add a Makefile for convenience

- docs/setup/compile.md
Fixing some grammar in the docs
Visual check and review of grammar
> [DOCS] Fix grammar in `docs/setup/compile.md`

- snowflake-tester/pom.xml
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-459. The PR name follows the format `[SEDONA-XXX] my subject`.
Replaced the hard-coded `1.5.1-SNAPSHOT` with the project config
> [SEDONA-459] Open-source Sedona Snowflake: fix the wrong version setting in Snowflake tester

- docs/setup/install-scala.md
- docs/tutorial/sql-pure-sql.md
sedona-viz was removed since 1.5.0. This PR removes sedona-viz from spark commands accordingly.
Verified locally and passed CI.
> [DOCS] Remove sedona-viz from spark setup manual

- common/pom.xml
- flink-shaded/pom.xml
- flink/pom.xml
- pom.xml
- snowflake-tester/pom.xml
- snowflake/pom.xml
- spark-shaded/pom.xml
- spark/common/pom.xml
- spark/pom.xml
- spark/spark-3.0/pom.xml
- spark/spark-3.4/pom.xml
- spark/spark-3.5/pom.xml
Bump all Maven module versions to 1.6.0-SNAPSHOT
> [DOCS] Bump the Maven version to 1.6.0-SNAPSHOT

- docker/sedona-spark-jupyterlab/sedona-jupyterlab.dockerfile
- docker/sedona.sh
1. Docker image `latest` tag does not include gresearch and geotools
2. `sedona-spark` jar wasn't removed from the notebooks
> [DOCS] Fix bugs in Docker images

- binder/ApacheSedonaCore.ipynb
Fixed spelling in code comments
> [DOCS] Fix spelling in `binder/ApacheSedonaCore.ipynb`

- binder/Sedona_OvertureMaps_GeoParquet.ipynb
> [DOCS] Fix spelling in `binder/Sedona_OvertureMaps_GeoParquet.ipynb`

- docs/api/flink/Function.md
- docs/api/sql/AggregateFunction.md
- docs/api/sql/Constructor.md
- docs/api/sql/Function.md
- docs/api/sql/Optimizer.md
- docs/api/sql/Predicate.md
- docs/api/sql/Raster-aggregate-function.md
- docs/api/sql/Raster-loader.md
- docs/api/sql/Raster-operators.md
- docs/api/sql/Raster-visualizer.md
- docs/api/sql/Raster-writer.md
- docs/api/viz/sql.md
- mkdocs.yml
1. Replace `Spark SQL Example` with `SQL Example`
2. Add `Snowflake` and `Flink` to the names of function docs.
> [DOCS] Replace `Spark SQL Example` and add Snowflake and Flink to the names of function docs.

- python/src/geomserde_speedup_module.c
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-512. The PR name follows the format `[SEDONA-512] my subject`.
Geometry_serde.serialize should report the incorrect type in the error message (contributed by @rbavery )
Passed existing tests
> [SEDONA-512] Geometry_serde.serialize should report the incorrect type

- snowflake/pom.xml
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-520. The PR name follows the format `[SEDONA-XXX] my subject`.
Added missing commons-lang3 dependency to snowflake/pom.xml.
Passed https://github.com/wherobots/sedona-snowflake-tester/pull/20
> [SEDONA-520] Fix dependency issue of shaded snowflake JAR

- README.md
Fixes pre-commit.
Orders the TOC links. Adds a missing link for docker
Ran locally:
> [DOCS] README: order toc links and remove extra line

- README.md
Added the missing links to the README TOC
Ran locally:
Also visually inspected the links and clicked on them.
> [DOCS] Complete the README TOC

- .pre-commit-config.yaml
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-528. The PR name follows the format `[SEDONA-XXX] my subject`.
Added another hook to our pre-commit framework.
https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#check-yaml
Ran locally:
> [SEDONA-528] Add `pre-commit` hook `check-yaml`

- .github/pull_request_template.md
Cleaned up the pull request template.
Just by reading the new better version.
> [DOCS] Fix grammar in the `pull_request_template.md`

- .github/workflows/docs.yml
Prepull the website branch before deploying to the website branch, as recommended by https://github.com/jimporter/mike
Tested in the CI
> [CI] Address the race condition among multiple CI deploying to the website branch

- mkdocs.yml
Add the scarf pixel to track the traffic of the Sedona website. Scarf fully supports the GDPR and is allowed by the Apache Software Foundation. See https://privacy.apache.org/policies/privacy-policy-public.html and https://privacy.apache.org/faq/committers.html
> [DOCS] Add the scarf pixel for traffic analytics

- .pre-commit-config.yaml
https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#debug-statements
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-530. The PR name follows the format `[SEDONA-XXX] my subject`.
Added another check to our pre-commit framework.
- debug-statements
Check for debugger imports and py37+ `breakpoint()` calls in python source.
Ran locally:
> [SEDONA-530] Add `pre-commit` hook `debug-statements`

- python/README.md
Add the scarf pixel to track the traffic of Sedona PyPi README. Scarf fully supports the GDPR and is allowed by the Apache Software Foundation. See [privacy.apache.org/policies/privacy-policy-public.html](https://privacy.apache.org/policies/privacy-policy-public.html) and [privacy.apache.org/faq/committers.html](https://privacy.apache.org/faq/committers.html)
> [DOCS] Add traffic analysis to PyPI README

- docs/api/flink/Function.md
- docs/api/snowflake/vector-data/Function.md
- docs/api/sql/Function.md
Fixed some spelling and grammar.
Read and spell checked.
> [DOCS] Fix spelling and remove duplicate word

- common/src/main/java/org/apache/sedona/common/Functions.java
- common/src/test/java/org/apache/sedona/common/FunctionsTest.java
- docs/api/flink/Function.md
- docs/api/snowflake/vector-data/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- python/sedona/sql/st_functions.py
- python/tests/sql/test_dataframe_api.py
- python/tests/sql/test_function.py
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctions.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsV2.java
- snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
- snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFsV2.java
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
- spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
- spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-533. The PR name follows the format `[SEDONA-533] my subject`.
Implement ST_Polygonize
> [SEDONA-533] Add ST_Polygonize

- .github/labeler.yml
- .github/workflows/labeler.yml
https://github.com/actions/labeler
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-535. The PR name follows the format `[SEDONA-XXX] my subject`.
Adds the pull request labeler to increase automation.
> [SEDONA-535] Add the pull request labeler

- docs/setup/compile.md
> [DOCS] Add information on pre-commit to `docs/setup/compile.md`

- .github/workflows/python-extension.yml
Change the `macos-latest` to `macos-13`
> [CI] Fix the failed python build extension

- python/sedona/sql/st_constructors.py
- python/tests/sql/test_dataframe_api.py
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-548. The PR name follows the format `[SEDONA-XXX] my subject`.
- A few constructor functions weren't registered as they were supposed to.
- Add Dataframe API tests
> [SEDONA-548] Fix Python Dataframe API Constructor registrations

- .github/workflows/docker-build.yml
Fix the failed docker build by using `macos-13`. `macos-latest` recently got updated.
Passed CI
> [CI] Fix the failed Docker build

- docs/image/snowflake/sedona-snowflake-1.5.1.sql
- docs/image/snowflake/sedona-snowflake.sql
- docs/setup/release-notes.md
- docs/usecases/Sedona_OvertureMaps_GeoParquet.ipynb
- mkdocs.yml
1. Added release notes
2. Updated release version
3. Updated sedona-snowflake.sql
> [DOCS] Add 1.5.2 release notes and doc changes

- R/DESCRIPTION
- R/R/dependencies.R
- common/pom.xml
- flink-shaded/pom.xml
- flink/pom.xml
- pom.xml
- python/sedona/version.py
- snowflake-tester/pom.xml
- snowflake/pom.xml
- spark-shaded/pom.xml
- spark/common/pom.xml
- spark/pom.xml
- spark/spark-3.0/pom.xml
- spark/spark-3.4/pom.xml
- spark/spark-3.5/pom.xml
- zeppelin/package.json
> [DOCS] Bump Sedona version to 1.5.2

- R/R/dependencies.R
Bump the dependency version to `1.5.2` in Sedona R
> [DOCS] Bump dependency in R to 1.5.2

- docs/setup/release-notes.md
Updates the release notes docs
> [DOCS] Update release notes

- docs/setup/release-notes.md
Cleaned up the release notes for unneeded whitespace
> [DOCS] Remove unneeded whitespace from `release-notes.md`

- docs/setup/release-notes.md
- mkdocs.yml
> [DOCS] Add release notes for 1.6.0

- R/DESCRIPTION
- R/R/dependencies.R
- common/pom.xml
- flink-shaded/pom.xml
- flink/pom.xml
- pom.xml
- python/sedona/version.py
- snowflake-tester/pom.xml
- snowflake/pom.xml
- spark-shaded/pom.xml
- spark/common/pom.xml
- spark/pom.xml
- spark/spark-3.0/pom.xml
- spark/spark-3.4/pom.xml
- spark/spark-3.5/pom.xml
- zeppelin/package.json
> [DOCS] Bump Sedona version to 1.6.0

- spark/common/src/main/scala/org/apache/sedona/sql/RasterRegistrator.scala
- spark/common/src/main/scala/org/apache/sedona/sql/utils/GeoToolsCoverageAvailability.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/InferrableRasterTypes.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/InferredExpression.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/InferredRasterExpression.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/implicits.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/GeometryFunctions.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/MapAlgebra.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/PixelFunctionEditors.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/PixelFunctions.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterAccessors.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterBandAccessors.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterBandEditors.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterConstructors.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterEditors.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterOutputs.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryBase.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-478. The PR name follows the format `[SEDONA-XXX] my subject`.
Make basic geometry functions and spatial join functioning without GeoTools.
Passing existing tests and testing manually without GeoTools.
> [SEDONA-478] Make Sedona geometry functions and spatial join working without GeoTools

- docs/download.md
- docs/index.md
- docs/setup/maven-coordinates.md
- mkdocs.yml
NOTE: Waiting for the release approval from Sedona PMC.
1. Add news
2. Update versions
3. Update some statements
> [DOCS] Sedona 1.5.2 post release doc updates

- common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
- common/src/test/java/org/apache/sedona/common/raster/RasterBandEditorsTest.java
- docs/api/sql/Raster-operators.md
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterBandEditors.scala
- spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-554. The PR name follows the format `[SEDONA-XXX] my subject`.
- Implements RS_Union a multi-band, multi-raster version of RS_AddBand.
> [SEDONA-554] Add RS_Union

- snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/ddl/DDLGenerator.java
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-555. The PR name follows the format `[SEDONA-555] my subject`.
Added `IF NOT EXISTS` to create application role statement
> [SEDONA-555] Snowflake Native App should not always create a new role

- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-557. The PR name follows the format `[SEDONA-557] my subject`.
It was unclear to me why the previous SEDONA-557 PR wasn't able to detect this simple compilation bug
> [SEDONA-557] Fix failed Flink tests

- docs/setup/databricks.md
- docs/setup/emr.md
- docs/setup/fabric.md
- docs/setup/release-notes.md
- docs/setup/wherobots.md
This reverts commit d8a896e.
Revert the Java 11 tutorial
> Revert "[DOCS] Update 1.6.0 release notes with Java 11 tutorial (#1403)"

- docs/setup/flink/platform.md
- docs/setup/release-notes.md
- docs/tutorial/geopandas-shapely.md
* Completely remove Java 11 in release notes
* Added Flink 1.19 compilation info
> [DOCS] Add 1.6.0-rc3 release notes

- docs/download.md
- docs/index.md
- mkdocs.yml
> [DOCS] 1.6.0 post release doc update

- common/pom.xml
- flink-shaded/pom.xml
- flink/pom.xml
- pom.xml
- snowflake-tester/pom.xml
- snowflake/pom.xml
- spark-shaded/pom.xml
- spark/common/pom.xml
- spark/pom.xml
- spark/spark-3.0/pom.xml
- spark/spark-3.4/pom.xml
- spark/spark-3.5/pom.xml
- No, this is a project version update.
Bump project version for the next development iteration.
Passing CI.
> [maven-release-plugin] prepare for next development iteration

- .pre-commit-config.yaml
- docs/download.md
- docs/setup/databricks.md
Standardized some docs and updated pre-commit
> [DOCS] pre-commit autoupdate

- common/src/main/java/org/apache/sedona/common/Functions.java
- common/src/test/java/org/apache/sedona/common/FunctionsTest.java
- docs/api/flink/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- python/sedona/sql/st_functions.py
- python/tests/sql/test_dataframe_api.py
- python/tests/sql/test_function.py
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
- spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
- spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-567. The PR name follows the format `[SEDONA-567] my subject`.
Add ST_M
> [SEDONA-567] Add ST_M

- common/src/main/java/org/apache/sedona/common/Constructors.java
- common/src/test/java/org/apache/sedona/common/ConstructorsTest.java
- common/src/test/java/org/apache/sedona/common/FunctionsTest.java
- docs/api/flink/Constructor.md
- docs/api/snowflake/vector-data/Constructor.md
- docs/api/sql/Constructor.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Constructors.java
- flink/src/test/java/org/apache/sedona/flink/ConstructorTest.java
- python/sedona/sql/st_constructors.py
- python/tests/sql/test_constructor_test.py
- python/tests/sql/test_dataframe_api.py
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestConstructors.java
- snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Constructors.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_constructors.scala
- spark/common/src/test/scala/org/apache/sedona/sql/constructorTestScala.scala
- spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
* Added ST_PointZM
* Added ST_PointM
* Added ST_PointFromWKB
> [SEDONA-569][SEDONA-570][SEDONA-572] Add ST_PointZM, ST_PointM, ST_PointFromWKB

- common/src/main/java/org/apache/sedona/common/Functions.java
- common/src/test/java/org/apache/sedona/common/FunctionsTest.java
- docs/api/flink/Function.md
- docs/api/snowflake/vector-data/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- python/sedona/sql/st_functions.py
- python/tests/sql/test_dataframe_api.py
- python/tests/sql/test_function.py
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctions.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsV2.java
- snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
- snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFsV2.java
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
- spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
- spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-578. The PR name follows the format `[SEDONA-578] my subject`.
Add ST_Points
> [SEDONA-578] Add ST_Points

- common/src/main/java/org/apache/sedona/common/Functions.java
- common/src/test/java/org/apache/sedona/common/FunctionsTest.java
- docs/api/flink/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- python/sedona/sql/st_functions.py
- python/tests/sql/test_dataframe_api.py
- python/tests/sql/test_function.py
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
- spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
- spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
> [SEDONA-584] Add ST_Zmflag

- common/src/main/java/org/apache/sedona/common/Constructors.java
- common/src/test/java/org/apache/sedona/common/ConstructorsTest.java
- docs/api/flink/Constructor.md
- docs/api/snowflake/vector-data/Constructor.md
- docs/api/sql/Constructor.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Constructors.java
- flink/src/test/java/org/apache/sedona/flink/ConstructorTest.java
- python/sedona/sql/st_constructors.py
- python/tests/sql/test_constructor_test.py
- python/tests/sql/test_dataframe_api.py
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestConstructors.java
- snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Constructors.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_constructors.scala
- spark/common/src/test/scala/org/apache/sedona/sql/constructorTestScala.scala
- spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
Add ST_GeomCollFromText
Add ST_MPointFromText
> [SEDONA-590] [SEDONA-592] Add ST_GeomCollFromText, ST_MPointFromText

- common/src/main/java/org/apache/sedona/common/Predicates.java
- common/src/test/java/org/apache/sedona/common/PredicatesTest.java
- docs/api/flink/Predicate.md
- docs/api/snowflake/vector-data/Predicate.md
- docs/api/sql/Predicate.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Predicates.java
- flink/src/test/java/org/apache/sedona/flink/PredicateTest.java
- python/sedona/sql/st_predicates.py
- python/tests/sql/test_dataframe_api.py
- python/tests/sql/test_predicate.py
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestPredicates.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestPredicatesV2.java
- snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
- snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFsV2.java
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Predicates.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_predicates.scala
- spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
- spark/common/src/test/scala/org/apache/sedona/sql/predicateTestScala.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-593. The PR name follows the format `[SEDONA-593] my subject`.
Add ST_Relate
Add ST_RelateMatch
> [SEDONA-593] [SEDONA-594] Add ST_Relate, ST_RelateMatch

- common/src/main/java/org/apache/sedona/common/Functions.java
- common/src/test/java/org/apache/sedona/common/FunctionsTest.java
- docs/api/flink/Function.md
- docs/api/snowflake/vector-data/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- python/sedona/sql/st_functions.py
- python/tests/sql/test_dataframe_api.py
- python/tests/sql/test_function.py
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctions.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsV2.java
- snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
- snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFsV2.java
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
- spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
- spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-598. The PR name follows the format `[SEDONA-598] my subject`.
Add ST_UnaryUnion
> [SEDONA-598] Add ST_UnaryUnion

- common/src/main/java/org/apache/sedona/common/Functions.java
- common/src/main/java/org/apache/sedona/common/utils/GeomUtils.java
- common/src/test/java/org/apache/sedona/common/FunctionsTest.java
- docs/api/flink/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- python/sedona/sql/st_functions.py
- python/tests/sql/test_dataframe_api.py
- python/tests/sql/test_function.py
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
- spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
- spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
> [SEDONA-604] Add ST_AddMeasure

- common/src/main/java/org/apache/sedona/common/Functions.java
- common/src/test/java/org/apache/sedona/common/FunctionsTest.java
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-608. The PR name follows the format `[SEDONA-XXX] my subject`.
- add a check to see if the interior ring exists or not to fix #1475.
- passed new tests
> [SEDONA-608] Fix ST_IsPolygonCW, ST_IsPolygonCCW, ST_ForcePolygonCW and ST_ForcePolygonCCW

- common/src/main/java/org/apache/sedona/common/Functions.java
- common/src/test/java/org/apache/sedona/common/FunctionsTest.java
- docs/api/flink/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
- spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
- spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-610. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add ST_IsValidTrajectory
- add new unit tests
> [SEDONA-610] Add ST_IsValidTrajectory

- .github/workflows/first-interaction.yml
https://github.com/actions/first-interaction?tab=readme-ov-file
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-612. The PR name follows the format `[SEDONA-XXX] my subject`.
Adds a new workflow to greet new members of the community.
This was not tested.  We can merge and then in future when someone new opens an issue or PR we can see if this workflow triggers.
Also we can update or change the greeting messages if needed.
> [SEDONA-612] Add the `actions/first-interaction` workflow

- examples/flink-sql/src/test/resources/scalastyle_config.xml
- examples/spark-sql/src/test/resources/scalastyle_config.xml
- tools/maven/scalastyle_config.xml
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-614. The PR name follows the format `[SEDONA-XXX] my subject`.
Cleaned up some XML
> [SEDONA-614] Clean up `scalastyle_config.xml`

- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- spark/common/src/test/java/org/apache/sedona/core/formatMapper/GeoJsonIOTest.java
> [DOCS] Fix spelling in Java files function names tests

- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/SnowClient.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/SnowTestRunner.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestBase.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestConstructors.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctions.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsGeography.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsV2.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestPredicates.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestPredicatesV2.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestTableFunctions.java
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-616. The PR name follows the format `[SEDONA-XXX] my subject`.
- Apply spotless to snowflake module
- passed existing tests
> [SEDONA-616] Apply spotless to snowflake module

- .pre-commit-config.yaml
- mkdocs.yml
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-619. The PR name follows the format `[SEDONA-XXX] my subject`.
Standardized and formatted the YAML
> [SEDONA-619] pre-commit(yaml): format `mkdocs.yml`

- common/src/main/java/org/apache/sedona/common/raster/RasterBandAccessors.java
- common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-620. The PR name follows the format `[SEDONA-XXX] my subject`.
Cleaned up some Java code.
> [SEDONA-620] Simplify Java if statements

- spark/common/src/test/scala/org/apache/sedona/sql/functions/TestGeometrySimplify.scala
> [DOCS] Fix typo in Scala code

- common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java
Removed an unneeded duplicate word.
> [DOCS] Remove duplicate word

- spark/common/src/main/java/org/apache/sedona/core/rangeJudgement/RangeFilterUsingIndex.java
- spark/common/src/main/java/org/apache/sedona/core/spatialOperator/RangeQuery.java
- spark/common/src/main/java/org/apache/sedona/core/spatialRDD/SpatialRDD.java
- spark/common/src/main/java/org/apache/sedona/viz/core/GlobalParameter.java
- spark/common/src/main/java/org/apache/sedona/viz/core/RasterOverlayOperator.java
- spark/common/src/main/java/org/apache/sedona/viz/core/VectorOverlayOperator.java
- spark/common/src/main/java/org/apache/sedona/viz/core/VisualizationOperator.java
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-623. The PR name follows the format `[SEDONA-XXX] my subject`.
Cleans up and standardizes the Java code.
> [SEDONA-623] Simplify Java `if` statements

- common/src/main/java/org/apache/sedona/common/raster/RasterAccessors.java
- common/src/main/java/org/apache/sedona/common/subDivide/PivotFinder.java
- common/src/main/java/org/apache/sedona/common/utils/GeometrySplitter.java
- common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java
- common/src/test/java/org/apache/sedona/common/raster/RasterBandEditorsTest.java
- common/src/test/java/org/apache/sedona/common/raster/RasterEditorsTest.java
- spark/common/src/main/java/org/apache/sedona/core/formatMapper/shapefileParser/boundary/BoundBox.java
- spark/common/src/main/java/org/apache/sedona/core/formatMapper/shapefileParser/parseUtils/shp/ShapeSerde.java
- spark/common/src/main/java/org/apache/sedona/core/formatMapper/shapefileParser/parseUtils/shp/ShpFileParser.java
- spark/common/src/main/java/org/apache/sedona/core/formatMapper/shapefileParser/shapes/CombineShapeReader.java
- spark/common/src/main/java/org/apache/sedona/core/joinJudgement/DedupParams.java
- spark/common/src/main/java/org/apache/sedona/core/spatialPartitioning/quadtree/StandardQuadTree.java
Fixed some grammar and spelling.
> [DOCS] Fix grammar and spelling

- R/R/dependencies.R
Fix context creation to post 1.4.1 flow
Ran r tests
> [SEDONA-644] R – Adapt to SedonaContext flow (post 1.4.1)

- binder/start
- docker/sedona-spark-jupyterlab/start.sh
- docs/api/sql/Raster-loader.md
- docs/setup/databricks.md
- docs/setup/maven-coordinates.md
- docs/setup/release-notes.md
- mkdocs.yml
1. Add 1.6.1 release notes
2. Fix some minor issues in the docs
> [DOCS] Add Sedona 1.6.1 release notes and update docs

- R/DESCRIPTION
- R/R/dependencies.R
- python/sedona/version.py
- zeppelin/package.json
> [DOCS] Bump Sedona Python, R, Zeppelin version to 1.6.1

- docs/setup/release-notes.md
- mkdocs.yml
Update the docs to include the latest PR and 1.6.1-rc2
> [DOCS] Update release notes for 1.6.1-rc2

- common/src/main/java/org/apache/sedona/common/Functions.java
- common/src/main/java/org/apache/sedona/common/utils/GeometryDuplicateCoordinateRemover.java
- common/src/test/java/org/apache/sedona/common/FunctionsTest.java
- docs/api/flink/Function.md
- docs/api/snowflake/vector-data/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- python/sedona/sql/st_functions.py
- python/tests/sql/test_dataframe_api.py
- python/tests/sql/test_function.py
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctions.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsV2.java
- snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
- snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFsV2.java
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
- spark/common/src/test/scala/org/apache/sedona/sql/PreserveSRIDSuite.scala
- spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
- spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-647. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add ST_RemoveRepeatedPoints
- add new unit tests
> [SEDONA-647] Add ST_RemoveRepeatedPoints

- .github/workflows/python-wheel.yml
- spark/common/src/test/scala/org/apache/sedona/viz/sql/optVizOperatorTest.scala
Upgrade the cibuildwheel action to 2.20.2
Passed GitHub
> [CI] Upgrade CIBuildwheel to 2.20.0

- pom.xml
The parent pom mistakenly deploys the parent module multiple times, which will create problems when publish the packages
To be tested when make a release
> [SEDONA-640] Fix the parent pom issue

- docs/setup/databricks.md
- docs/setup/emr.md
- docs/tutorial/benchmark.md
- docs/tutorial/sql.md
1. Improve the databricks setup guide to include `Shared cluster` situation.
2. Other minor fixes
> [DOCS] Improve the Databricks setup guide

- spark/common/src/main/java/org/apache/sedona/viz/core/BigBufferedImage.java
Minor addition to the java docs
> [DOCS] Update Java code comments

- common/src/test/java/org/apache/sedona/common/FunctionsTest.java
- flink/src/test/java/org/apache/sedona/flink/ConstructorTest.java
- spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
> [DOCS] Fix spelling in Java and Scala test files

- .gitattributes
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
Added a basic .gitattributes file
> Add `.gitattributes` for newline code normalization

- spark/common/src/main/java/org/apache/sedona/viz/extension/photoFilter/Emboss.java
Fixed spelling and renamed a file.
> [DOCS] Fix spelling and rename file

- python/sedona/stats/clustering/dbscan.py
- python/tests/stats/test_dbscan.py
- spark/common/src/main/scala/org/apache/sedona/stats/clustering/DBSCAN.scala
Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-662. The PR name follows the format [SEDONA-XXX] my subject.
removing dead code in the DBSCAN implementation
ran stats unit tests
> [SEDONA-662] remove dead code from dbscan code

- .github/linters/.markdown-lint.yml
- docs/api/sql/Optimizer.md
- docs/tutorial/rdd.md
- docs/tutorial/snowflake/sql.md
https://github.com/DavidAnson/markdownlint/blob/main/doc/md038.md
Added another check/test to our Markdown linter.
Ran locally: `pre-commit run --all-files`
> [DOCS] Enable markdownlint rule MD038

- .github/pull_request_template.md
Minor change to the pull request template based on recent PRs and their titles.
Ran locally `pre-commit run --all-files`
> [DOCS] Minor update to the pull request template

- docs/api/flink/Function.md
- docs/api/snowflake/vector-data/Function.md
- docs/api/sql/Function.md
- docs/api/sql/Raster-operators.md
- docs/setup/emr.md
- docs/setup/glue.md
- No:
Fixed some typos :)
I ran pre-commit and checked the spelling.
> [DOCS] Fix spelling; Standardize code block languages

- mkdocs.yml
Minor change for improved readability.  A ordered list always helps.  Less chaos :+1:
Minor clean up.
> [DOCS] 💄 update `mkdocs.yml` to sort the `theme/features` list

- R/vignettes/articles/apache-sedona.Rmd
- No:
Commit dc7e5c91c1641edbcdf8bacd3d12a20f14745aca moved the location of `arealm-small.csv`. This PR adjusts sources to changes.
> [DOCS] Update arealm-small reference

- pyproject.toml
- No:
Commit 48412795bed9e25517ae62890767f036c432174b removed isort
> Update pyproject.toml remove isort

- README.md
- No:
Added some helpful links to the README.
Helps new contributors understand what Sedona is about in general.
> [DOCS] Enhance the README with links for technical terms

- README.md
- No:
- Added 3 links to Spatial computer, Spatial R, and Spatial Python
> [DOCS] Added links to spatial computing, Spatial R and Spatial Python

- docs/tutorial/sql.md
- docs/usecases/ApacheSedonaSQL.ipynb
- No:
- this is a documentation update. 
Small PR - Commit dc7e5c91c1641edbcdf8bacd3d12a20f14745aca moved the `ApacheSedonaSQL_SpatialJoin_AirportsPerCountry.ipynb` notebook. This PR adjusts sources to changes.
> [DOCS] Update `ApacheSedonaSQL_SpatialJoin_AirportsPerCountry.ipynb`

- docs/download.md
- docs/index.md
- docs/setup/release-notes.md
- mkdocs.yml
- No:
1. Add release news
2. Add download links
3. Add maven links
> [DOCS] Add 1.7.0 release news

- requirements.txt
- No
Added a Python requirements file for the pre-commit package.
> [DOCS] Add Python requirements file for pre-commit

- .pre-commit-config.yaml
> [CI] Run `pre-commit autoupdate`

- R/DESCRIPTION
- R/R/data_interface.R
- R/man/sdf_register.spatial_rdd.Rd
- R/man/spark_read_shapefile.Rd
- R/man/spark_write_geojson.Rd
- R/tests/testthat/test-data-interface-raster.R
- R/tests/testthat/test-data-interface.R
- Deprecate custom reader/writers replaced by the normal "source" API
- Update tests for deprecation warnings
Ran R tests
R documentation has been updated
> [SEDONA-685] Deprecate custom readers writers

- .pre-commit-config.yaml
- R/R/data_interface.R
- R/tests/testthat/test-data-interface-raster.R
- R/vignettes/articles/apache-sedona.Rmd
- R/vignettes/articles/raster.Rmd
Add some pre-commit hooks for R, see issue #1370 
* tidyverse style
* lint
* no bowser or print statements in R files
* code is parsable
* Pkgdown documentation has the right entries
Did not include less relevant ones, nor spell check
> [CI] Add pre-commit hooks for R

- .pre-commit-config.yaml
Some clean up to our pre-commit config.
Ran locally `pre-commit run --all-files`
> [CI] Clean up and standardize the pre-commit config

- mkdocs.yml
- No:
Add link to STAC doc the mkdocs yml file
NA
> [DOC] Add link to STAC doc the mkdocs yml file

- .asf.yaml
- No:
* Stop spamming the dev mailing list
* Add @MrPowers and @jbampton to collaborators to triage issues
> [CI] Update asf.yml

- docs/community/contributor.md
- No:
Updated the website committers list.
> [DOCS] Add Pranav Toggi to the Committers list

- spark/common/src/main/scala/org/apache/sedona/sql/UDF/AbstractCatalog.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-710. The PR name follows the format `[SEDONA-XXX] my subject`.
Fix bug where AbstractCatalog reference Catalog in registerAll function
Unit Test dont show regression
> [SEDONA-710] fix bug in AbstractCatalog referencing Catalog.

- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/adapters/StructuredAdapter.scala
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-712. The PR name follows the format `[SEDONA-XXX] my subject`.
added a version of toSpatialRdd that takes in an RDD[InternalRow].
using in a downstream project. Existing test for Dataframe based method that calls this function.
> [SEDONA-712] add toSpatialRdd method for RDD[InternalRow]

- docs/asf/telemetry.md
- mkdocs.yml
- No:
Add Matomo tracking
Update the privacy doc
> [DOCS] Add Matomo to Sedona website

- docs/api/sql/Function.md
- Yes,
- No:
document for ST_MakeValid. The description for the keepCollapsed was in correct.
Run the query on AWS Athena
> [DOCS] Correct the document for ST_MakeValid

- docs/tutorial/files/csv-geometry-sedona-spark.md
- mkdocs.yml
This adds a documentation page on reading and writing CSV files with Apache Sedona.
All code snippets were verified on localhost.
- Yes, I have updated the documentation based on existing Sedona functionality.
> [DOCS] add docs on csv files

- docs/tutorial/files/shapefiles-sedona-spark.md
- docs/tutorial/sql.md
- mkdocs.yml
- this is a documentation update for existing functionality. The PR name follows the format `[DOCS] my subject`
Adds a documentation page for Shapefiles.
Code snippets tested on localhost.
> [DOCS] add shapefiles documentation page

- .github/pull_request_template.md
- docs/community/contact.md
- docs/community/rule.md
- No:
Update the following
* Rules for community
* Help info for the community to encourage GitHub Discussion
> [DOCS] Update the community docs

- python/tests/utils/test_arrow_conversion_geopandas_to_sedona.py
- No:
Add the missing license header
> [DOCS] Add missing license header

- docs/setup/release-notes.md
> [DOCS] Add Sedona 1.7.1 release notes

- NOTICE
- docs/community/publish.md
- snowflake-tester/pom.xml
- No:
1. Improve the release script
2. Fix versions
> [DOCS] Update the release script and docs

- README.md
- docs/download.md
- docs/index.md
> [DOCS] Add 1.7.1 release news

- mkdocs.yml
> [DOCS] Bump Sedona versions in doc

- docs/api/sql/Function.md
- No:
Add a missing parameter in the `ST_DBSCAN` docs.
its just docs.
> [DOCS] add missing useSpheroid argument to ST_DBSCAN docs

- common/src/main/java/org/apache/sedona/common/Functions.java
- common/src/main/java/org/apache/sedona/common/utils/GeometryForce2DTransformer.java
- common/src/test/java/org/apache/sedona/common/FunctionsTest.java
- docs/api/flink/Function.md
- docs/api/snowflake/vector-data/Function.md
- docs/api/sql/Function.md
- flink/src/main/java/org/apache/sedona/flink/Catalog.java
- flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
- flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
- python/sedona/sql/st_functions.py
- python/tests/sql/test_dataframe_api.py
- python/tests/sql/test_function.py
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
- Fix ST_Force_2D implementation.
- Create an alias ST_Force2D to keep it consistent with other ST_ForceXD functions.
- passed existing test and add new unit tests
> [SEDONA-726] Fix ST_Force_2D and add ST_Force2D

- docs/setup/databricks.md
- No:
* Add a warning for DBR 16.2
* Add a workaround for Sedona parser bug in DBR 16
> [DOCS] Update the Databricks doc to reflect issues on DBR 16

- docs/tutorial/files/stac-sedona-spark.md
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacExtension.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacUtils.scala
- spark/common/src/test/resources/datasource_stac/extended-item.json
- spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacDataSourceTest.scala
This PR add the stac grid extension to the reader and promote the properties to top level.
new unit test
> [SEDONA-704] Add the grid extension to the stac reader

- docs/community/contact.md
- No:
Typo fix in Markdown
Ran pre-commit
> [DOCS] Fix case / spelling

- common/src/main/java/org/apache/sedona/common/raster/RasterBandAccessors.java
- No
Fixed some typos in the Java code.
> [DOCS] Fix spelling in Java code

- .github/workflows/docs.yml
Standardize docs install process to use a requirements file.
> [CI] Optimize docs workflow; pip install -r requirements-docs.txt

- .github/workflows/docker-build.yml
- .github/workflows/docs.yml
- .github/workflows/example.yml
- .github/workflows/java.yml
- .github/workflows/lint.yml
- .github/workflows/python.yml
- Yes, and the PR name follows the format `[SEDONA-1900] Fixing ActionLint suggestions on Github Action files`.
#1900 -> Added fixes to workflow files as suggested by actionlint.
No more suggestions by Action Lint
> [GH-1900] Fixing ActionLint suggestions on Github Action files

- README.md
Fixed a typo in Mardown
Spell checked
> [DOCS] README: fix case / spelling of GitHub brand name

- CONTRIBUTING.md
- README.md
- docs/community/contact.md
- mkdocs.yml
- No:
Update the Discord invite link
> [DOCS] Update the Discord invite link

- CONTRIBUTING.md
- README.md
- docs/community/contact.md
- mkdocs.yml
- No:
Fixed the wrong discord link
Manually tested
> [DOCS] Fix the wrong discord link

- docs/usecases/ApacheSedonaRaster.ipynb
> [DOCS] Fix typos

- .pre-commit-config.yaml
https://nodejs.org/en
Updated Node to the latest LTS version and ran `pre-commit autoupdate` to update the hooks
> [CI] pre-commit: autoupdate and update Node LTS version

- docs/api/flink/Function.md
- docs/api/snowflake/vector-data/Function.md
- docs/api/sql/Function.md
- docs/tutorial/sql.md
Fixed some broken links in the docs.
refs #1888 
Checked the links
> [DOCS] Fix links in Markdown files

- spark/common/src/main/java/org/apache/sedona/sql/datasources/osmpbf/extractors/RelationExtractor.java
- spark/common/src/test/scala/org/apache/sedona/sql/OsmReaderTest.scala
- Yes
- Yes, and the PR name follows the format `[SEDONA-734] my subject`.
Fix relation ids parsing
unit test
> [SEDONA-734] Fix relation parsing in OSM reader

- docs/setup/release-notes.md
- No:
Added 1.7.2 release notes
> [DOCS] Add 1.7.2 release notes

- docker/docs/Dockerfile
- docker/zeppelin/update-zeppelin-interpreter.sh
- No:
Add the missing file headers
> [DOCS] Add missing Apache file headers

- R/README.md
> [DOCS] update R README.md fix typo

- python/tests/sql/test_function.py
- No:
This small PR fixes the sql function tests by handling the duplicated use-cases.
> [CI] Fix issues with the sql function tests

- docs-overrides/main.html
- docs/community/contact.md
- No:
- use the correct URL to fetch the discord badge
- locally
> [DOCS] Fix discord badge image

- .asf.yaml
- No:
Add 2 more names to the collaborator list as they will contribute the project soon
> [CI] Add 2 more names to the collaborator list

- .pre-commit-config.yaml
it closes issue: https://github.com/apache/sedona/issues/1997
Standardize the pre-commit config
> [CI] fix: Standardize the pre-commit config

- python/sedona/geopandas/geoseries.py
This PR adds advice when people calls the to_geopandas directly that it loads distributed df into driver that might cause OOM. Also we should only call interval version in the implementation that does not have this advice warning.
unit tests
- Yes, I have updated the documentation in the method comments.
> [GH-2004] Log advice for to_geopandas function and only use internal calls for constructor

- docker/install-sedona.sh
- flink/pom.xml
- spark/pom.xml
- No
A general whitespace clean up
> chore: remove tabs and indent code

- python/sedona/geopandas/geoseries.py
- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2062
Fix the bug that arose after a combination of 3 recent geopandas PRs merged.
Fixed existing tests that were failing.
> [GH-2062] Fix failing Geopandas tests after recent PR merges

- python/tests/sql/test_structured_adapter.py
- spark/common/src/main/scala/org/apache/sedona/python/wrapper/utils/implicits.scala
This PR fixed the issue of StructuredAdapter that does not work with RangeQuery on geometries.
TestStructuredAdapter
> [GH-2072] Fix Structured Adapter Issue with Spatial Queries

- python/sedona/geopandas/geoseries.py
- python/tests/geopandas/test_geoseries.py
- python/tests/geopandas/test_match_geopandas_series.py
- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2055
Implemented estimate_utm_crs. Implemented bounds and total_bounds in the process of doing so.
Added tests
> [GH-2055] Geopandas.GeoSeries: Implement estimate_utm_crs, bounds, total_bounds

- .github/workflows/python.yml
- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2075
Removed duplicate entry
https://github.com/apache/sedona/blob/3f407e96f4edf05bacc2a135811c063524cc50e4/.github/workflows/python.yml#L92-L99
N/A
> [CI] Remove duplicate versions matrix entry in python.yml

- .asf.yaml
> [CI] Add one more GitHub collaborator

- python/sedona/geopandas/tools/sjoin.py
- python/tests/geopandas/test_sjoin.py
This PR enhances geopandas sjoin implementation and adds new tests.
test_sjoin.py
> [GH-2100] Enhance geopandas sjoin implementation

- python/sedona/geopandas/geoseries.py
- python/tests/geopandas/test_geoseries.py
- python/tests/geopandas/test_match_geopandas_series.py
- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2112
Implemented to_wkt and to_wkb
Added tests
> [GH-2112] Geopandas.GeoSeries: Implement `to_wkt` and `to_wkb`

- python/sedona/geopandas/geoseries.py
- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2154
Small fix for safety
Ensured existing tests pass
> [GH-2154] fix: Order by index col in _query_geometry_column

- .github/workflows/codeql.yml
https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql
- No:
> [CI] Create basic CodeQL Analysis file

- .github/workflows/codeql.yml
- No:
Fixes the branch name for CodeQL
I tried two dummy test prs before I realized I had the wrong branch name
> [CI] Update codeql.yml change branch from `main` to `master`

- python/sedona/geopandas/__init__.py
- python/sedona/geopandas/geodataframe.py
- python/sedona/geopandas/geoseries.py
- python/sedona/geopandas/io.py
- python/tests/geopandas/test_geodataframe.py
- python/tests/geopandas/test_geopandas_base.py
- python/tests/geopandas/test_io.py
- python/tests/geopandas/test_match_geopandas_series.py
- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2149
- Implement `to_file`, `from_file`, `read_file`
- Fix GeoDataFrame.getitem to handle non-int indexes properly
Added tests
> [GH-2149] Geopandas: Implement `to_file`, `from_file`, `read_file`

- python/sedona/spark/stac/collection_client.py
- No:
- this is a security update. 
- Replaced direct string concatenation with validated format strings
- Used proper SQL escaping (single quote doubling: ' → '')
- Implemented numeric-only formatting for bbox coordinates
- Used Spark SQL col() and lit() functions for datetime filtering
- Applied proper column operations instead of string-based SQL
- Added graceful handling of invalid inputs (skip rather than fail)
- Prevented information disclosure through error messages
stac client tests
> [GH-2174] Security issues in the STAC client api

- README.md
https://www.star-history.com/
https://contrib.rocks
Added some more 💄 to the README which showcases some great statistics.
Both tools are popular and a lot of projects use them.
Makes our project and team look better.
Visual testing and ran pre-commit
> [DOCS] README: Add `Star History Chart` and `Contributors Avatars`

- python/tests/geopandas/test_geoseries.py
- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2161
Added tests
Added tests
> [GH-2161] Add constructor tests and re-enable more linear ring tests

- .github/workflows/docs.yml
- No:
This PR enhances the documentation build process by adding automated Python API documentation
generation using Sphinx, following the same pattern as existing R documentation generation.
CI Build
> [CI] Add Python API Documentation to CI/CD Pipeline

- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctions.java
- snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsV2.java
- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2204
Fixed tests
Fixed tests
> [GH-2204] Fix snowflake tests for ST_Segmentize

- python/sedona/geopandas/base.py
- python/sedona/geopandas/geodataframe.py
- python/sedona/geopandas/geoseries.py
- python/sedona/geopandas/sindex.py
- python/tests/geopandas/test_geoseries.py
- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2215
Retain sindex, make sindex.query return geometries, implement has_sindex
Added tests
> [GH-2215] Retain sindex, make sindex.query return geometries, implement has_sindex

- common/src/main/java/org/apache/sedona/common/S2Geography/PointGeography.java
- common/src/main/java/org/apache/sedona/common/S2Geography/PolylineGeography.java
- common/src/main/java/org/apache/sedona/common/S2Geography/S2Geography.java
- common/src/main/java/org/apache/sedona/common/S2Geography/SinglePointGeography.java
- common/src/main/java/org/apache/sedona/common/S2Geography/SinglePolylineGeography.java
- common/src/test/java/org/apache/sedona/common/S2Geography/WKBReaderTest.java
Add new Geography kind: SINGLEPOINT, SINGLEPOLYLINE
Solve the issue of read Geography from WKB/WKT as POINT/LINESTRING and decode into same WKT text
> [GH-2222] add Singlepoint, Singlepolyline for correctlty round trip WKT write

- common/src/main/java/org/apache/sedona/common/sphere/Haversine.java
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/optimization/SpatialFilterPushDownForGeoParquet.scala
- spark/spark-3.4/src/test/scala/org/apache/sedona/sql/GeoParquetSpatialFilterPushDownSuite.scala
- spark/spark-3.5/src/test/scala/org/apache/sedona/sql/GeoParquetSpatialFilterPushDownSuite.scala
- spark/spark-4.0/src/test/scala/org/apache/sedona/sql/GeoParquetSpatialFilterPushDownSuite.scala
- This PR pushes down the ST_DistanceSphere filter
- Introduces sphere distance type in `distanceFilter` utility method
-  Passes new and existing tests
> [SEDONA-742] Push down ST_DistanceSphere filter

- python/sedona/spark/geopandas/base.py
- python/sedona/spark/geopandas/geoseries.py
- python/tests/geopandas/test_geoseries.py
- python/tests/geopandas/test_match_geopandas_series.py
- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2242
title
Pass existing tests
> [GH-2242] Geopandas: Remove orderBy in query_geometry_column

- common/src/test/java/org/apache/sedona/common/Geography/ConstructorsTest.java
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_constructors.scala
- spark/common/src/test/scala/org/apache/sedona/sql/geography/ConstructorsDataFrameAPITest.scala
- spark/common/src/test/scala/org/apache/sedona/sql/geography/ConstructorsTest.scala
Constructor test for ST_GeogFromWKB
Datframe API test for ST_GeogFromWKB
> [GH-2255]add test for ST_GeogFromWKB(byte array)

- common/src/test/java/org/apache/sedona/common/Geography/ConstructorsTest.java
- docs/api/sql/geography/Constructor.md
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/geography/Constructors.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_constructors.scala
- spark/common/src/test/scala/org/apache/sedona/sql/geography/ConstructorsDataFrameAPITest.scala
- spark/common/src/test/scala/org/apache/sedona/sql/geography/ConstructorsTest.scala
add new constructor ST_GeogFromEKWB
> [GH-2261]add new constructor ST_GeogFromEKWB

- common/src/main/java/org/apache/sedona/common/geography/Constructors.java
- common/src/test/java/org/apache/sedona/common/Geography/ConstructorsTest.java
- docs/api/sql/geography/Constructor.md
- spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/geography/Constructors.scala
- spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_constructors.scala
- spark/common/src/test/scala/org/apache/sedona/sql/geography/ConstructorsDataFrameAPITest.scala
- spark/common/src/test/scala/org/apache/sedona/sql/geography/ConstructorsTest.scala
function of convert Geography to Geometry
> [GH-2276] new constructor of convert Geography to Geometry

- common/src/main/java/org/apache/sedona/common/S2Geography/GeographyCollection.java
- common/src/main/java/org/apache/sedona/common/S2Geography/PolylineGeography.java
update to a more robust method to check count value from instream input
> [GH-2036] update more robust instream count for Geography decode

- spark/common/src/main/java/org/apache/sedona/sql/datasources/osmpbf/extractors/DenseNodeExtractor.java
- spark/common/src/test/scala/org/apache/sedona/sql/OsmReaderTest.scala
- Yes, and the PR name follows the format `[GH-2312] my subject`. Closes #2312 
The previous PR had an oversight on another precision lost issue. It was captured by a test case but I missed it. This PR is to fix it.
Passed all unit tests
> [GH-2312] Fix the precision lost issue in OSM PBF again

- python/sedona/doc/Makefile
- scripts/pre-commit/check_makefiles_for_tabs.sh
- shade-proto/pom.xml
> [DOCS] Add missing license headers

- R/DESCRIPTION
- R/R/dependencies.R
- python/sedona/version.py
- zeppelin/package.json
> [DOCS] Bump Sedona Python, R, Zeppelin versions

- docs/community/publish.md
> [DOCS] Update Sedona release script

- docs/blog/posts/intro-sedonadb.md
- No:
- this is a documentation update.
This moves the CTA to the end of the blog post.
Ran `mkdocs serve` locally.
- No, this PR does not affect any public API and just updates the CTA in a blog post.
> docs: move cta

- .asf.yaml
- No:
1. Add `hactoberfest` to the repo labels to attract contribution: https://hacktoberfest.com/participation/
2. Use PR title in the merge button commit message
> [DOCS] add hactoberfest to the repo labels and fix the merge button
