src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java

This one line PR fixes a crash when doing spatial partitioning in Spark versions < 1.6.
The fix is to use JavaRDD.rdd().partitions().length rather than JavaRDD.getNumPartitions() for Spark <1.6 compatibility.  This safely gets the number of partitions for this RDD for all versions of Spark 1.X.  (1.0.0 through 1.6.X).  
Note JavaRDDLike has a partitions() method but it is not available in Spark 1.0.0 so I used this approach.
Request: when releasing a new version for 1.X could you please tag the branch with a tag?  It seems only the mainline releases get tags on master.  Thanks...

Fix for Spark < 1.6

---

core/pom.xml
core/src/main/java/org/datasyslab/geospark/formatMapper/LineStringFormatMapper.java
core/src/main/java/org/datasyslab/geospark/formatMapper/PointFormatMapper.java
core/src/main/java/org/datasyslab/geospark/formatMapper/PolygonFormatMapper.java
core/src/main/java/org/datasyslab/geospark/formatMapper/RectangleFormatMapper.java
core/src/main/java/org/datasyslab/geospark/knnJudgement/KnnJudgement.java
core/src/main/java/org/datasyslab/geospark/knnJudgement/KnnJudgementUsingIndex.java
core/src/main/java/org/datasyslab/geospark/rangeJudgement/RangeFilter.java
core/src/main/java/org/datasyslab/geospark/rangeJudgement/RangeFilterUsingIndex.java
core/src/main/java/org/datasyslab/geospark/spatialPartitioning/PartitionJudgement.java
core/src/main/java/org/datasyslab/geospark/spatialRDD/CircleRDD.java
core/src/main/java/org/datasyslab/geospark/spatialRDD/LineStringRDD.java
core/src/main/java/org/datasyslab/geospark/spatialRDD/PointRDD.java
core/src/main/java/org/datasyslab/geospark/spatialRDD/PolygonRDD.java
core/src/main/java/org/datasyslab/geospark/spatialRDD/RectangleRDD.java
core/src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java
core/src/main/java/org/datasyslab/geospark/utils/XMaxComparator.java
core/src/main/java/org/datasyslab/geospark/utils/XMinComparator.java
core/src/main/java/org/datasyslab/geospark/utils/YMaxComparator.java
core/src/main/java/org/datasyslab/geospark/utils/YMinComparator.java
core/src/test/java/org/datasyslab/geospark/spatialRDD/LineStringRDDTest.java
core/src/test/java/org/datasyslab/geospark/spatialRDD/PolygonRDDTest.java

Allow creating SpatialRDD with a mix of geometry types by making SpatialRDD a generic class parameterized over geometry type. Restricting objects stored in Spatial RDD to instances of Geometry enhances type safety and reduces the need for dynamic cast.
Updated core/pom.xml to add dependencies to allow 'mvn clean install' to succeed.

Make SpatialRDD a generic class parameterized over geometry type

---

core/src/main/java/org/datasyslab/geospark/geometryObjects/PairGeometry.java
core/src/main/java/org/datasyslab/geospark/joinJudgement/GeometryByCircleJudgement.java
core/src/main/java/org/datasyslab/geospark/joinJudgement/GeometryByCircleJudgementUsingIndex.java
core/src/main/java/org/datasyslab/geospark/joinJudgement/GeometryByPolygonJudgement.java
core/src/main/java/org/datasyslab/geospark/joinJudgement/GeometryByPolygonJudgementUsingIndex.java
core/src/main/java/org/datasyslab/geospark/spatialOperator/JoinQuery.java
core/src/main/java/org/datasyslab/geospark/spatialPartitioning/DuplicatesHandler.java

Generalize join APIs to allow joins between generic SpatialRDD<T> and SpatialRDD<Polygon>.

Allow joining SpatialRDD<T> with SpatialRDD<Polygon>

---

core/src/main/java/org/datasyslab/geospark/spatialPartitioning/quadtree/QuadRectangle.java
core/src/test/java/org/datasyslab/geospark/spatialPartitioning/quadtree/QuadRectangleTest.java

QuadRectange.contains used to return false for all rectangles of zero width or height including all rectangles which represent envelopes of points. As a result quad-tree partitioning of RDD of points never created more than 5 partitions making join operations very slow for large datasets. This PR fixes QuadRectange.contains to properly handle zero width or height rectangles.

Fix QuadRectange.contains to process envelopes of points correctly

---

.gitignore
core/src/main/java/org/datasyslab/geospark/joinJudgement/DynamicIndexLookupJudgement.java
core/src/main/java/org/datasyslab/geospark/joinJudgement/IndexLookupJudgement.java
core/src/main/java/org/datasyslab/geospark/joinJudgement/JudgementBase.java
core/src/main/java/org/datasyslab/geospark/joinJudgement/NestedLoopJudgement.java
core/src/main/java/org/datasyslab/geospark/spatialOperator/JoinQuery.java

Updated the signature of the JoinQuery.spatialJoin API to allow mix-and-match of geometry types on both sides of the join. In practice, this allows to perform joins against a mix of polygons and multi-polygons.

Allow mix-and-match of geometry types on both sides of a join

---

core/src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java
core/src/main/java/org/datasyslab/geospark/utils/RDDSampleUtils.java
core/src/test/java/org/datasyslab/geospark/utils/RDDSampleUtilsTest.java

SpatialRDD.spatialPartitioning(GridType gridType) method uses RDD.takeSample API to sample the data and build partitioning grid. RDD.takeSample API tends to scan RDD multiple times to get the exact number of requested samples. For large datasets, the extra latency is significant. Since it is not critical to get the exact number of samples, this PR starts to use RDD.sample API.
See https://github.com/apache/spark/blob/412b0e8969215411b97efd3d0984dc6cac5d31e0/core/src/main/scala/org/apache/spark/rdd/RDD.scala#L508
Also, fixed confusing behavior of RDDSampleUtils where it would allow to partition an RDD of 999 records into up to 499 partitions, but not allow the same for RDD of 1000 records. 
Updated RDDSampleUtilsTest.testTooManyPartitions to actually test 3 different scenarios instead of …

Do not scan RDD multiple times to get a sample of the data for partitioning

---

core/src/main/java/org/datasyslab/geospark/spatialPartitioning/PartitionJudgement.java
core/src/main/java/org/datasyslab/geospark/spatialPartitioning/QuadtreePartitioning.java
core/src/main/java/org/datasyslab/geospark/spatialPartitioning/quadtree/QuadRectangle.java
core/src/main/java/org/datasyslab/geospark/spatialPartitioning/quadtree/StandardQuadTree.java
core/src/test/java/org/datasyslab/geospark/spatialPartitioning/quadtree/QuadTreeTest.java
core/src/test/java/org/datasyslab/geospark/spatialPartitioning/quadtree/RenderQuadTree.java

To simplify usage of the StandardQuadTree, combined getAllLeafNodeUniqueId, getSeriaIdMapping, and decidePartitionSerialId into single assignPartitionIds method. Consolidated tree traversal logic within the StandardQuadTree using visitor pattern. Changed global max-items-per-node and max-levels configuration to per-instance.

Simplified partition ID assignment in StandardQuadTree

---

core/src/main/java/org/datasyslab/geospark/spatialPartitioning/HilbertPartitioning.java
core/src/main/java/org/datasyslab/geospark/spatialPartitioning/QuadtreePartitioning.java
core/src/main/java/org/datasyslab/geospark/spatialPartitioning/RtreePartitioning.java
core/src/main/java/org/datasyslab/geospark/spatialPartitioning/VoronoiPartitioning.java
core/src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java

Spatial partitioning involves sampling and building partitioning scheme from the samples. Building of partitioning scheme happens in the driver and therefore requires samples to be transferred from the cluster to the driver machine. Each sample contains a geometry object and user data. Both, geometry object and user data can be large. In particular, complex polygons may contain lots of vertexes and holes and therefore be expensive to transfer other the network. Since partitioning building schemes use only bounding boxes of the samples, we can avoid transferring large geometries and user data to the driver by transforming samples into bounding boxes before collecting them to the driver. The PR updates SpatialRDD to do that and updates *Partitioning class to remove no longer needed logic of …

Collect envelopes instead of full geometry objects when sampling

---

core/src/main/java/org/datasyslab/geospark/geometryObjects/Circle.java
core/src/test/java/org/datasyslab/geospark/geometryObjects/CircleTest.java
core/src/test/java/org/datasyslab/geospark/utils/CRSTransformationTest.java

The original implementation of Circle.covers(geometry) used to return true iff all 4 corners of the bounding box of the input geometry were covered by the circle. However, a line or a polygon may be covered by the circle while their bounding box is not. 
Similarly, the implementation of Circle.intersects(geometry) used to return true iff at least one corner of the bounding box of the input geometry was covered by the circle. However, a line cutting through the circle or a polygon covering the circle do intersect the circle, but this logic would report false.
This PR attempts to implement covers and intersects checks correctly.

Fix Circle.covers and Circle.intersects

---

core/src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java
core/src/test/java/org/datasyslab/geospark/spatialRDD/BoundaryAndCountAggregationTest.java

Further reduce RDD scans in SpatialRDD.analyze by combining count and boundary computation into a single aggregation.

Count records and compute extent of the RDD in a single scan

---

core/src/main/java/org/datasyslab/geospark/spatialPartitioning/QuadtreePartitioning.java
core/src/test/java/org/datasyslab/geospark/spatialPartitioning/quadtree/QuadTreePartitioningTest.java

StandardQuadTree.insert could get into an infinite split cycle if there was a lot of data in the corner of the overall extent. This PR puts a cap on the depth of the tree equal to the number of desired partitions to avoid the problem.
java.lang.StackOverflowError
at org.datasyslab.geospark.spatialPartitioning.quadtree.StandardQuadTree.findRegion(StandardQuadTree.java:62)
at org.datasyslab.geospark.spatialPartitioning.quadtree.StandardQuadTree.insert(StandardQuadTree.java:153)
at org.datasyslab.geospark.spatialPartitioning.quadtree.StandardQuadTree.insert(StandardQuadTree.java:159)
at org.datasyslab.geospark.spatialPartitioning.quadtree.StandardQuadTree.insert(StandardQuadTree.java:169)
at org.datasyslab.geospark.spatialPartitioning.quadtree.StandardQuadTree.insert(StandardQuadTree.java:159 …

Fix java.lang.StackOverflowError in StandardQuadTree.insert

---

core/src/main/java/org/datasyslab/geospark/formatMapper/shapefileParser/parseUtils/shp/ShpFileParser.java
core/src/main/java/org/datasyslab/geospark/formatMapper/shapefileParser/shapes/CombineShapeReader.java
core/src/main/java/org/datasyslab/geospark/formatMapper/shapefileParser/shapes/ShapeFileReader.java
core/src/test/java/org/datasyslab/geospark/formatMapper/shapefileParser/shapes/ShapefileReaderTest.java

In this PR I complete the logic of reading .shx file and extracting bytes from .shp file with indexes. This update can fix missing shapes when reading .shp files with incorrect file length in .shp file.

Add support for .shx file for extracting .shp file

---

core/src/main/java/org/datasyslab/geospark/enums/GridType.java
core/src/main/java/org/datasyslab/geospark/spatialPartitioning/KDBTree.java
core/src/main/java/org/datasyslab/geospark/spatialPartitioning/KDBTreePartitioner.java
core/src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java
core/src/test/java/org/datasyslab/geospark/spatialOperator/JoinQueryCorrectnessChecker.java
core/src/test/java/org/datasyslab/geospark/spatialOperator/JoinTestBase.java
core/src/test/java/org/datasyslab/geospark/spatialOperator/LineStringJoinTest.java
core/src/test/java/org/datasyslab/geospark/spatialOperator/PointJoinTest.java
core/src/test/java/org/datasyslab/geospark/spatialOperator/PolygonJoinTest.java
core/src/test/java/org/datasyslab/geospark/spatialOperator/RectangleJoinTest.java

Spatial partitioning based on KDB-tree yields much more even partitions when partitioning based on Quad-tree. At the same time, just like Quad-tree, KDB-tree generates non-overlapping partitions and supports efficient inline de-duplication.

Introduce 2-D-B-tree partitioning scheme

---

core/pom.xml
core/src/main/java/org/datasyslab/geospark/joinJudgement/DynamicIndexLookupJudgement.java
core/src/main/java/org/datasyslab/geospark/spatialOperator/JoinQuery.java
core/src/main/scala/org/datasyslab/geospark/monitoring/GeoSparkListener.scala
core/src/main/scala/org/datasyslab/geospark/monitoring/GeoSparkMetric.scala
core/src/main/scala/org/datasyslab/geospark/monitoring/GeoSparkMetrics.scala
core/src/test/scala/org/datasyslab/geospark/monitoring/GeoSparkMetricSuite.scala
core/src/test/scala/org/datasyslab/geospark/scalaTest.scala

Partitioning the data into roughly same-size buckets is critical for spatial join performance. Spatial join is a lot less performant when there is a skew. This PR introduces a set of metrics to help investigate skew.
Introduced GeoSparkMetric accumulator to collect per-task metrics and updated DynamicIndexLookupJudgement to collect the following statistics for individual partitions:
- number of objects on the build side of the join;
- number of objects on the streaming side of the join;
- number of candidate object pairs (bounding boxes intersect);
- number of join results
Added GeoSparkListener to print out new statistics at the end of the join.

 Start collecting metrics about spatial join execution

---

core/src/main/java/org/datasyslab/geospark/enums/FileDataSplitter.java
core/src/main/java/org/datasyslab/geospark/enums/GeometryType.java
core/src/main/java/org/datasyslab/geospark/formatMapper/FormatMapper.java
core/src/main/java/org/datasyslab/geospark/formatMapper/LineStringFormatMapper.java
core/src/main/java/org/datasyslab/geospark/formatMapper/PointFormatMapper.java
core/src/main/java/org/datasyslab/geospark/formatMapper/PolygonFormatMapper.java
core/src/main/java/org/datasyslab/geospark/formatMapper/RectangleFormatMapper.java
core/src/main/java/org/datasyslab/geospark/formatMapper/shapefileParser/parseUtils/shp/ShapeSerde.java
core/src/main/java/org/datasyslab/geospark/serde/GeoSparkKryoRegistrator.java

This PR includes the following changes:
1. Add more delimiter support to FileDataSplitter
2. Open all functions in format mappers so that GeoSpark sql can connect with GeoSpark core
3. Add one more deserialization function in ShapeSerde in case GeoSpark sql will use it in the future. Currently GeoSparkSql uses GeometrySerde to do UDT serialization and deserialization

Add GeoSpark core hooks for DataFrame

---

core/src/main/java/org/datasyslab/geospark/rangeJudgement/JudgementBase.java
core/src/main/java/org/datasyslab/geospark/rangeJudgement/RangeFilter.java
core/src/main/java/org/datasyslab/geospark/rangeJudgement/RangeFilterUsingIndex.java
core/src/main/java/org/datasyslab/geospark/spatialOperator/RangeQuery.java

This PR includes the following change: Relax the left and right order of inputRDD and queryGeometry in a SpatialRangeQuery.
The old SpatialRangeQuery API is (spatialRDD, queryWindow,...) which returns objects are covered/intersected by queryWindow.
This PR brings out one more SpatialRangeQuery API which is (queryWIndow, spatialRDD) which returns objects cover/intersect the queryWindow.

Relax the left and right order of SpatialRangeQuery input parameters

---

core/src/main/java/org/datasyslab/geospark/spatialOperator/JoinQuery.java

This PR includes the following change: Expose JoinParams in SpatialJoinQuery official API
Since the new JoinQuery needs many different parameters to control buildSide/indexType/allowDuplicates/considerBoundaryIntersection, this PR allows the user to see JoinParams in official SpatialJoinQuery API.

Expose JoinParams in SpatialJoinQuery official API

---

README.md
core/pom.xml
core/src/main/java/org/datasyslab/geospark/spatialOperator/JoinQuery.java
core/src/test/scala/org/datasyslab/geospark/scalaTest.scala
sql/pom.xml
sql/src/main/scala/org/apache/spark/sql/geosparksql/GeometryWrapper.scala
sql/src/main/scala/org/datasyslab/geosparksql/utils/Adapter.scala
sql/src/test/java/org/datasyslab/geosparksql/readTestJava.java
sql/src/test/scala/org/datasyslab/geosparksql/readTestScala.scala

This PR is an urgent patch to GeoSpark 0.9.0 and upgrades GeoSpark to 0.9.1. It includes the following content:
* [GeoSpark-core]: solve the return object type problem of DistanceJoinQuery so that GeoSpark SQL can access it. 
* [GeoSpark-SQL]: add an adapter which converts join query result to a DataFrame

Urgent patch: Add an adapter function to convert Join result to DataFrame

---

sql/src/main/scala/org/apache/spark/sql/geosparksql/strategy/join/TraitJoinQueryExec.scala
sql/src/test/scala/org/datasyslab/geosparksql/predicateJoinTestScala.scala

Set unnecessary log from info level to debug level. Add one test for RangeQuery PredicatePushDown

Small fixes for GeoSparkSQL 1.0

---

core/pom.xml
core/src/main/java/org/datasyslab/geospark/geometryObjects/GeometrySerde.java
core/src/main/java/org/datasyslab/geospark/geometryObjects/SpatialIndexSerde.java
core/src/main/java/org/datasyslab/geospark/serde/GeoSparkKryoRegistrator.java
core/src/test/java/org/datasyslab/geospark/geometryObjects/SpatialIndexSerdeTest.java

@jiayuasu 
Default kryo serializer can't support its's spatial index since there are some classes without non-arg so I add a SpatialIndexSerde to handle spatial index.
The output size and serialization time is much better than java default serializer and a little bit better than default kryo(I tested  this by adding constructors to its). You can check the work bench of comparing time and size in SpatialIndexSerdeTest.java.
Also, to access to some fields within SpatialIndex objects, I moved JTSPlus dependency to 0.1.4.

add kryo serializer for SpatialIndex type

---

README.md

Link "A Demonstration of GeoSpark: A Cluster Computing Framework for Processing Big Spatial Data" has invalid URL.
Updated link to http://www.public.asu.edu/~jiayu2/geospark/publication/GeoSpark_DemoPaper.pdf

Added link to demo paper in README.MD

---

sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Functions.scala
sql/src/main/scala/org/datasyslab/geosparksql/UDF/UdfRegistrator.scala
sql/src/main/scala/org/datasyslab/geosparksql/utils/GeoSparkSQLRegistrator.scala
sql/src/test/scala/org/datasyslab/geosparksql/functionTestScala.scala

This PR will fix the following issue:
1. fix ST_ConvexHull bug: Issue https://github.com/DataSystemsLab/GeoSpark/issues/188
2. add a new function called ST_Intersection which returns the geometrical intersection of two geometries: Issue  https://github.com/DataSystemsLab/GeoSpark/issues/110
3. allow the user to add one more parameter in ST_Transform to turn off the exception in ST_Transform to bypass "Bursa wolf" error: https://github.com/DataSystemsLab/GeoSpark/issues/185
**ST_Transform (A:geometry, SourceCRS:string, TargetCRS:string, [Optional]UseLongitudeLatitudeOrder:Boolean, [Optional]IgnoreException:Boolean)**

Fixed the ST_ConvexHull bug, added ST_Intersection function and turned off the exception in ST_Transform

---

core/src/main/java/org/datasyslab/geospark/formatMapper/shapefileParser/parseUtils/dbf/DbfParseUtil.java

This PR contains the bugfix to solve the unreadable character in shapefile reader. See Issue https://github.com/DataSystemsLab/GeoSpark/issues/190
If you are working with Arabic, Chinese or Korean character sets in ESRI shapefile, you need to force GeoSpark shapefile reader to use UTF-8 charset.
Add the following line before GeoSpark ShapefileReader:
```
System.setProperty("geospark.global.charset","utf8")
```

Support UTF-8 charset in ShapefileReader

---

core/pom.xml
sql/pom.xml
sql/src/main/scala/org/datasyslab/geosparksql/UDF/UdfRegistrator.scala
viz/pom.xml

This PR makes GeoSparkSQL to support Apache Spark 2.3.0.
The internal UDF APIs in SparkSQL change over versions. Since GeoSparkSQL is put in SparkSQL kernel, we need to change the internal API usage.
This fixed Issue https://github.com/DataSystemsLab/GeoSpark/issues/194

Add the support of Apache Spark 2.3.0

---

sql/src/main/scala/org/apache/spark/sql/geosparksql/strategy/join/TraitJoinQueryExec.scala
sql/src/test/scala/org/datasyslab/geosparksql/predicateJoinTestScala.scala

This PR fixed Issue https://github.com/DataSystemsLab/GeoSpark/issues/193.
Bug description: The original code cannot well handle too small test data for spatial join query. When the user provides some super small test data, (2 or 3 rows per DataFrame), the partition number logic will jump in a wrong fallback setting and eventually pick "-1" as the partition number.
Solution: use a smarter Partition Number Optimizer to select a proper partition number for both input tables of a spatial join query.

Fix the SQL join query partition error when deal with too small testdata

---

sql/src/main/scala/org/datasyslab/geosparksql/UDF/Catalog.scala
sql/src/main/scala/org/datasyslab/geosparksql/UDF/UdfRegistrator.scala

No
Separate the expression catalog and the udf registrator. Udf registrator used to loop over each single expression in UDF package and use a sentence to register this ST expression.
This led to two problems:
(1) If a patch introduces a new ST function, it is impossible to backport this patch to other SparkSQL branches without resulting in a code conflict.
(2) A huge chunk of redundant code
By having this PR, adding a new ST function can be done through three steps:
1. Add the ST function in org.apache.spark.sql.geosparksql.expressions
2. Add the name of this function in org.datasyslab.geosparksql.UDF.Catalog
3. After accepting the proposed ST function, a GeoSpark committer should use `Git Cherry-Pick` to backport the corresponding commit to all GeoSpark branches such as …

Separate the expression catalog and the udf registrator

---

core/src/main/java/org/datasyslab/geospark/spatialRDD/LineStringRDD.java
core/src/main/java/org/datasyslab/geospark/spatialRDD/PointRDD.java
core/src/main/java/org/datasyslab/geospark/spatialRDD/PolygonRDD.java
core/src/main/java/org/datasyslab/geospark/spatialRDD/RectangleRDD.java
core/src/test/java/org/datasyslab/geospark/spatialRDD/LineStringRDDTest.java
core/src/test/java/org/datasyslab/geospark/spatialRDD/PointRDDTest.java
core/src/test/java/org/datasyslab/geospark/spatialRDD/PolygonRDDTest.java
core/src/test/java/org/datasyslab/geospark/spatialRDD/RectangleRDDTest.java
core/src/test/scala/org/datasyslab/geospark/scalaTest.scala

No
Add the empty constructors for 4 typed SpatialRDDs. So, the users can create an empty SpatialRDD and manually assemble it.
This is especially useful when the users want to load a persisted RDD from disk and assemble a typed SpatialRDD by themselves.
Passed the regression test. Added four corresponding unit tests: build an empty spatialRDD and manually assemble it.
This change will add new APIs. JavaDoc has been added.

Add the empty constructors for 4 typed SpatialRDDs

---

docs/api/sql/GeoSparkSQL-Constructor.md

Proposed by me in the gitter.im channel. It was not clear to me what format the text constructors were expecting. Hopefully this will clarify it for future users.
Add some example text input strings to the documentation of ST_FromText constructors. I also fixed one typo on line 176 -> 192.
I install mkdocs, ran mkdocs serve, and verified that the documentation works as intended.
This is a documentation-only update.

Add example strings to sql constructor documentation

---

core/src/main/scala/org/datasyslab/geospark/showcase/ScalaExample.scala

Yes: https://github.com/DataSystemsLab/GeoSpark/issues/235
Nothing else than replacing a 0 by a 1 :-)
Interactively using the spark-shell.
Also, it is now conform to what is written the Scala [test](https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/test/scala/org/datasyslab/geospark/scalaTest.scala).
No.

Set PointRDDOffset to 1 when loading arealm-small.csv in the ScalaExample

---

viz/src/main/java/org/datasyslab/geosparkviz/core/VisualizationOperator.java
viz/src/main/java/org/datasyslab/geosparkviz/utils/Pixel.java

Yes, see Issue https://github.com/DataSystemsLab/GeoSpark/issues/234
https://github.com/DataSystemsLab/GeoSpark/issues/231 
Remove the useless count initialization code
Add the Null and class type check for Pixel.equals function
Passed the regression test

Fix NullPointerException bug and OutOfMem bug

---

docs/api/sql/GeoSparkSQL-Function.md
sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Functions.scala
sql/src/main/scala/org/datasyslab/geosparksql/UDF/Catalog.scala
sql/src/test/scala/org/datasyslab/geosparksql/functionTestScala.scala

Yes, https://github.com/DataSystemsLab/GeoSpark/issues/244
Also add the docs for ST_IsValid https://github.com/DataSystemsLab/GeoSpark/pull/241
[SQL] Add a new API called "ST_PrecisionReduce" to reduce the precision of coordinates, in order to avoid "side location conflict"
Introduction: Reduce the decimals places in the coordinates of the geometry to the given number of decimal places. The last decimal place will be rounded.
Format: `ST_PrecisionReduce (A:geometry, B:int)`
Since: `v1.2.0`
Spark SQL example:
```SQL
SELECT ST_PrecisionReduce(polygondf.countyshape, 9)
FROM polygondf
```
The new coordinates will only have 9 decimal places.
Pass the new unit test and regression test
ST_PrecisionReduce and ST_IsValid docs are added

Add ST_PrecisionReduce and add docs for ST_IsValid

---

LICENSE
LICENSE-before-1.2.0
docs/license/License-before-1-2-0.md
docs/license/License.md
mkdocs.yml

From GeoSpark v1.2.0, change GeoSpark license from MIT License to Apache License 2.0.
Users who use GeoSpark version <1.2.0 can still work with MIT License.
Since the previous license, MIT License, is compatible to Apache License 2.0, this change shouldn't be a problem.
If any previous contributors of GeoSpark have questions, please contact [Jia Yu](jiayu2@asu.edu) and [Mohamed Sarwat](msarwat@asu.edu).

Change GeoSpark license from MIT license to Apache License 2.0

---

sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Functions.scala
sql/src/test/scala/org/datasyslab/geosparksql/functionTestScala.scala

Return null if the geometry is null in [ST_IsValid](https://github.com/DataSystemsLab/GeoSpark/blob/de05c0eed36237fd828c24375376403c86457022/sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Functions.scala#L235) function
Define nullable = true
Add a test to cover it
#288 
Add check for null geometry, and return null when it happens.
This behavior defined by PostGIS for the [ST_IsValid](https://postgis.net/docs/ST_IsValid.html) function docs
I added a test that query ST_IsValid with null geometry
There are no documentation updates

Check for null in ST_IsValid function #288

---

docs/api/sql/GeoSparkSQL-Predicate.md
sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Predicates.scala
sql/src/main/scala/org/datasyslab/geosparksql/UDF/Catalog.scala
sql/src/test/scala/org/datasyslab/geosparksql/predicateTestScala.scala

1. Propose a `ST_Touches` feature for Spatial SQL.
2. Since the `JTS geometry` provides the touching operation, I added a testcase which a small polygon touches a line.
3. Added some docs in `GeoSparkSQL-Predicate.md`.

Spatial SQL ST_Touches

---

sql/src/main/scala/org/apache/spark/sql/geosparksql/strategy/join/JoinQueryDetector.scala
sql/src/test/scala/org/datasyslab/geosparksql/predicateJoinTestScala.scala

No. but related to a review in this [PR](https://github.com/DataSystemsLab/GeoSpark/pull/300#issuecomment-443018927)
Added ST_Touches option to JoinQueryDetector.scala in order that spark will leverage GeoSpark RangeJoin algorithm
Added test in predicateJoinTestScala.scala
Not relevant

Added ST_Touches option to JoinQueryDetector.scala

---

docs/api/sql/GeoSparkSQL-Function.md
sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Functions.scala
sql/src/main/scala/org/datasyslab/geosparksql/UDF/Catalog.scala
sql/src/test/scala/org/datasyslab/geosparksql/functionTestScala.scala

no
add sql function `ST_GeometryType`
`functionTestScala.scala`
yes `String ST_GeometryType(geometry)`，return the geometry type

add ST_GeometryType

---

core/src/main/java/org/datasyslab/geospark/spatialRDD/SpatialRDD.java
core/src/test/java/org/datasyslab/geospark/spatialRDD/SpatialRDDWriterTest.java
docs/tutorial/rdd.md

no
Writing for saveAsWKT Method
even though it can be used as saveAsTextFile method, it is user friendly to write saveAsWKT method.
tested
yes

commit for writing WKT Method.

---

core/pom.xml
pom.xml
sql/pom.xml
sql/src/main/scala/org/apache/spark/sql/geosparksql/strategy/join/JoinQueryDetector.scala
sql/src/main/scala/org/apache/spark/sql/geosparksql/strategy/join/TraitJoinQueryExec.scala
viz/pom.xml

Yes: [#340]( https://github.com/DataSystemsLab/GeoSpark/issues/340), but this PR is for spark 3.0 instead of spark 2.4
Support for compiling with scala 2.12 and spark 3.0
mvn clean install
No api changes made,  just dependency updates, dependency exclusions, a shading exclusion, and very minor changes to:
[JoinQueryDetector.scala](sql/src/main/scala/org/apache/spark/sql/geosparksql/strategy/join/JoinQueryDetector.scala)
and
[TraitJoinQueryExec.scala](sql/src/main/scala/org/apache/spark/sql/geosparksql/strategy/join/TraitJoinQueryExec.scala)
to accommodate changes in spark 3.0

Added support for compiling with scala 2.12 and spark 3.0

---

docs/tutorial/rdd.md

No
I found some examples in the "Spatial RDD application" tutorial don't work or are inconsistent with their context. This PR fixes them.
Ran `mkdocs serve` locally, and confirmed that copy-pasted snippets from the generated page worked manually.
Yes (it's a fix for the documentation itself)

Fix wrong examples in the RDD tutorial

---

docs/tutorial/geospark-core-python.md
docs/tutorial/geospark-sql-python.md

No
This PR fixes code examples in the Python tutorial as follows:
* Remove unnecessary indents for avoiding IndentationError
when copy-pasting example codes to plain pyspark REPL
and format consistency
* Separate example codes and their results so that
users can easily copy-paste the former
* Add required import statements
* Fix wrong table names, method names, variable names, etc.
Ran `mkdocs serve` locally and confirmed that generated examples worked by copy-pasting them to pyspark REPL
Yes (it's a fix for the document itself)

Fix minor issues in the Python tutorial

---

docs/tutorial/viz.md

No
This PR fixes an example query and a variable name in the visualization
tutorial, so that the succeeding query works and the variable names are
consistent in the same document, respectively.
Ran `mkdocs serve` locally and confirmed the modified queries and
snippets worked by copy-pasting from the generated document.
Yes (it's a fix for the documentation itself)

Fix minor issues in the visualization tutorial

---

sql/pom.xml
viz/pom.xml
viz/src/test/java/org/datasyslab/geosparkviz/ChoroplethmapTest.java
viz/src/test/java/org/datasyslab/geosparkviz/ScatterplotTest.java
viz/src/test/scala/org/datasyslab/geosparkviz/rdd/scalaTest.scala

No
Currently, tests for the sql and viz modules are failing, as follows:
https://travis-ci.org/github/DataSystemsLab/GeoSpark/builds/714265634#L697
To fix it, this PR:
* Added required libraries as dependencies.
- Hive dependency is required only for the test, so its scope is limited as 'test'.
- The sql and viz modules also require some GeoTools dependencies
(without them, they fail with `NoSuchAuthorityCodeException`),
so they are added with the 'provided' scope, as the core module.
* Disabled tests for generating SVG, because that feature was removed by the commit 4baed9184d9178e123c3290cf30999f115c3bb53.
Regarding the latter point, I think we can revive this feature in the future
using another SVG library such as Apache Batik instead of JFreeSVG,
so I just commented them out rather …

Fix test failures of the sql and viz modules

---

python/geospark/core/jvm/config.py
python/tests/format_mapper/test_geo_json_reader.py
python/tests/format_mapper/test_shapefile_reader.py
python/tests/sql/test_adapter.py
python/tests/sql/test_function.py
python/tests/utils/test_geo_spark_meta.py

No
The compare_versions function in python/geospark/core/jvm/config.py seems to have a bug.
I think this function is supposed to return True if the left side is equal or higher than the right, but it's broken in some cases.
```
In [1]: from geospark.core.jvm.config import compare_versions                                                                 
In [2]: compare_versions('1.2.3', '1.0.0')                                                                                    
Out[2]: True
In [3]: compare_versions('1.0.0', '1.3.2')                                                                                    
Out[3]: False
In [4]: compare_versions('1.3.2', '1.2.3')                                                                                    
Out[4]: False <- ??
```
This PR …

Fix Python compare_versions function

---

.travis.yml
python/geospark/core/jvm/config.py

No
* Fix Travis configuration to use Spark 3.0.0, pick up the jar files
which contains '-SNAPSHOT' in its version number, and download
jar files that are not included in our distribution due to
the license incompatibility but required to run all tests.
* Fix SparkJars.get_used_jars in geospark/core/jvm/config.py
to search jar files from $SPARK_HOME/jars directly
when SparkConf._jconf.get("spark.jars") returns empty string
rather than raises Exception for some reason.
It's tested on CI and succeeded: https://travis-ci.org/github/sekikn/GeoSpark/builds/714655938
No

Fix CI failure

---

sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/AggregateFunctions.scala
sql/src/main/scala/org/datasyslab/geosparksql/UDF/Catalog.scala
sql/src/main/scala/org/datasyslab/geosparksql/UDF/UdfRegistrator.scala
sql/src/test/scala/org/datasyslab/geosparksql/TestBaseScala.scala
sql/src/test/scala/org/datasyslab/geosparksql/aggregateFunctionTestScala.scala

No
User Defined Aggregate Functions API is depreciated in Spark 3.0.
(https://github.com/apache/spark/pull/25024)
So I rewrite user defined aggregate functions.
yes. add to test.
no(function is not changed)

Aggregate Functions rewrite for new Aggregator API

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/UDT/GeometryUDT.scala
sql/src/test/scala/org/apache/sedona/sql/GeometryUdtTestScala.scala

SEDONA-20
Implementation of a custom equals method for GeometryUDT because auf changes in the base class UserDefinedType made in Spark 3.0.2
Unit test
No
<sup>Michael Merg (<michael.merg@daimler.com>), Mercedes-Benz AG on behalf of MBition GmbH ([Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md))</sup>

[SEDONA-20] Add custom equals method to GeometryUDT

---

core/src/main/java/org/apache/sedona/core/spatialOperator/JoinQuery.java
core/src/test/java/org/apache/sedona/core/spatialOperator/LineStringJoinTest.java
core/src/test/java/org/apache/sedona/core/spatialOperator/PointJoinTest.java
core/src/test/java/org/apache/sedona/core/spatialOperator/PolygonJoinTest.java
core/src/test/java/org/apache/sedona/core/spatialOperator/RectangleJoinTest.java
core/src/test/scala/org/apache/sedona/core/scalaTest.scala
python-adapter/src/main/scala/org.apache.sedona.python.wrapper/adapters/JoinParamsAdapter.scala
python/sedona/core/spatialOperator/join_params.py
python/tests/core/test_avoiding_python_jvm_serde_df.py
python/tests/core/test_avoiding_python_jvm_serde_to_rdd.py
python/tests/core/test_rdd.py
python/tests/spatial_operator/test_linestring_join.py
python/tests/spatial_operator/test_point_join.py
python/tests/spatial_operator/test_polygon_join.py
python/tests/spatial_operator/test_rectangle_join.py
python/tests/sql/test_function.py
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryExec.scala

https://issues.apache.org/jira/browse/SEDONA-19
Fixes a bug where useIndex was always false when setting the index type and index build side. 
Existing tests still pass, but not sure how you would check if the index was used or not.
Updates the code to reflect what the documentation already says.

[SEDONA-19] Update JoinParams to not always set useIndex to false

---

docs/tutorial/geospark-sql-python.md
docs/tutorial/sql-sql.md
docs/tutorial/sql.md
docs/tutorial/viz.md
sql/src/main/scala/org/apache/sedona/sql/SedonaSqlExtensions.scala
viz/src/main/scala/org/apache/sedona/viz/sql/SedonaVizExtensions.scala

[SEDONA-21](https://issues.apache.org/jira/browse/SEDONA-21)
With this change we can use Sedona UDFs/UDTs from Spark SQL, for example, from `spark-sql`
or via Thrift server.  Just need to add following to command-line:
```
--conf spark.sql.extensions=org.apache.sedona.viz.sql.SedonaVizExtensions,org.apache.sedona.sql.SedonaSqlExtensions \
--conf spark.kryo.registrator=org.apache.spark.serializer.KryoSerializer \
--conf spark.kryo.registrator=org.apache.sedona.viz.core.Serde.SedonaVizKryoRegistrator
```
manual test using `spark-sql`
yes

[SEDONA-21] Add extension classes for auto registration of UDFs/UDTs

---

.gitignore
docs/api/sql/GeoSparkSQL-Optimizer.md
docs/api/sql/GeoSparkSQL-Overview.md
python-adapter/.gitignore
python/tests/sql/test_predicate_join.py
spark-version-converter.py
sql/src/main/scala/org/apache/sedona/sql/utils/SedonaSQLRegistrator.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Predicates.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastIndexJoinExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/DistanceJoinExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/SpatialIndexExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryBase.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/enums.scala
sql/src/test/scala/org/apache/sedona/sql/BroadcastIndexJoinSuite.scala
sql/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala
sql/src/test/scala/org/apache/sedona/sql/predicateJoinTestScala.scala

https://issues.apache.org/jira/browse/SEDONA-26
Adds SQL broadcast join support. Broadcast hints are detected in the SQL Join detector and will execute a new `BroadcastIndexJoin` plan (that uses a `SpatialIndex` child plan, mostly for nice display purposes in the query plan).
New UT, still need to add more
Yes
Still have some work to do on this, but wanted to get some initial feedback on the overall approach. I opted to keep things purely in SQL land instead of trying to add more parameters to spatialJoin or add another new core package that SQL calls out to. ~Currently works for Spark 3, and it compiles in Spark 2 but the new test fails because broadcasts aren't currently detected in Spark 2.~ Figured out the Spark 2 support.
Also, I tried to better maintain the concept of left and right …

[SEDONA-26] Add broadcast join support

---

.github/workflows/java.yml
.github/workflows/python.yml
docs/api/viz/sql.md
docs/download/overview.md
docs/tutorial/viz.md
examples/rdd-colocation-mining/build.sbt
examples/sql/build.sbt
examples/viz/build.sbt
examples/viz/src/main/scala/ScalaExample.scala
pom.xml
python-adapter/pom.xml
sql/src/test/scala/org/apache/sedona/sql/adapterTestScala.scala
viz/src/main/scala/org/apache/spark/sql/sedona_viz/expressions/Pixelize.scala
viz/src/test/scala/org/apache/sedona/viz/sql/TestBaseScala.scala
viz/src/test/scala/org/apache/sedona/viz/sql/optVizOperatorTest.scala
viz/src/test/scala/org/apache/sedona/viz/sql/standardVizOperatorTest.scala

https://issues.apache.org/jira/browse/SEDONA-29
1. Tweak all workflows to support Spark 2.4, 3.0, 3.1 CI
2. Rewrite ST_Pixelize using Expression instead of Generator to make Lateral View recognize this function
Passed the unit tests
Yes

[SEDONA-29] Upgrade to Spark 3.1.1 and fix ST_Pixelize

---

core/src/test/java/org/apache/sedona/core/io/EarthdataHDFTest.java
pom.xml

N/A
This PR is to fix an issue that occurred in the release procedure. The resolved-pom plugin was supposed to replace all pom variables with real values in the initialize phase of the Maven build lifecyle. Otherwise, the new poms will not be uploaded to Maven Central.
Pass all existing test cases

Make the pom file ready to upload checksum using the resolved pom

---

sql/src/main/scala/org/apache/sedona/sql/utils/Adapter.scala
sql/src/test/scala/org/apache/sedona/sql/adapterTestScala.scala

Signed-off-by: Yitao Li <yitao@rstudio.com>
https://issues.apache.org/jira/browse/SEDONA-35
I think we should create an issue for it.
The problem is currently if `Adapter.toDf()` is called with a `SpatialRDD` carrying non-spatial attributes (a.k.a "user data") in addition to spatial attributes, then the Spark dataframe returned from `toDf()` can only be evaluated successfully once. If it was  evaluated more than once, then a null pointer exception occurrs. If a Spark dataframe is not cached, then the underlying RDD could be evaluated more than once in many scenarios, so, the NPE problem could break quite a few use cases.
Essentially, the changes in this PR ensures `toDf()` respects the immutability of `RDD`s in Spark. The abovementioned NPE issue happens because the `Geometry` objects …

[SEDONA-35] address user-data mutability issue with `Adapter.toDF()`

---

python/sedona/core/jvm/config.py

https://issues.apache.org/jira/browse/SEDONA-50
Importing this file causes logging issues within databricks.
Full error:
```
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib/python3.7/logging/__init__.py", line 1025, in emit
msg = self.format(record)
File "/usr/lib/python3.7/logging/__init__.py", line 869, in format
return fmt.format(record)
File "/usr/lib/python3.7/logging/__init__.py", line 611, in format
s = self.formatMessage(record)
File "/usr/lib/python3.7/logging/__init__.py", line 580, in formatMessage
return self._style.format(record)
File "/usr/lib/python3.7/logging/__init__.py", line 422, in format
return self._fmt % record.__dict__
ValueError: unsupported format character '%' (0x25) at index 11
Call stack:
File …
```

[SEDONA-50] Removing logging configuration as it causes errors on databricks.

---

.github/workflows/r.yml

Signed-off-by: Yitao Li <yitao@rstudio.com>
No.
This is a trivial change to fix the GitHub rate-limiting problem encountered in https://github.com/apache/incubator-sedona/pull/534
via GitHub Actions workflows for R builds
No.

use GITHUB_TOKEN to authenticate `remotes::install_github()` web requests

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/SpatialIndexExec.scala
sql/src/test/scala/org/apache/sedona/sql/BroadcastIndexJoinSuite.scala

https://issues.apache.org/jira/browse/SEDONA-56
Small fix for SpatialIndexExec to just extend UnaryExecNode instead of Exchange to make it run with AQE enabled.
New unit test.
None needed, bug fix.

[SEDONA-56] Fix broadcast join with AQE enabled

---

core/src/main/java/org/apache/sedona/core/joinJudgement/NestedLoopJudgement.java

https://issues.apache.org/jira/browse/SEDONA-63
Return immediately if one of the sides is empty in NestedLoopJudgement as already implemented in indexed join judgements.
Current set of test in Sedona should cover this change. 
Small performance improvement (~10%) observed with some of our Sedona jobs.
No documentation changes needed.

[SEDONA-63] Skip empty partitions in NestedLoopJudgement

---

core/src/main/java/org/apache/sedona/core/joinJudgement/JudgementBase.java
core/src/main/java/org/apache/sedona/core/spatialOperator/JoinQuery.java

https://issues.apache.org/jira/browse/SEDONA-64
Broadcast dedupParams to reduce task size.
Current tests in Sedona covers the change.
Test with production workloads. We see a 20% reduction in execution time for jobs with a large partition count.
Javadoc for an added public method.

[SEDONA-64] Broadcast dedupParams to improve performance

---

core/src/main/java/org/apache/sedona/core/spatialRDD/SpatialRDD.java
core/src/main/java/org/apache/sedona/core/utils/RDDSampleUtils.java
core/src/test/java/org/apache/sedona/core/spatialOperator/PolygonJoinTest.java
core/src/test/java/org/apache/sedona/core/utils/RDDSampleUtilsTest.java
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryBase.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryExec.scala
sql/src/test/scala/org/apache/sedona/sql/predicateJoinTestScala.scala

Yes, [SEDONA-60](https://issues.apache.org/jira/browse/SEDONA-60) and [SEDONA-22](https://issues.apache.org/jira/browse/SEDONA-22).
This patch fixes spatial joins performed in Spark SQL: when the dominant side contains only one row or no rows, we'd like to perform the join as usual instead of raising exceptions.
We've added new unit tests to cover these 2 cases.
No.

[SEDONA-22] [SEDONA-60] Fix join in Spark SQL when one side has no rows or only one row

---

.github/workflows/java.yml
.github/workflows/python.yml
.github/workflows/r.yml
pom.xml
python/tests/serialization/test_deserializers.py
sql/src/main/scala/org/apache/sedona/sql/UDF/UdfRegistrator.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/execution/SedonaSparkPlan.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Constructors.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Predicates.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/Functions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/IO.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastIndexJoinExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/DistanceJoinExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/RangeJoinExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/SpatialIndexExec.scala
viz/src/main/scala/org/apache/sedona/viz/sql/UDF/UdfRegistrator.scala
viz/src/main/scala/org/apache/spark/sql/sedona_viz/expressions/Colorize.scala
viz/src/main/scala/org/apache/spark/sql/sedona_viz/expressions/ImageEncoder.scala
viz/src/main/scala/org/apache/spark/sql/sedona_viz/expressions/Partitioner.scala
viz/src/main/scala/org/apache/spark/sql/sedona_viz/expressions/Pixelize.scala
viz/src/main/scala/org/apache/spark/sql/sedona_viz/expressions/Render.scala
viz/src/test/scala/org/apache/sedona/viz/sql/optVizOperatorTest.scala
viz/src/test/scala/org/apache/sedona/viz/sql/standardVizOperatorTest.scala

https://issues.apache.org/jira/browse/SEDONA-67
Adds support for Spark 3.2, but maintains compatibilities.
Specifically to get 3.2 working I had to:
- Rework how functions are registered to use an API present in all supported versions of Spark.
- Add `withNewChildrenInternal` to all expressions. Without using `override`, it works both in the new version to override it as well as in older versions it's just ignored.
- Add a new profile for Spark 3.2 because it needs a newer version of jackson to test with
Additionally I cleaned up a few things:
- Removed assert statements from the eval method of expressions. This is an analysis time check that can be done on instantiation of the case class
- Removed a bunch of return statements to make things consistent
Existing tests, though I do need …

[SEDONA-67] Support Spark 3.2

---

.github/workflows/r.yml
R/tests/testthat/test-crs-transform.R
R/tests/testthat/test-dbplyr-integration.R

No.
- Apply the workaround suggested in https://github.com/apache/incubator-sedona/pull/557#issuecomment-961491472
- Re-enable R builds for Spark 3.2
Unit test
N/A

[SEDONA-67] apply workaround for SPARK-37202; re-enable R builds for Spark 3.2

---

.github/workflows/java.yml
.github/workflows/r.yml
pom.xml
python-adapter/src/main/scala/org.apache.sedona.python.wrapper/adapters/EnvelopeAdapter.scala
python-adapter/src/main/scala/org.apache.sedona.python.wrapper/adapters/PythonConverter.scala
python-adapter/src/main/scala/org.apache.sedona.python.wrapper/translation/GeometrySeqToPythonConverter.scala
python-adapter/src/main/scala/org.apache.sedona.python.wrapper/utils/PythonAdapterWrapper.scala
python-adapter/src/test/scala/org/apache/sedona/python/wrapper/GeometrySample.scala
python-adapter/src/test/scala/org/apache/sedona/python/wrapper/TestToPythonSerialization.scala
sql/src/main/scala/org/apache/sedona/sql/SedonaSqlExtensions.scala
sql/src/main/scala/org/apache/sedona/sql/utils/Adapter.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/Functions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/SpatialIndexExec.scala
sql/src/test/scala/org/apache/sedona/sql/GeometrySample.scala
sql/src/test/scala/org/apache/sedona/sql/adapterTestScala.scala
sql/src/test/scala/org/apache/sedona/sql/functions/TestStSubDivide.scala
sql/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala
viz/src/main/scala/org/apache/sedona/viz/sql/SedonaVizExtensions.scala
viz/src/main/scala/org/apache/sedona/viz/sql/operator/VizPartitioner.scala
viz/src/main/scala/org/apache/spark/sql/sedona_viz/expressions/Pixelize.scala

https://issues.apache.org/jira/browse/SEDONA-73
Adds a Scala 2.13 Maven profile and updates the code base to support 2.13 in addition to existing versions. A new dependency was added that provides backward compatibility for various Java-Scala conversion utilities. I enabled the Java tests to also run with 2.13.
It will be a little trickier to figure out how to run the Python or R tests with Scala 2.13, because I think both just download official releases to do it. It looks like there are official releases for Scala 2.13, but I am not trying to tackle that in this PR. The Python tests would likely have to be updated to download the official release versus installing from Pypi, because that only comes with the default Scala version. This is mostly for experimental purposes, and for making …

[SEDONA-73] Add support for Scala 2.13 build

---

docs/api/sql/Raster-operators.md
docs/setup/databricks.md

In the Databricks doc, I think the path to the init script should be prefixed with `dbfs:` as opposed to a directory in the local file system. After this change on my Azure Databricks cluster, the init script executed successfully.
No
Document update
Fix tested on an Azure Databricks cluster
Yes

[DOCS] Fix typo in Raster & Databricks doc

---

pom.xml

Follow up to https://issues.apache.org/jira/browse/SEDONA-73, exclude scala-library from the new dependency.
Dependency update
Existing tests

[SEDONA-73][FOLLOWUP] Exclude scala-library from scala-collection-compat

---

.github/workflows/docs.yml
mkdocs.yml

Fix the failed DOCS CI which is caused by the name changing in fontawesome: https://fontawesome.com/docs/web/setup/upgrade/whats-changed#icons-renamed-in-version-6

[CI] Fix docs GitHub CI by updating fontawesome name

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

https://issues.apache.org/jira/browse/SEDONA-86
Support empty geometries in ST_AsBinary and ST_AsEKWB
No documentation updates needed

[SEDONA-86] Support empty geometries in ST_AsBinary and ST_AsEWKB

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/UDT/GeometryUDT.scala

https://issues.apache.org/jira/browse/SEDONA-89
`GeometryUDT.equals` currently returns true for **any** UDT, not just other geometry
Internally with another project.
No APIs change in any appreciable way.

[SEDONA-89] GeometryUDT equals should test equivalence of the other object

---

docs/api/sql/Function.md
sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/collect/Collect.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/collect/ST_Collect.scala
sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

[SEDONA-100
](https://issues.apache.org/jira/browse/SEDONA-100)
ST_Multi 
unit test added
yes

[SEDONA-100] Add st_multi function

---

docs/api/sql/Function.md
pom.xml
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

I will always return a single geometry and works for all geometry types.
[SEDONA-96](https://issues.apache.org/jira/browse/SEDONA-96)
Refactor ST_MakeValid to use GeometryFixer in JTS
Yes

[SEDONA-96] Refactor ST_MakeValid to use GeometryFixer.

---

docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/tests/sql/test_function.py
sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

[SEDONA-107](https://issues.apache.org/jira/projects/SEDONA/issues/SEDONA-107)
ST_Reverse Function
Scala, Python, Java integration tests
Yes

[SEDONA-107] Add St_Reverse function

---

core/src/main/java/org/apache/sedona/core/utils/GeomUtils.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/tests/sql/test_function.py
sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

[SEDONA-105](https://issues.apache.org/jira/browse/SEDONA-105)
Added ST_PointOnSurface
Added unit tests for Scala, Python and Java. Tested the website using mkdocs.
Yes. Added descriptions on the websites and in the source code.

[SEDONA-105] Add ST_PointOnSurface function

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Predicates.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-118. The PR name follows the format `[SEDONA-118] my subject`.
Changing the JTS method called during ST_Within evaluation from coveredBy to within
It was ensured that for the affected query:
`ST_Within(ST_GeomFromWKT('POINT(0 0)'),ST_GeomFromWKT('POLYGON ((0.0 0.0, 10.0 0.0, 10.0 10.0, 0.0 10.0, 0.0 0.0))')) `
The correct value (false) is returned. 

[SEDONA-118] Using the within function of JTS for ST_Within

---

docs/api/flink/Constructor.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Constructors.java
flink/src/test/java/org/apache/sedona/flink/ConstructorTest.java
flink/src/test/java/org/apache/sedona/flink/TestBase.java

Added equivalent constructors left over from Spark to Flink
Added tests.

[SEDONA-121] constructors from spark2flink

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Constructors.scala
sql/src/test/scala/org/apache/sedona/sql/constructorTestScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-127. The PR name follows the format `[SEDONA-XXX] my subject`.
This PR adds null safety to ST_GeomFromWKB, ST_GeomFromWKT and ST_GeomFromTest

[SEDONA-127] Add null safety to ST_GeomFromWKT/WKB/Text

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/geohash/GeometryGeoHashEncoder.scala
sql/src/test/scala/org/apache/sedona/sql/functions/geohash/TestStGeoHash.scala

- Yes, the URL of the assoicated JIRA ticket is <https://issues.apache.org/jira/browse/SEDONA-123>. The PR name follows the format `[SEDONA-XXX] my subject`.
Currently, ST_GeoHash checks for invalid latitude and longitude values (in `GeometryGeoHashEncoder.scala`):
- Longitude < -180
- Latitude < -90
- Longitude > 180
- *Longitude* > 90
This PR fixes the last comparison to check latitude instead of longitude.
Added unit tests that fail before the fix (as well as some passing tests for similar boundary cases), implemented the fix suggested by Itamar, and tests now pass again.
Some screenshots during the process:
Test results …

[SEDONA-123] Fix check for invalid latitude/longitude values in ST_GeoHash

---

R/tests/testthat/test-dbplyr-integration.R

Signed-off-by: Yitao Li <yitaoli@apache.org>
Fixing one failing test case in R
`TESTTHAT_FILTER='sdf-interface' SPARK_VERSION='2.4.8' NOT_CRAN='true' Rscript testthat.R --testthat`

[DOCS] fix dbplyr integration test failures

---

python/tests/streaming/spark/test_constructor_functions.py

The random tables names in Python tests occasionally fail due to duplicate table names. This PR uses UUID to replace random table names.

[DOCS] Fix Python tests which randomly fails

---

flink/src/test/java/org/apache/sedona/flink/AdapterTest.java
flink/src/test/java/org/apache/sedona/flink/ConstructorTest.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
flink/src/test/java/org/apache/sedona/flink/PredicateTest.java

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-139. The PR name follows the format `[SEDONA-XXX] my subject`.
- This PR fixes the argument order passed to JUnit's assert methods so that developers doesn't get confused.
- Ran `mvn test -pl flink` locally and ensured all tests passed.

[SEDONA-139] Fix wrong argument order in Flink unit tests

---

flink/src/test/java/org/apache/sedona/flink/FunctionTest.java

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-136. The PR name follows the format `[SEDONA-XXX] my subject`.
This PR enables testAsEWKT for Flink again, which was accidentally disabled before.
Ran `mvn test -pl flink` locally and confirmed the number of tests executed was incremented.

[SEDONA-136] Enable testAsEWKT for Flink

---

docs/api/flink/Constructor.md
docs/api/flink/Function.md
docs/api/flink/Predicate.md
docs/api/sql/AggregateFunction.md
docs/api/sql/Constructor.md
docs/api/sql/Function.md
docs/api/sql/Parameter.md
docs/api/sql/Predicate.md
docs/api/sql/Raster-loader.md
docs/api/sql/Raster-operators.md
docs/api/viz/sql.md

Currenly, the items in the API reference seems to be ordered randomly,
and it makes difficult for users to find the function they need.
It is more user-friendly if they were arranged in alphabetical order.
Ran `mkdocs serve` locally and made sure that the API docs were fixed as expected.

[DOCS] Arrange items in the API reference in alphabetical order

---

flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-137. The PR name follows the format `[SEDONA-XXX] my subject`.
Currently, the ST_Buffer function for Flink is broken. This PR fixes it.
Ran `mvn test -pl flink` locally and ensured all tests passed including the new one.

[SEDONA-137] Fix ST_Buffer for Flink to work

---

flink/src/test/java/org/apache/sedona/flink/PredicateTest.java
flink/src/test/java/org/apache/sedona/flink/TestBase.java

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-143. The PR name follows the format `[SEDONA-XXX] my subject`.
Currently, ST_Contains and ST_OrderingEquals for Flink don't have their unit test. This PR adds them.
Ran `mvn test -pl flink` locally.

[SEDONA-143] Add missing unit tests for the Flink predicates

---

common/src/main/java/org/apache/sedona/common/utils/GeomUtils.java
python/tests/sql/test_function.py
sql/src/main/scala/org/apache/sedona/sql/utils/GeometrySerializer.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-145. The PR name follows the format `[SEDONA-XXX] my subject`.
- This PR fixes ST_AsEWKT to reserve the Z coordinate.
- Ran `mvn clean install -Dgeotools` locally
- Ran `pipenv run pytest tests/sql/test_function.py` locally with the artifact above

[SEDONA-145] Fix ST_AsEWKT to reserve the Z coordinate

---

docs/api/sql/Constructor.md
docs/api/sql/Function.md

This PR adds the following missing functions to the Spark SQL reference.
* ST_GeomFromText
* ST_LineInterpolatePoint
* ST_LineSubstring
- Ran `mkdocs serve` locally

[DOCS] Document SQL functions not in the API reference

---

.github/workflows/python.yml

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-149. The PR name follows the format `[SEDONA-XXX] my subject`.
- This PR adds a new condition to the GitHub Actions for ensuring the current code works with Python 3.10. In this PR, I added quotes to the version numbers in python.yml, since "python: 3.10" is interpreted as "python: 3.1" without quotes.
- Tested on my own GitHub repository.

[SEDONA-149] Add Python 3.10 support

---

python/sedona/sql/types.py
python/tests/serialization/test_deserializers.py
python/tests/serialization/test_serializers.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-153. The PR name follows the format `[SEDONA-XXX] my subject`.
- Added guards to the python methods `GeometryType.toInternal` and `GeometryType.fromInternal`. This allows for null geometry to be passed between python and the JVM.
- Added two new unit tests: `test_null_deserializer` in test_deserializers.py and `test_null_serializer` in test_serializers.py. Both of these tests fail on the current release of Sedona and now pass with this PR.

[SEDONA-153] Add None guards to GeometryType

---

common/src/main/java/org/apache/sedona/common/Functions.java
docs/api/flink/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-159. The PR name follows the format `[SEDONA-XXX] my subject`.
This PR adds ST_GeometryN and ST_InteriorRingN to the Flink API.
- Ran `mvn clean install` locally.
- Ran `mkdocs serve` and checked the generated documents.

[SEDONA-159] Add Nth accessor functions to the Flink API

---

sql/src/test/scala/org/apache/sedona/sql/geoparquetIOTests.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-160. The PR name follows the format `[SEDONA-XXX] my subject`.
- This PR fixes geoparquetIOTests.scala to remove its output files after running tests.
- Ran `mvn clean test -pl sql -am` and confirmed that no output files were left after tests

[SEDONA-160] Fix geoparquetIOTests.scala to cleanup after test

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-169. The PR name follows the format `[SEDONA-XXX] my subject`.
This PR fixes ST_RemovePoint to work without the second parameter, in accordance with its API document.
Ran `mvn clean install` locally.

[SEDONA-169] Fix ST_RemovePoint in accordance with the API document

---

common/src/main/java/org/apache/sedona/common/Functions.java
docs/api/flink/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-170. The PR name follows the format `[SEDONA-XXX] my subject`.
- This PR adds ST_AddPoint and ST_RemovePoint to the Flink API.
- Ran `mvn clean install` locally
- Ran `mkdocs serve` and checked the generated API document

[SEDONA-170] Add ST_AddPoint and ST_RemovePoint to the Flink API

---

.gitignore
docs/tutorial/sql-python.md
docs/tutorial/sql.md
python/sedona/register/java_libs.py
python/sedona/sql/dataframe_api.py
python/sedona/sql/st_aggregates.py
python/sedona/sql/st_constructors.py
python/sedona/sql/st_functions.py
python/sedona/sql/st_predicates.py
python/tests/sql/test_dataframe_api.py
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/DataFrameAPI.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_aggregates.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_constructors.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_predicates.scala
sql/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-166. The PR name follows the format `[SEDONA-XXX] my subject`.
Introduce a type-safe DataFrame style API similar to standard Spark functions. The API can operate on Spark `Column` types directly or function specific native Scala/Java types. For example, the function `ST_CollectionExtract` can be called in the following ways:
```scala
val df = sparkSession.sql("SELECT ST_GeomFromWKT('GEOMETRYCOLLECTION(POINT(0 0), LINESTRING(0 0, 1 0))') AS geom")
// with Column objects and default geomType argument …
```

[SEDONA-166] Support type-safe dataframe style API

---

common/src/main/java/org/apache/sedona/common/Functions.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
python/tests/sql/test_function.py
sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
sql/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-172. 
ST_LineFromMultiPoint Function
Scala, Python, Java integration tests

[SEDONA-172] Add ST_LineFromMultiPoint Function to SEDONA SQL API

---

docs/api/flink/Predicate.md
docs/api/sql/Predicate.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Predicates.java
flink/src/test/java/org/apache/sedona/flink/PredicateTest.java
python/sedona/sql/st_predicates.py
python/tests/sql/test_dataframe_api.py
sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Predicates.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_predicates.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
sql/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
sql/src/test/scala/org/apache/sedona/sql/predicateJoinTestScala.scala
sql/src/test/scala/org/apache/sedona/sql/predicateTestScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-176. The PR name follows the format `[SEDONA-176] my subject`.
* `ST_Contains` in Spark SQL module calls JTS function `contains` instead of `covers`.
* Added `ST_Covers`, which calls JTS function `covers`.
* Added `ST_CoveredBy`, which calls JTS function `coveredBy`.
* Added dataframe functions for `ST_Covers` and `ST_CoveredBy`.
Unit tests were added in this patch.

[SEDONA-176] Make ST_Contains conform with OGC standard, and add ST_Covers and ST_CoveredBy functions.

---

docs/tutorial/core-python.md
docs/tutorial/rdd.md
pom.xml
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastIndexJoinExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/DistanceJoinExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/SpatialIndexExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryBase.scala
sql/src/test/scala/org/apache/sedona/sql/BroadcastIndexJoinSuite.scala
sql/src/test/scala/org/apache/sedona/sql/SpatialJoinSuite.scala
sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
sql/src/test/scala/org/apache/sedona/sql/predicateJoinTestScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-178. The PR name follows the format `[SEDONA-178] my subject`.
Sedona SQL doesn't rely on Circle for distance joins. Correct results are now produces for all geometry types.
Performance could be improved but would require some refactoring of the spatial partitioning code.
See the jira for discussion.
All unit tests pass. New tests added.

[SEDONA-178] Correctness issue in distance joins

---

pom.xml

~~- No, I haven't read it.~~
- Yes SEDONA-181
~~- No, this is a documentation update. The PR name follows the format `[DOCS] my subject`.~~
Update `scalatest-maven-plugin` version because of https://github.com/scalatest/scalatest-maven-plugin/issues/26
`mvn clean install` in env where `JAVA_HOME` points to java8 and default java is 19
~~- Yes, I am adding a new API. I am using the [current SNAPSHOT version number](https://github.com/apache/incubator-sedona/blob/master/pom.xml#L29) in since `vX.Y.Z` format.~~
~~- Yes, I have updated the documentation update.~~ …

[SEDONA-181] Bump scalatest-maven-plugin to make it respect JAVA_HOME

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/main/java/org/apache/sedona/common/utils/GeomUtils.java
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-182. The PR name follows the format `[SEDONA-XXX] my subject`.
ST_AsText should return a WKT string and not a EWKT string
Unit test added

[SEDONA-182] ST_AsText should not return SRID

---

python/sedona/core/jvm/config.py
python/tests/core/test_config.py

When Sedona is deployed via YARN the version check fails due to the jars being listed under `spark.yarn.dist.jars` instead of `spark.jars`. 
- Added a unit test to mock the behaviour
- Tested that Sedona is listed in `spark.yarn.dist.jars` on a YARN deployment

[SEDONA-183] Python version check fails when Sedona JAR is distributed by YARN

---

common/src/main/java/org/apache/sedona/common/Functions.java
python/tests/sql/test_dataframe_api.py
sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/src/main/scala/org/apache/sedona/sql/UDF/UdfRegistrator.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Constructors.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/DataFrameAPI.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/NullSafeExpressions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Predicates.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/collect/Collect.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_constructors.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
sql/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-180.
This patch makes ST_* functions foldable, and declared input types for these functions to make the SQL analyzer perform type checking for these ST_* function calls and emit more friendly error messages. Raster functions and viz functions are still left unchanged.
I've deliberately left `ST_Binary` and `ST_AsEWKB` unfoldable since unit tests would fail after making these expressions foldable.
The reason is that folding binary expressions as constants triggers a function call to [`encodeHexString(byte[], …

[SEDONA-180] Make ST_* expressions foldable and declares input types for type checking

---

python/sedona/core/jvm/config.py

[SEDONA-188](https://issues.apache.org/jira/browse/SEDONA-188)
The bug fix in https://github.com/apache/incubator-sedona/pull/705 has inadvertently made logging warnings very noisy. As we now check both `spark.jars` and `spark.yarn.dist.jars` at least one will fail every time. The PR changes the logic so that we only log a warnings if neither have returned some Jars. 
Existing unit test.

[SEDONA-188] Python warns about missing `jars` even when some are found

---

core/src/main/java/org/apache/sedona/core/spatialOperator/SpatialPredicateEvaluators.java
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastIndexJoinExec.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-189. The PR name follows the format `[SEDONA-189] my subject`.
Use prepared geometries in `BroadcastIndexJoinExec` to speed up queries. In jira there is a simple dataset of polygons and points, where the speedup is around 4x.
Preparing the geometry has some overhead, but it will be compensated if the prepared geometry will be used several times. Using it in broadcast join seems like a safe bet - the broadcasted dataset is meant to be small.
Running the existing UTs in sql submodule
- No, this PR does not affect any public API so no need …

[SEDONA-189] Prepare geometries in broadcast join

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/DistanceJoinExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/RangeJoinExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryExec.scala
sql/src/test/scala/org/apache/sedona/sql/SpatialJoinSuite.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-186
Fixes [SEDONA-186](https://issues.apache.org/jira/browse/SEDONA-186) by properly assembling result rows of join queries when left and right sub plans were swapped.
New tests were added to `SpatialJoinSuite`.

[SEDONA-186] Fix ordering of columns in results of queries like SELECT * A JOIN B

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Predicates.scala
sql/src/test/scala/org/apache/sedona/sql/predicateTestScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-192. The PR name follows the format `[SEDONA-XXX] my subject`.
Allow nulls in predicate inputs - currently they end with nullpointer exception. Also added the `org.apache.spark.sql.catalyst.expressions.NullIntolerant` trait to `ST_Predicate`, so catalyst optimizer can infer notnull filters on nullable inputs.
Unittests

[SEDONA-192] Null handling in predicates

---

common/src/main/java/org/apache/sedona/common/Functions.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_function.py
sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-197. The PR name follows the format `[SEDONA-XXX] my subject`.
Added ST_ZMax and ST_ZMin functions to SQL
Through unit tests written in Scala

[SEDONA-197] Added ST_ZMax and ST_ZMin to Apache Sedona

---

core/src/main/java/org/apache/sedona/core/utils/SedonaConf.java
core/src/test/java/org/apache/sedona/core/utils/SedonaConfTest.java
docs/api/sql/Parameter.md
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryExec.scala
sql/src/test/scala/org/apache/sedona/sql/predicateJoinTestScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-208. The PR name follows the format `[SEDONA-XXX] my subject`.
Use dynamic runtime configuration in Sedona

[SEDONA-208] Use Spark RuntimeConfig in SedonaConf

---

common/src/main/java/org/apache/sedona/common/Functions.java
sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-206. The PR name follows the format `[SEDONA-206] my subject`.
Swap CRS.decode and CRS.parseWKT in ST_Transform function. So the default becomes that first try CRS.decode then call CRS.parseWKT. This makes sense since in most cases, people just use an existing CRS code issues by an authority. This could significantly speed up ST_Transform
Passed unit tests

[SEDONA-206] Performance regression of ST_Transform

---

core/src/main/java/org/apache/sedona/core/formatMapper/EarthdataHDFPointMapper.java
core/src/main/java/org/apache/sedona/core/formatMapper/netcdfParser/HDFSRandomAccessFile.java
core/src/main/java/org/apache/sedona/core/formatMapper/netcdfParser/SerNetCDFUtils.java
core/src/test/java/org/apache/sedona/core/formatMapper/testSerNetCDF.java
docs/setup/maven-coordinates.md
pom.xml
viz/pom.xml

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-194. The PR name follows the format `[SEDONA-194] my subject`.
1. Move SerNetCDF to Sedona
2. Add unidata repo and cdm-core to Sedona dependency
3. Remove the shaded SerNetCDF dependency
No actual tests are added. Reason:
1. We deprecated HDF/NetCDF support in Spark RDD.
2. We plan to launch more mature support for different raster formats in DataFrame

[SEDONA-194] Merge org.datasyslab.sernetcdf into Sedona

---

core/src/main/java/org/apache/sedona/core/utils/SedonaConf.java
core/src/test/java/org/apache/sedona/core/utils/SedonaConfTest.java
docs/api/sql/Parameter.md
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
sql/src/test/scala/org/apache/sedona/sql/BroadcastIndexJoinSuite.scala
sql/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-217. The PR name follows the format `[SEDONA-XXX] my subject`.
Automatic broadcasting of small joins
Unit test added

[SEDONA-217] Automatically broadcast small datasets.

---

sql/src/main/scala/org/apache/sedona/sql/utils/Adapter.scala
sql/src/test/scala/org/apache/sedona/sql/adapterTestScala.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-218. The PR name follows the format `[SEDONA-218] my subject`.
Handle null struct values properly in `Adapter.toDF` and fix related flaky tests. Please refer to the JIRA ticket for details.
The flaky unit test fails randomly since it has non-deterministic behavior, we make it deterministic and pass consistently in this patch.

[SEDONA-218] Fix a flaky test caused by improper handling of null struct values in `Adapter.toDf`

---

python/sedona/sql/types.py
sql/src/main/scala/org/apache/sedona/sql/utils/Adapter.scala
sql/src/main/scala/org/apache/sedona/sql/utils/GeometrySerializer.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/UDT/GeometryUDT.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Constructors.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Predicates.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/collect/ST_Collect.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/collect/ST_CollectionExtract.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/implicits.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/io/GeotiffFileFormat.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryBase.scala
viz/src/main/scala/org/apache/spark/sql/sedona_viz/expressions/Pixelize.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-205. The PR name follows the format `[SEDONA-XXX] my subject`.
Use the more specialized type, BinaryType, in GeometryUDT for less overhead.
It seems that I stumbled upon the same flaky test as in https://github.com/apache/incubator-sedona/pull/733. I will rebase this patch when the other PR is merged.
All unit tests pass.

[SEDONA-205] Use BinaryType in GeometryUDT in Sedona Spark.

---

common/src/main/java/org/apache/sedona/common/geometrySerde/ByteBufferGeometryBuffer.java
common/src/main/java/org/apache/sedona/common/geometrySerde/CoordinateType.java
common/src/main/java/org/apache/sedona/common/geometrySerde/GeometryBuffer.java
common/src/main/java/org/apache/sedona/common/geometrySerde/GeometryBufferFactory.java
common/src/main/java/org/apache/sedona/common/geometrySerde/GeometrySerializer.java
common/src/main/java/org/apache/sedona/common/geometrySerde/UnsafeGeometryBuffer.java
common/src/test/java/org/apache/sedona/common/geometrySerde/GeometryBufferTest.java
common/src/test/java/org/apache/sedona/common/geometrySerde/GeometryCollectionSerdeTest.java
common/src/test/java/org/apache/sedona/common/geometrySerde/LineStringSerdeTest.java
common/src/test/java/org/apache/sedona/common/geometrySerde/MultiLineStringSerdeTest.java
common/src/test/java/org/apache/sedona/common/geometrySerde/MultiPointSerdeTest.java
common/src/test/java/org/apache/sedona/common/geometrySerde/MultiPolygonSerdeTest.java
common/src/test/java/org/apache/sedona/common/geometrySerde/PointSerdeTest.java
common/src/test/java/org/apache/sedona/common/geometrySerde/PolygonSerdeTest.java
core/src/main/java/org/apache/sedona/core/geometryObjects/GeometrySerde.java
python/sedona/sql/geometry_serde.py
python/sedona/sql/types.py
python/sedona/utils/geometry_serde.py
python/tests/serialization/test_deserializers.py
python/tests/utils/test_geometry_serde.py
sql/src/main/scala/org/apache/sedona/sql/utils/GeometrySerializer.scala
sql/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoDataSourceUtils.scala
sql/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetFileFormat.scala
sql/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetReadSupport.scala
sql/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetRowConverter.scala
sql/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetWriteSupport.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-207. The PR name follows the format `[SEDONA-XXX] my subject`.
The new geometry serde was implemented in `common/src/main/java/org/apache/sedona/common/geometrySerde/`. The ShapeSerde used by Kryo serializer and the WKB based serde used by `GeometryUDT` were replaced by this new serde. Please refer to [SEDONA-207](https://issues.apache.org/jira/browse/SEDONA-207) for a detailed explanation of this new geometry serde.
GeoParquet stores geometry objects as WKB binary values, which happens to be the old serialization format of …

[SEDONA-207] Implemented a new geometry serde for supporting Z/M dimensions and better performance

---

common/pom.xml
common/src/test/resources/log4j2.properties
core/pom.xml
core/src/test/resources/log4j2.properties
flink/pom.xml
flink/src/test/java/org/apache/sedona/flink/TestBase.java
flink/src/test/resources/log4j2.properties
pom.xml
python-adapter/pom.xml
python-adapter/src/test/resources/log4j2.properties
sql/pom.xml
sql/src/test/resources/log4j2.properties
viz/pom.xml
viz/src/test/resources/log4j2.properties

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-228. The PR name follows the format `[SEDONA-XXX] my subject`.
Standardize on using log4j 2 for logging. Currently the logging modules are pulled in from Spark to use log4j 1 or 2 depending on the Spark version. The common module and flink module have no logging available to it. Both Flink and Spark use Log4j 2.x in their latest versions.
Main points:
- Add `log4j-1.2-api` as a provided dependency for all modules. Currently all the logging uses the log4j 1.x API, so this makes that compatible while still being able to run log4j 2.x …

[SEDONA-228] Standardize logging modules

---

common/pom.xml
common/src/main/java/org/apache/sedona/common/Functions.java
common/src/main/java/org/apache/sedona/common/utils/GeomUtils.java
common/src/main/java/org/apache/sedona/common/utils/GeometrySplitter.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
sql/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-223. The PR name follows the format `[SEDONA-XXX] my subject`.
1. Add ST_Split function to sedona-common, sedona-sql, sedona-flink, and the dataframe/python API.
2. Created FunctionsTest.java to house tests for functions being added to sedona-common.
1. Comprehensive unit tests in sedona-common
2. Integration unit tests in sedona-sql, sedona-flink, and python.
- Yes, I have updated the documentation in docs/api/sql/Function.md.

[SEDONA-223] Add ST_Split

---

R/tests/testthat/helper-initialize.R
R/tests/testthat/test-data-interface.R
common/src/main/java/org/apache/sedona/common/utils/GeomUtils.java
core/src/main/java/org/apache/sedona/core/formatMapper/FormatUtils.java
core/src/main/java/org/apache/sedona/core/spatialRDD/SpatialRDD.java
core/src/test/java/org/apache/sedona/core/TestBase.java
core/src/test/java/org/apache/sedona/core/formatMapper/GeoJsonIOTest.java
core/src/test/java/org/apache/sedona/core/formatMapper/TestReadInvalidSyntaxGeometriesTest.java

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-230. The PR name follows the format `[SEDONA-230] my subject`.
1. SpatialRdd that has fields will be saved as a geojson that has correct property keys and values for each record.
2. Null field value will be saved as empty space. E.g.,
```
"properties": {"name": ""}
```
3. SpatialRdd that has no fields will be save as
```
"properties": null
```
One remaining issue is that numerical values in geojson will be converted to string type. To solve this, we need the full schema info preserved in SpatialRDD metadata. I will leave in this as the …

[SEDONA-230] rdd.saveAsGeoJSON should generate feature properties with field names

---

python/sedona/utils/geometry_serde.py
python/tests/utils/test_geometry_serde.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-227. The PR name follows the format `[SEDONA-XXX] my subject`.
A refactor of some of the python serialization/deserialization functions is proposed. This is due to the performance regression experienced from the change in serialization formats. Most of the functions were refactored to increase performance. Attempts were made to maintain readability of the code at the same time.
A significant pain point involves interacting with shapely geometry. Most of the shapely methods are too slow and involve repeated calls to native code. Once …

[SEDONA-227] Python Serde Refactor

---

.github/workflows/java.yml

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-232. The PR name follows the format `[SEDONA-XXX] my subject`.
Upgrade the patch version of Spark 3.2 used in CICD from 0 to 3 (3.2.0 to 3.2.3).
Existing unit tests pass.

[SEDONA-232] Upgrade CICD From Spark 3.2.0 to 3.2.3

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastIndexJoinExec.scala
sql/src/test/scala/org/apache/sedona/sql/BroadcastIndexJoinSuite.scala

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-221. The PR name follows the format `[SEDONA-XXX] my subject`.
This fixes the issues in broadcast left and anti joins with null geometries.
Rows are mapped to (Geometry, UnsafeRow) to allow rows with null geometries to be emitted.
Conditions for left and anti joins, where nulls can happen, checks for null.
This patch also adds a SQLMetric for number of output row visible in spark-ui. All native Spark join exec have them
Tests added

[SEDONA-221] Outer join throws NPE for null geometries.

---

python/tests/serialization/test_deserializers.py
python/tests/serialization/test_serializers.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-236. The PR name follows the format `[SEDONA-XXX] my subject`.
Fix test failures caused by converting pandas DataFrames containing lots of missing values to Spark DataFrames. We replaced missing values in the pandas DataFrame to get rid of this problem.
This patch was verified on an AWS EC2 instance where the problem could be constantly reproduced.

[SEDONA-236] Fix flaky python tests related to converting GeoPandas DataFrames to Spark DataFrames

---

sql/src/test/scala/org/apache/sedona/sql/ogc/GeometryTypesAndFunctionsTestScala.scala
sql/src/test/scala/org/apache/sedona/sql/ogc/package-info.java

- Yes, the URL of the assoicated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-179. The PR name follows the format `[SEDONA-179] my subject`.
The most relevant parts of OGC sfs tests for Geometry types and functions are implemented.
Findings: Two functions are not compliant plus some functions are not implemented in Sedona.
Tests for those are ignored with comments.
Test suite.

[SEDONA-179] Claim OGC compliance

---

docs/api/flink/Function.md
docs/api/sql/Function.md

- Yes, but both links in the "Yes" option are broken with 404 not found:
https://sedona.apache.org/community/rule/
https://sedona.apache.org/community/develop/
I think it should be https://sedona.apache.org/latest-snapshot/community/rule/ etc
Fixing some typos

[DOCS] fix spelling

---

.github/pull_request_template.md
README.md
docs/tutorial/rdd.md

Remove unneeded space from inside code span element
sedona % mdl -r MD038 docs
docs/tutorial/rdd.md:66: MD038 Spaces inside code span elements
https://github.com/markdownlint/markdownlint
https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md038---spaces-inside-code-span-elements
Mainly fixing links and general clean up
Spelling `assoicated ` -> `associated `
- …

[DOCS] Fix broken links, spelling and whitespace

---

docs/api/sql/Function.md
docs/api/sql/Raster-loader.md
docs/api/sql/Raster-operators.md
docs/api/viz/sql.md
docs/community/contributor.md
docs/community/publish.md
docs/community/rule.md
docs/community/vote.md
docs/setup/install-r.md
docs/setup/maven-coordinates.md
docs/setup/release-notes.md
docs/tutorial/core-python.md
docs/tutorial/flink/sql.md
docs/tutorial/rdd.md
docs/tutorial/sql-r.md
docs/tutorial/sql.md
docs/tutorial/viz.md
python/tests/core/test_rdd.py

Fix typos in Markdown.  One spelling fix in one Python file.

[DOCS] Fix spelling in Markdown and Python files

---

common/src/main/java/org/apache/sedona/common/geometrySerde/GeometrySerializer.java
common/src/test/java/org/apache/sedona/common/geometrySerde/GeometryCollectionSerdeTest.java
common/src/test/java/org/apache/sedona/common/geometrySerde/MultiLineStringSerdeTest.java
common/src/test/java/org/apache/sedona/common/geometrySerde/MultiPointSerdeTest.java
common/src/test/java/org/apache/sedona/common/geometrySerde/MultiPolygonSerdeTest.java
python/sedona/utils/geometry_serde.py
python/tests/utils/test_geometry_serde.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-207. The PR name follows the format `[SEDONA-XXX] my subject`.
This pull request fixes the handling of empty multi-geometries in the geometry serializer. In the current implementation, we omitted structure data for multi-geometries containing only empty geometries, such as `MULTILINESTRING (EMPTY, EMPTY)`. In this case, we cannot tell if it is an empty multi-geometry or multi-geometry containing only empty geometries. This patch fixes the problem by always writing structure data for multi geometries.
This …

[SEDONA-207] Fix ambiguity of empty multi-geometries and multi geometries containing only empty geometries

---

R/R/dependencies.R
R/tests/testthat/test-spatial-queries.R

Updating dependencies in R package
Ran R tests

[SEDONA-242] R: Update dependencies + fix failing test

---

.github/workflows/python-extension.yml
.github/workflows/python-wheel.yml
.github/workflows/python.yml
python/sedona/utils/geometry_serde.py
python/sedona/utils/geometry_serde_general.py
python/setup.py
python/src/geom_buf.c
python/src/geom_buf.h
python/src/geomserde.c
python/src/geomserde.h
python/src/geomserde_speedup_module.c
python/src/geos_c_dyn.c
python/src/geos_c_dyn.h
python/src/geos_c_dyn_funcs.h
python/src/pygeos/c_api.h
python/tests/utils/test_geometry_serde.py
python/tests/utils/test_geomserde_speedup.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/projects/SEDONA/issues/SEDONA-227. The PR name follows the format `[SEDONA-XXX] my subject`.
This patch provides a Python geometry serializer implemented as a native extension. The original pure python serializer was still kept around as a fallback implementation when the native extension failed to load.
Please be acknowledged that the existence of native extensions will complicate the release process of apache-sedona python packages, since we have to build wheels for various CPython versions and platforms. There is a …

[SEDONA-227] Implemented Python geometry serializer as a native extension

---

core/src/test/java/org/apache/sedona/core/utils/CRSTransformationTest.java
pom.xml

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-249. The PR name follows the format `[SEDONA-XXX] my subject`.
Add jvm flags to test plugins to make it possible to run tests on Java 17. This will make life easier for contributors running Java 17 locally.
This PR does not add Java 17 to the test matrix for github actions.
This PR does not make the tests pass on Java 17. Currently CRSTransformationTest.testPolygonDistanceJoinWithCRSTransformation in sedona-core fails on Java 17.
All tests pass on Java 8.
- No, this PR does not affect any public API so no …

[SEDONA-249] Add jvm flags for running tests on Java 17

---

pom.xml

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-253. The PR name follows the format `[SEDONA-XXX] my subject`.
Upgrade geotools to the latest version, 28.2.
There is also a PR for geotools-wrapper at: https://github.com/jiayuasu/geotools-wrapper/pull/3
All tests pass

[SEDONA-253] Upgrade geotools to version 28.2

---

.github/workflows/r.yml

https://issues.apache.org/jira/projects/SEDONA/issues/SEDONA-256
Update to the R testing workflow:
* Update to latest version of actions
* Replace steps with prepackaged actions: (R dependencies, R checks)
* Reorder to check R package before building Sedona
Removed cache steps (maven, R packages) already handled by prepackaged actions
Not yet updating to Ubuntu 22.04
On my fork
No, this PR does not affect any public API so no need to change the docs.

[SEDONA-256] R GitHub workflow update

---

scalastyle_config.xml

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-229.
This PR disables the scalastyle check called MultipleStringLiteralsChecker. This check is responsible for detecting multiple occurrences of the same string literal in the same file. From what I could gather, the reason for this check is to detect potential cases of "magic numbers" or constants that should be consolidated into a constant variable. There are three issues with this check:
- There is a bug in the check which flags fragments of interpolated strings as duplicates even though the string as …

[SEDONA-229] Remove Duplicate String Check

---

flink/src/main/java/org/apache/sedona/flink/expressions/Predicates.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-229. This PR only changes javadoc comments but it is a part of the linter clean up issue.
Just filled out the return tags for javadoc comments in Flink. These are the only linter warnings in the flink module, so that makes it officially cleaned up I guess.
Standard build process. There are no code changes in this PR.

[SEDONA-229] Fix Flink Return Tags

---

.github/workflows/docs.yml
.github/workflows/example.yml
.github/workflows/java.yml
.github/workflows/python.yml
.github/workflows/r.yml
python/tests/utils/test_crs_transformation.py

Upgrade the CI to use Ubuntu 22.04

[DOCS] Upgrade GitHub Action to Ubuntu 22.04

---

python-adapter/src/main/scala/org.apache.sedona.python.wrapper/translation/GeometryRddConverter.scala
python-adapter/src/main/scala/org.apache.sedona.python.wrapper/translation/PythonGeometrySerializer.scala
python-adapter/src/main/scala/org.apache.sedona.python.wrapper/translation/PythonRDDToJavaConverter.scala
python-adapter/src/test/scala/org/apache/sedona/python/wrapper/GeometrySample.scala
python-adapter/src/test/scala/org/apache/sedona/python/wrapper/TestToPythonSerialization.scala
python/tests/test_assign_raw_spatial_rdd.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-258. The PR name follows the format `[SEDONA-XXX] my subject`.
This PR fixes deserialization of `Circle` objects in python-adapter. It fixes problems such as not being able to assign to the `rawSpatialRDD` property of `CircleRDD` objects in Python binding, as well as other potential problems with Circle RDD.
Added tests in both python-adapter and python module.

[SEDONA-258] Fix deserialization of Circle objects in python-adapter

---

python-adapter/src/main/scala/org.apache.sedona.python.wrapper/utils/PythonAdapterWrapper.scala
python/sedona/utils/adapter.py
python/tests/sql/test_adapter.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-259. The PR name follows the format `[SEDONA-XXX] my subject`.
Added a proper implementation of `sedona.utils.Adapter.toSpatialRdd` to produce spatial RDDs with custom field names for user data.
Added tests for this use case.

[SEDONA-259] Properly implement Adapter.toSpatialRdd to support custom field names for user data

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastIndexJoinExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
sql/src/test/scala/org/apache/sedona/sql/SpatialJoinSuite.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-261. The PR name follows the format `[SEDONA-XXX] my subject`.
BroadcastIndexJoinExec cannot run distance joins when the distance expression references attribute from the right-side relation, this patch fixed this problem.
Added new distance join tests where the distance expressions are not constant expressions.

[SEDONA-261] Allow distance expression in distance join to reference attributes from the right-side relation when running broadcast join.

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastIndexJoinExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/DistanceJoinExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/RangeJoinExec.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryBase.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryExec.scala
sql/src/test/scala/org/apache/sedona/sql/SpatialJoinSuite.scala

This patch depends on https://github.com/apache/sedona/pull/796.
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-260. The PR name follows the format `[SEDONA-XXX] my subject`.
Do not automatically swap the left and right relations when doing spatial joins, since it may cause confusion when the user wants to configure the partition and index-build side of the join.
Tested using existing tests in SpatialJoinSuite.

[SEDONA-260] Don't swap the left and right relations of spatial joins

---

core/src/main/java/org/apache/sedona/core/enums/SpatialJoinOptimizationMode.java
core/src/main/java/org/apache/sedona/core/utils/SedonaConf.java
docs/api/sql/Parameter.md
sql/src/main/scala/org/apache/spark/sql/sedona_sql/optimization/ExpressionUtils.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/optimization/SpatialFilterPushDownForGeoParquet.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
sql/src/test/scala/org/apache/sedona/sql/SpatialJoinSuite.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-262. The PR name follows the format `[SEDONA-XXX] my subject`.
This patch disabled Sedona spatial join optimizations on equi-joins by default. User can still switch to the old behavior with `spark.conf.set("sedona.join.optimizationmode", "all")`. Please refer to the JIRA ticket for details about this patch.
Added tests with various `"sedona.join.optimizationmode"` options and verified that join queries are producing expected executed plans.

[SEDONA-262] Don't optimize equi-join by default, add an option to configure when to optimize spatial joins

---

zeppelin/index.js

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-264. 

[SEDONA-264] zeppelin helium plugin supports drawing geometry like linestring, polygon

---

R/DESCRIPTION
R/R/dependencies.R

Draft PR until this is ready to be submitted to CRAN
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-263. The PR name follows the format `[SEDONA-XXX] my subject`.
Prepare R package for 1.4.0 release:
* Update maven coordinates to 1.4.0
* Update version of R package to 1.4.0
No changes to tested features

[SEDONA-263] R – Prepare for 1.4.0 release

---

.github/workflows/python-extension.yml
python/MANIFEST.in

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-267. The PR name follows the format `[SEDONA-XXX] my subject`.
Added header files to the source distribution package by adding a MANIFEST.in file, following the practice recommended by https://github.com/pypa/packaging-problems/issues/84.
We've added a step to install apache-sedona from source distribution package.

[SEDONA-267] Fix missing header files in the python sdist package

---

.github/workflows/python-wheel.yml

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-227. The PR name follows the format `[SEDONA-XXX] my subject`.
Build python wheels for ARM64.
Tested manually by installing the wheels on Linux aarch64 and macOS arm64. Windows ARM64 was left untested.

[SEDONA-227] Enable building python wheels for ARM64

---

sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/Constructors.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/implicits.scala
sql/src/test/scala/org/apache/sedona/sql/serdeAwareTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-270. The PR name follows the format `[SEDONA-XXX] my subject`.
Just like in SEDONA-231 we can remove redundant serde for chained raster functions.
Unit test added

[SEDONA-270] Remove redundant serialization for rasters

---

common/src/main/java/org/apache/sedona/common/raster/Functions.java
common/src/test/java/org/apache/sedona/common/raster/ConstructorsTest.java
common/src/test/java/org/apache/sedona/common/raster/FunctionsTest.java
docs/api/sql/Raster-operators.md
sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/Functions.scala
sql/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-271. The PR name follows the format `[SEDONA-XXX] my subject`.
Add raster function RS_SRID

[SEDONA-271] Add raster function RS_SRID

---

python/.gitignore
python/README.md

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-167. The PR name follows the format `[SEDONA-XXX] my subject`.
In the ticket user asked to add `__pycache__` to `.gitignore`. This PR adds this.
I also added link to docs about setting up python dev env.
No testing required.

[SEDONA-167] Add pycache to gitignore

---

python/Pipfile

Limit 3 Python dependencies to the versions that work for Python 3.7, 3.8 and 3.9. Note: this only affects people who want to do Sedona Dataframe toPandas or pandas to Sedona DataFrame
If you are using Python ==3.7:
Shapely <= 1.8.5.post1
Pandas <= 1.3.5
GeoPandas <= 0.10.2
If you are using Python >=3.8:
Shapely <=1.8.5.post1
Pandas <= 1.5.3
GeoPandas <= 0.11.1
Passed CI …

[SEDONA-273] Explicitly bound Pandas, GeoPandas and Shapely versions

---

common/src/main/java/org/apache/sedona/common/raster/Functions.java
common/src/test/java/org/apache/sedona/common/raster/FunctionsTest.java
docs/api/sql/Raster-operators.md
sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/Functions.scala
sql/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-275. The PR name follows the format `[SEDONA-XXX] my subject`.
Add RS_SetSRID - the raster version of ST_SetSRID
Tests added

[SEDONA-275] Add raster function RS_SetSRID

---

common/src/main/java/org/apache/sedona/common/Constructors.java
common/src/main/java/org/apache/sedona/common/Functions.java
common/src/main/java/org/apache/sedona/common/Predicates.java
common/src/main/java/org/apache/sedona/common/utils/GeoHashDecoder.java
sql/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Constructors.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/NullSafeExpressions.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Predicates.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/implicits.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_constructors.scala
sql/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-274 The PR name follows the format `[SEDONA-XXX] my subject`.
Transplant all the sql st funcions' implementation to sedona-common to allow added to flink and other computation engines.
Migrate the expressions to inferred typed expressions. Except following
- ST_SubDivideExplode    <==    explode method 1 -> N
- ST_MinimumBoundingRadius    <==    result in 2 columns
- St_geomfromwkb    <==    accept 2 types of argument, require overloading
- Predicates    <==    spatial join detector requires …

[SEDONA-265] Migrate all ST functions to Sedona Inferred Expressions

---

docs/tutorial/raster.md
docs/tutorial/storing-blobs-in-parquet.md
mkdocs.yml

I had a parquet file with rasters that took 30 minutes to read. After som tuning I got it down to 2 seconds. This is what I learned.
- This is a documentation update.

[DOCS] Document tuning Spark for writing large raster geometries to Parquet

---

flink-shaded/pom.xml
pom.xml
spark-shaded/pom.xml

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-284. The PR name follows the format `[SEDONA-284] my subject`.
The POMs of shaded modules (`sedona-spark-shaded`, `sedona-flink-shaded`) were not correctly generated, they still have variables in artifact IDs. This patch solves this problem by upgrading the maven-shade-plugin from 2.1 to the latest 3.4.1.
Manually running `mvn clean deploy -DskipTests` to deploy the artifacts to a private repository, and verify that the POMs of shaded modules are correct.
- No, this PR does not affect any public API so no …

[SEDONA-284] Substitute property values in dependency-reduced-pom.xml for shaded submodules

---

common/src/main/java/org/apache/sedona/common/sphere/Haversine.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
sql/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
sql/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

To be consistent with PostGIS, change the default radius in ST_DistanceSphere to 6371008
Fix unit tests

[SEDONA-281] Change ST_DistanceSphere default radius to 6371008

---

docs/api/sql/Function.md
docs/api/sql/Optimizer.md
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/DistanceJoinExec.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/SpatialIndexExec.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryBase.scala
sql/common/src/test/scala/org/apache/sedona/sql/BroadcastIndexJoinSuite.scala
sql/common/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala
sql/common/src/test/scala/org/apache/sedona/sql/predicateJoinTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-286. The PR name follows the format `[SEDONA-286] my subject`.
1. Added patterns for ST_DistanceSpheroid and ST_DistanceSphere based join
2. Expand buffer area by following the formula provided by Kristin:
$$
\begin{align*}
\Delta \textrm{lat} &= \frac{D}{R} \\
\Delta \textrm{lon} &= \max (\frac{D}{R \cos(\textrm{lat} + \Delta \textrm{lat})}, \frac{D}{R \cos(\textrm{lat} - \Delta \textrm{lat})})
\end{align*}
$$
where $\textrm{lat}$, $\textrm{lon}$ is the center of the envelope; $R$ is the mean radius of …

[SEDONA-286] Support optimized distance join on ST_DistanceSphere and ST_DistanceSpheroid

---

core/src/main/java/org/apache/sedona/core/joinJudgement/DynamicIndexLookupJudgement.java
core/src/main/java/org/apache/sedona/core/joinJudgement/JudgementBase.java
core/src/main/java/org/apache/sedona/core/joinJudgement/LeftIndexLookupJudgement.java
core/src/main/java/org/apache/sedona/core/joinJudgement/NestedLoopJudgement.java
core/src/main/java/org/apache/sedona/core/joinJudgement/RightIndexLookupJudgement.java
core/src/main/java/org/apache/sedona/core/spatialOperator/JoinQuery.java

Make `populateNextBatch` as a shared function in `JudgementBase` so all other Judgement can leverage it to build the iterators.
Passed existing test cases.

[SEDONA-290] RDD Spatial Joins should follow the iterator model

---

docs/setup/compile.md
mkdocs.yml

- This PR includes updates to the compilation process of sedona.
- This PR also removes prebuild_index config from mkdocs.yml since its support has been removed in newer versions of mkdocs.
- This patch was tested by compiling the documentation and verifying intended updates.

[DOCS] Compilation process updates

---

R/DESCRIPTION
R/R/dependencies.R
core/pom.xml
docs/community/publish.md
docs/community/snapshot.md
docs/setup/release-notes.md
flink/pom.xml
mkdocs.yml
pom.xml
python/sedona/version.py
sql/pom.xml
sql/spark-3.0/pom.xml
sql/spark-3.4/pom.xml
viz/pom.xml
zeppelin/package.json

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-306. The PR name follows the format `[SEDONA-XXX] my subject`.
Due to the changes made to the project structure since Sedona 1.4.0, the release process of Sedona 1.4.1 changed a lot. We'll update the docs and address all the issues introduced to the release process. Notable changes are:
1. Added an `enable-all-submodules` profile for `release:prepare` to substitute versions of all submodules.
2. Don't generate and publish scala docs when building `sedona-core`, `sedona-viz` and `sedona-flink`. We'll …

[SEDONA-306] Prepare release 1.4.1

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
docs/community/publish.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
sql/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
sql/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-237. The PR name follows the format `[SEDONA-XXX] my subject`.
Add ST_Dimension function to [sedona-common](https://issues.apache.org/jira/browse/SEDONA-common), [sedona-sql](https://issues.apache.org/jira/browse/SEDONA-sql), [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink), and the dataframe/python API.
2. Integration unit tests in …

[SEDONA-237] Add ST_Dimension

---

common/src/main/java/org/apache/sedona/common/Functions.java
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/InferredExpression.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-311. The PR name follows the format `[SEDONA-XXX] my subject`.
Support wrapping overloaded functions as catalyst expressions. This makes implementing UDFs with multiple variants much easier.
Passing existing unit tests.

[SEDONA-311] Support overloaded functions in InferredExpression

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/main/java/org/apache/sedona/common/utils/GeomUtils.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
sql/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
sql/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-238. The PR name follows the format `[SEDONA-XXX] my subject`.
Add ST_Dimension function to [sedona-common](https://issues.apache.org/jira/browse/SEDONA-common), [sedona-sql](https://issues.apache.org/jira/browse/SEDONA-sql), [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink), and the dataframe/python API.
2. Integration unit tests in …

[SEDONA-238] Implement OGC GeometryType

---

docs/api/flink/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-303. The PR name follows the format `[SEDONA-XXX] my subject`.
Port missing ST_functions including {ST_Centroid, ST_CollectionExtract, ST_ConvexHull, ST_Difference, ST_Dump} to [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink).
1. Integration unit tests in [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink).

[SEDONA-303] Port all Sedona Spark functions to Sedona Flink -- Step 1

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
python/tests/sql/test_function.py
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
sql/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
sql/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-298. The PR name follows the format `[SEDONA-XXX] my subject`.
Add ST_ClosestPointfunction to [sedona-common](https://issues.apache.org/jira/browse/SEDONA-common), [sedona-sql](https://issues.apache.org/jira/browse/SEDONA-sql), [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink), and the dataframe/python API.
2. Integration unit tests in …

[SEDONA-298] Implement ST_ClosestPoint

---

common/src/main/java/org/apache/sedona/common/raster/DeepCopiedRenderedImage.java
common/src/main/java/org/apache/sedona/common/raster/Serde.java
common/src/test/java/org/apache/sedona/common/raster/SerdeTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-318. The PR name follows the format `[SEDONA-XXX] my subject`.
We've implemented our own serializable rendered image named `DeepCopiedRenderedImage`. This class mimics the behavior of the deep copy mode of `SerializableRenderedImage`, and does not have the bugs mentioned in the ticket.
Added new tests to SerdeTest.

[SEDONA-318] Switch raster serde to a deep copy implementation

---

common/src/main/java/org/apache/sedona/common/raster/RasterPredicates.java
common/src/test/java/org/apache/sedona/common/raster/RasterPredicatesTest.java
common/src/test/java/org/apache/sedona/common/raster/RasterTestBase.java
docs/api/sql/Raster-operators.md
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterPredicates.scala
sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-321. The PR name follows the format `[SEDONA-XXX] my subject`.
Added a function `RS_Intersects(rast, geom)` for testing if the envelope of `rast` intersects with `geom`. This function performs implicit CRS transformations before the intersection testing.
Added new test cases.

[SEDONA-321] Implement RS_Intersects(rast, geom)

---

.github/workflows/java.yml
.github/workflows/python.yml
.github/workflows/r.yml

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-322. The PR name follows the format `[SEDONA-XXX] my subject`.
The CI for Scala/Java build fails frequently. The failure was triggered by a failed maven artifact download:
```
Error:  Plugin org.apache.maven.plugins:maven-shade-plugin:3.4.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-shade-plugin:jar:3.4.1: Could not transfer artifact org.apache.maven.plugins:maven-shade-plugin:pom:3.4.1 from/to central …
```

[SEDONA-322] Fix unstable maven build on GitHub Actions

---

common/src/main/java/org/apache/sedona/common/raster/MapAlgebra.java
sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-319. The PR name follows the format `[SEDONA-XXX] my subject`.
Manually construct the `BufferedImage` object with a serializable color model when building the resulting GridCoverage2D object, so that the resulting raster could be successfully serialized.
Added a new test case for it.

[SEDONA-319] Make result of RS_BandAsArray serializable

---

docs/api/flink/Constructor.md
docs/api/flink/Predicate.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Constructors.java
flink/src/main/java/org/apache/sedona/flink/expressions/Predicates.java
flink/src/test/java/org/apache/sedona/flink/ConstructorTest.java
flink/src/test/java/org/apache/sedona/flink/PredicateTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-303. The PR name follows the format `[SEDONA-XXX] my subject`.
Port missing Predicates including 
{ST_Crosses
ST_Equals
ST_Touches
ST_Overlaps} and Contructor {ST_PointZ}
to [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink).
1. Integration unit tests in [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink).

[SEDONA-303] Port all Sedona Spark functions to Sedona Flink -- Step 7

---

common/src/main/java/org/apache/sedona/common/raster/RasterConstructors.java
common/src/main/java/org/apache/sedona/common/raster/inputstream/ByteArrayImageInputStream.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-325. The PR name follows the format `[SEDONA-XXX] my subject`.
We've implemented an `ImageInputStream` backed by byte-array, which prevents GeoTiffReader from wrapping the input `InputStream` with a file-backed cached input stream. Now the GridCoverage2D will be entirely backed by memory blobs and no file-io should be involved.
We may also need to `dispose` the GridCoverage2D object after usage, though now this `dispose` call become optional. We'll add raster support to `InferredExpression` so that we can …

[SEDONA-325] Fix resource leaks in raster constructors RS_FromGeoTiff and RS_FromArcInfoAsciiGrid

---

docs/api/flink/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-303. The PR name follows the format `[SEDONA-XXX] my subject`.
Port missing ST_functions including 
{ST_Collect}
to [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink).
1. Integration unit tests in [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink).

[SEDONA-303] Port all Sedona Spark function to Sedona Flink -- ST_Collect

---

sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-313. The PR name follows the format `[SEDONA-XXX] my subject`.
A redundant UDF catalog entry for `ST_Affine` was removed.
Passed existing tests.

[SEDONA-313] Remove redundant ST_Affine entry from the Spark SQL catalog

---

common/src/main/java/org/apache/sedona/common/raster/DeepCopiedRenderedImage.java
common/src/main/java/org/apache/sedona/common/raster/Serde.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-318. The PR name follows the format `[SEDONA-XXX] my subject`.
The current implementation of the GridCoverage2D serializer calls the `getData` method of the rendered image to obtain serializable raster data. When the rendered image object is a `BufferedImage`, it will create a hard copy of the underlying raster, which is very time-consuming. This happens when serializing rasters created by `RS_MakeEmptyRaster` or `RS_AddBandFromArray`.
This patch adds a fast path for GridCoverage2D objects backed by a …

[SEDONA-318] Avoid creating an unnecessary copy of raster data when serializing rasters backed by BufferedImage

---

docs/api/flink/Aggregator.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Aggregators.java
flink/src/test/java/org/apache/sedona/flink/AggregatorTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-303. The PR name follows the format `[SEDONA-XXX] my subject`.
Port missing aggregation including 
{ST_Intersection_Aggr}
to [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink).
1. Integration unit tests in [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink).

[SEDONA-303] Port all Sedona Spark function to Sedona Flink -- ST_Intersection_Aggr

---

.github/workflows/r.yml
R/.Rbuildignore
R/tests/testthat/test-dbplyr-integration.R

https://issues.apache.org/jira/browse/SEDONA-324
Fixing the tests by removing the unneeded workaround
By running the tests

[SEDONA-324] R fix tests

---

common/src/main/java/org/apache/sedona/common/raster/RasterConstructors.java
common/src/main/java/org/apache/sedona/common/raster/RasterOutputs.java
python-adapter/pom.xml
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/InferredExpression.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/MapAlgebra.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/PixelFunctions.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterAccessors.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterConstructors.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterEditors.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterOutputs.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterPredicates.scala
viz/pom.xml

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-327. The PR name follows the format `[SEDONA-XXX] my subject`.
Added support for `GridCoverage2D` to `InferredExpression`, and refactored many raster functions to extend `InferredExpression`.
Please note that this patch will make `gt-coverage` a mandatory dependency.
Passing existing tests.

[SEDONA-327] Refactored raster UDFs to extend InferredExpression

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
sql/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
sql/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-293. The PR name follows the format `[SEDONA-XXX] my subject`.
- I implemented the ST_IsCollection function.
- In my local Ubuntu VM environment.
- Yes, I have added the necessary information to the readmes.

[SEDONA-293] Implement ST_IsCollection

---

docs/api/flink/Function.md
docs/api/sql/Function.md

The following functions' docs were edited both in Spark and Flink:
ST_3DDistance, ST_Area, ST_AreaSpheroid, ST_AsBinary, ST_AsEWKB, ST_EWKT, ST_GeoJSON, ST_AsGML, ST_KML and ST_AsText.
On my local Ubuntu VM machine.

[DOCS] Add example outputs to all Sedona functions

---

docs/api/flink/Function.md
docs/api/sql/Function.md

The following functions' docs were edited both in Spark and Flink:
ST_InteriorRingN, ST_Intersection, ST_IsClosed, ST_IsCollection, ST_IsEmpty, ST_IsRing, ST_IsSimple, ST_IsValid, ST_Length, ST_LengthSpheroid, ST_LineFromMultiPoint, and ST_LineInterpolatePoint.
On my local Ubuntu VM.

[DOCS] Add example outputs to all Sedona functions - 4

---

common/src/main/java/org/apache/sedona/common/raster/PixelFunctions.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-332. The PR name follows the format `[SEDONA-XXX] my subject`.
We make RS_Values only fetch relevant tiles instead of fetching the entire raster.
https://github.com/apache/sedona/issues/926 may relate to this problem.
Passed existing unit tests.

[SEDONA-332] Make RS_Values only fetch relevant tiles, instead of fetching the entire raster

---

common/src/main/java/org/apache/sedona/common/raster/RasterAccessors.java
common/src/test/java/org/apache/sedona/common/raster/RasterAccessorsTest.java
docs/api/sql/Raster-operators.md
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterAccessors.scala
sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-334. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add RS_ScaleX and RS_ScaleY
- Wrote new tests

[SEDONA-334] Add RS_ScaleX and RS_ScaleY

---

python/sedona/utils/geometry_serde.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-337. 
Adjusted python module import for geometry fallback implementation
After changing the import the module can now be located.

[SEDONA-337] adjusted python module import for geometry fallback implementation

---

common/src/main/java/org/apache/sedona/common/Constructors.java
common/src/test/java/org/apache/sedona/common/ConstructorsTest.java
docs/api/flink/Constructor.md
docs/api/sql/Constructor.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Constructors.java
flink/src/test/java/org/apache/sedona/flink/ConstructorTest.java
python/sedona/sql/st_constructors.py
python/tests/sql/test_constructor_test.py
python/tests/sql/test_dataframe_api.py
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Constructors.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_constructors.scala
sql/common/src/test/scala/org/apache/sedona/sql/constructorTestScala.scala
sql/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-298. The PR name follows the format `[SEDONA-XXX] my subject`.
Add ST_GeomFromEWKTto [sedona-common](https://issues.apache.org/jira/browse/SEDONA-common), [sedona-sql](https://issues.apache.org/jira/browse/SEDONA-sql), [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink), and the dataframe/python API.
2. Integration unit tests in [sedona-sql](https://issues.apache.org/jira/browse/SEDONA-sql), …

[SEDONA-333] Implement ST_GeomFromEWKT

---

common/src/main/java/org/apache/sedona/common/raster/MapAlgebra.java
common/src/main/java/org/apache/sedona/common/raster/RasterAccessors.java
common/src/main/java/org/apache/sedona/common/raster/RasterConstructors.java
common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java
common/src/test/java/org/apache/sedona/common/raster/RasterAccessorsTest.java
common/src/test/java/org/apache/sedona/common/raster/RasterConstructorsTest.java
docs/api/sql/Raster-loader.md
docs/api/sql/Raster-operators.md
sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-338. The PR name follows the format `[SEDONA-XXX] my subject`.
1. Make `RS_MakeEmptyRaster` work correctly by constructing the GridCoverage2D object directly from the affine transformation. Please refer to [SEDONA-338](https://issues.apache.org/jira/browse/SEDONA-338) for details.
2. Grid coordinates are consistently treated as the upper-left corner of the grid cells. This behavior follows the GDAL/PostGIS convention.
Add unit tests for geo-referencing related functions.
- Yes, I have updated the …

[SEDONA-338] Fix `RS_MakeEmptyRaster` and make affine transformation parameters compliant with the GDAL/PostGIS convention

---

common/src/main/java/org/apache/sedona/common/raster/GeometryFunctions.java
common/src/main/java/org/apache/sedona/common/raster/RasterAccessors.java
common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java
common/src/test/java/org/apache/sedona/common/raster/FunctionsTest.java
common/src/test/java/org/apache/sedona/common/raster/GeometryFunctionsTest.java
common/src/test/java/org/apache/sedona/common/raster/RasterAccessorsTest.java
common/src/test/java/org/apache/sedona/common/raster/RasterConstructorsTest.java
docs/api/sql/Raster-operators.md
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/GeometryFunctions.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterAccessors.scala
sql/common/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala
sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-340 and https://issues.apache.org/jira/browse/SEDONA-341. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add RS_ConvexHull
- Move RS_Envelope to Geometry Functions
- Added new tests
- Verified existing tests
- Compiled documentation

[SEDONA-340] Add RS_ConvexHull | [SEDONA-341] Move RS_Envelope to Geometry Functions

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
python/tests/sql/test_function.py
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
sql/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
sql/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-114. The PR name follows the format `[SEDONA-XXX] my subject`.
Add ST_MakeLineto [sedona-common](https://issues.apache.org/jira/browse/SEDONA-common), [sedona-sql](https://issues.apache.org/jira/browse/SEDONA-sql), [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink), and the dataframe/python API.
2. Integration unit tests in [sedona-sql](https://issues.apache.org/jira/browse/SEDONA-sql), …

[SEDONA-114] Implement ST_MakeLine

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
python/tests/sql/test_function.py
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
sql/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
sql/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket will be https://issues.apache.org/jira/browse/SEDONA-342. The PR name follows the format `[SEDONA-XXX] my subject`.
Add ST_Polygon to [sedona-common](https://issues.apache.org/jira/browse/SEDONA-common), [sedona-sql](https://issues.apache.org/jira/browse/SEDONA-sql), [sedona-flink](https://issues.apache.org/jira/browse/SEDONA-flink), and the dataframe/python API.
2. Integration unit tests in [sedona-sql](https://issues.apache.org/jira/browse/SEDONA-sql), …

[SEDONA-342] Implement ST_Polygon

---

common/src/main/java/org/apache/sedona/common/raster/RasterPredicates.java
common/src/test/java/org/apache/sedona/common/raster/RasterPredicatesTest.java
common/src/test/java/org/apache/sedona/common/raster/RasterTestBase.java
docs/api/sql/Raster-operators.md
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterPredicates.scala
sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-343. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add RS_Contains
- Add RS_Within
- Added new tests

[SEDONA-343] Add RS_Contains and RS_Within

---

common/src/main/java/org/apache/sedona/common/raster/RasterEditors.java
common/src/test/java/org/apache/sedona/common/raster/FunctionsTest.java
sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-338. The PR name follows the format `[SEDONA-XXX] my subject`.
Use the original geo-referencing information to construct rasters with new SRIDs, instead of using referenced envelopes to construct new rasters.
Add assertions for geo-referencing data of result rasters.

[SEDONA-338] Don't change the geo-referencing data when setting the SRID of rasters.

---

common/src/main/java/org/apache/sedona/common/utils/GeomUtils.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java

- Yes, the URL of the associated JIRA ticket will be https://issues.apache.org/jira/browse/SEDONA-348. The PR name follows the format `[SEDONA-XXX] my subject`.
GetDimension will support 2D and 3D, which will lead functions like ST_AsWKT ignore the M coordinate. After this PR is merged, M coordinate will be available in WKT format.
In short, current status of Sedona Input and Output ST functions are follows:
1. ST_AsEWKT: SRID + XYZM WKT
2. ST_AsText: XYZM WKT
3. ST_GeomFromWKT: accepts EWKT and WKT format, with XYZM
4. ST_GeomFromWKB: accepts EWKB format, with XYZM but M is ignored.
5. ST_AsWKB …

[SEDONA-351] Support XYZM coordinate

---

common/src/main/java/org/apache/sedona/common/raster/RasterConstructors.java
common/src/test/java/org/apache/sedona/common/raster/RasterConstructorsTest.java
docs/api/sql/Raster-loader.md
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterConstructors.scala
sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-193. The PR name follows the format `[SEDONA-XXX] my subject`.
- Refactor RS_MakeEmptyRaster to allow setting a custom datatype for the raster. Currently, all rasters created have double value.
- This PR allows setting 1 datatype out of (Double, Float, int32, short16, usigned_short16, and byte) for all current (and future) bands of the raster. Making a raster with different datatypes for all the bands is not supported, due to our usage of WritableRaster.
- Added additional tests
- Yes, I am adding a new …

[SEDONA-193] Refactor MakeEmptyRaster to allow setting custom datatype

---

common/src/test/java/org/apache/sedona/common/raster/RasterAccessorsTest.java
docs/api/sql/Raster-operators.md
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterAccessors.scala
sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-354. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add RS_SkewX and RS_SkewY
- Add new tests (java and spark sql)

[SEDONA-354] Add RS_SkewX and RS_SkewY

---

common/src/main/java/org/apache/sedona/common/raster/MapAlgebra.java
common/src/main/java/org/apache/sedona/common/raster/PixelFunctions.java
common/src/main/java/org/apache/sedona/common/raster/RasterBandAccessors.java
common/src/main/java/org/apache/sedona/common/raster/RasterConstructors.java
common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java
common/src/test/java/org/apache/sedona/common/raster/MapAlgebraTest.java
common/src/test/java/org/apache/sedona/common/raster/RasterConstructorsTest.java
common/src/test/java/org/apache/sedona/common/utils/RasterUtilsTest.java
sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-360. The PR name follows the format `[SEDONA-XXX] my subject`.
Added a utility function `RasterUtils.getNoDataValue` for retrieving the nodata value of a band using a more concise method: we only treat the values of NODATA categories as nodata values.
Add unit tests and replaced all calls to `GridSampleDimension#getNoDataValue` with `RasterUtils.getNoDataValue` in existing tests.

[SEDONA-360] Handle nodata values of raster bands in a more concise way

---

common/pom.xml
common/src/main/java/org/apache/sedona/common/raster/RasterAccessors.java
common/src/main/java/org/apache/sedona/common/raster/RasterPredicates.java
common/src/main/java/org/apache/sedona/common/utils/GeomUtils.java
common/src/test/java/org/apache/sedona/common/raster/RasterPredicatesTest.java
docs/api/sql/Raster-operators.md
pom.xml
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterPredicates.scala
sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-374. The PR name follows the format `[SEDONA-XXX] my subject`.
1. RS functions can take (geom, rast) and (rast, rast) as arguments.
1. Use convex hull of rasters for spatial relationship testing.
2. If either side of the RS predicate does not have defined its CRS, we treat them as in WGS84.
3. Transform both sides to a common CRS (WGS84) if the left and right side does not have the same CRS.
Add unit tests

[SEDONA-374] Add support for geom-raster and raster-raster relationship to RS predicates 

---

common/src/main/java/org/apache/sedona/common/sphere/Haversine.java
common/src/main/java/org/apache/sedona/common/sphere/Spheroid.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinedGeometry.scala
sql/common/src/test/scala/org/apache/sedona/sql/BroadcastIndexJoinSuite.scala
sql/common/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala
sql/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
sql/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
sql/common/src/test/scala/org/apache/sedona/sql/predicateJoinTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-377. The PR name follows the format `[SEDONA-XXX] my subject`.
This PR changes the following functions to accept geometries with WGS84 coordinates in lon/lat order:
* ST_DistanceSphere
* ST_DistanceSpheroid
* ST_AreaSpheroid
* ST_LengthSpheroid
Changed existing unit tests

[SEDONA-377] Sphere/Spheroid functions accepts geometries in lon/lat order 

---

common/src/main/java/org/apache/sedona/common/sphere/Haversine.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
common/src/test/java/org/apache/sedona/common/sphere/HaversineEnvelopeTest.java
docs/api/sql/Optimizer.md
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinedGeometry.scala
sql/common/src/test/scala/org/apache/sedona/sql/BroadcastIndexJoinSuite.scala
sql/common/src/test/scala/org/apache/sedona/sql/SphereDistanceJoinSuite.scala
sql/common/src/test/scala/org/apache/sedona/sql/predicateJoinTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-286. The PR name follows the format `[SEDONA-XXX] my subject`.
We generate anti-meridian-and-pole-aware envelopes for geometries when performing sphere/spheroid distance join.
If the join predicate `ST_DistanceSphere` has a custom radius (`ST_DistanceSphere(geom1, geom2, radius)`), then the join won't be optimized.
* Added tests for the function for generating anti-meridian-and-pole-aware envelopes.
* Added `SphereDistanceJoinSuite` to test sphere/spheroid distance join on geometries scattered on the …

[SEDONA-286] Correctly handle poles and anti-meridian in optimized sphere/spheroid distance join

---

common/src/test/java/org/apache/sedona/common/raster/RasterOutputTest.java
docs/api/sql/Raster-writer.md
sql/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
sql/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterOutputs.scala
sql/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

1. Rename the function to RS_AsBase64
2. Fix the wrong name of RasterOutputTests. This stopped JUnit from picking up the tests when run with `mvn install`
3. Use another image for the test as sometimes (for some images) Java8 and Java11 produce different base64 strings given the same input image.
4. Improve the documentation to explain how this function works. In particular, this function only visualizes the first 4 bands regardless how many …

[SEDONA-379] Fix bugs in RS_AsBase64

---

common/src/main/java/org/apache/sedona/common/raster/RasterBandAccessors.java
common/src/test/java/org/apache/sedona/common/raster/RasterBandAccessorsTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/InferredExpression.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterBandAccessors.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-383. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add RS_Band
- Passed added tests

[SEDONA-383] Add RS_Band

---

common/src/main/java/org/apache/sedona/common/raster/DeepCopiedRenderedImage.java
common/src/main/java/org/apache/sedona/common/raster/MapAlgebra.java
common/src/main/java/org/apache/sedona/common/raster/PixelFunctionEditors.java
common/src/main/java/org/apache/sedona/common/raster/RasterBandAccessors.java
common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-361. The PR name follows the format `[SEDONA-XXX] my subject`.
We've spotted several performance hits of map algebra functions:
1. `ImageUtils.createConstantImage` is very slow, we'd better manually create a buffered image, which is way faster.
2. The `.getData()` method on `BufferedImage` objects creates an unnecessary copy of the raster object. We've added a utility function to implement a fast path for `BufferedImage`.
Passing existing tests
- No, this PR does not affect any public API so no need to …

[SEDONA-361] Fix performance issues of map algebra functions and some band operators

---

common/src/main/java/org/apache/sedona/common/raster/RasterBandAccessors.java
common/src/test/java/org/apache/sedona/common/raster/RasterBandAccessorsTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterBandAccessors.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-387. The PR name follows the format `[SEDONA-XXX] my subject`.
Added `RS_BandIsNoData` for testing if all pixels in a band are nodata values. This is basically a more simple version of `RS_SummaryStats`.
Passing newly added tests.

[SEDONA-387] Implement RS_BandIsNoData

---

.github/workflows/python-extension.yml
.github/workflows/python.yml

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-389. The PR name follows the format `[SEDONA-XXX] my subject`.
Please refer to https://github.com/pypa/pipenv/issues/5924 for details. We'll temporarily pin the version of pipenv to 2023.9.1 to resolve this issue.
Passing CI.

[SEDONA-389] Pin pipenv version to 2023.9.1, since 2023.9.7 introduces a bug that broke our build

---

.github/workflows/lint.yml
.pre-commit-config.yaml
binder/Sedona_OvertureMaps_GeoParquet.ipynb
codespell.txt
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
common/src/test/java/org/apache/sedona/common/utils/RasterUtilsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
docs/setup/release-notes.md
docs/tutorial/rdd.md
docs/tutorial/sql.md
flink-shaded/pom.xml
python/sedona/sql/st_functions.py
spark-shaded/pom.xml
spark/common/src/main/java/org/apache/sedona/core/formatMapper/shapefileParser/parseUtils/shp/ShapeSerde.java
spark/common/src/main/java/org/apache/sedona/core/spatialPartitioning/quadtree/StandardQuadTree.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-390. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add `pre-commit` with GitHub Actions
- Setup pre-commit config file
- Setup `codespell.txt` ignored words list
- Fixed a lot of spelling
https://pre-commit.com/#github-actions-example
Installed `pre-commit` locally and then installed the repo hooks and ran from repo root:
This will also run on git commit against changed files

[SEDONA-390] Add `codespell` with `pre-commit`

---

.pre-commit-config.yaml

https://github.com/pre-commit/pre-commit-hooks
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-392. The PR name follows the format `[SEDONA-XXX] my subject`.
Added 5 more hooks from the official `pre-commit` repo
Nothing else to change for these tests.

[SEDONA-392] Add five more pre-commit hooks

---

common/src/main/java/org/apache/sedona/common/raster/RasterBandAccessors.java
common/src/test/java/org/apache/sedona/common/raster/RasterBandAccessorsTest.java
common/src/test/java/org/apache/sedona/common/raster/RasterOutputTest.java
docs/api/sql/Raster-writer.md

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-394. The PR name follows the format `[SEDONA-XXX] my subject`.
- add perservation of pixel data types of pixel/cell.
- add tests to check perservation
- add test for RS_AsPNG using RS_Band
- add docs for RS_AsPNG using RS_Band
- passed added tests

[SEDONA-394] fix RS_Band data type bug

---

python/tests/spatial_operator/test_join_base.py
spark/common/src/main/java/org/apache/sedona/core/spatialRDD/SpatialRDD.java
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryExec.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-XXX. The PR name follows the format `[SEDONA-349] my subject`.
https://github.com/apache/sedona/pull/954/files#diff-63577974e7e93ba53321c1c96a3e6f9db257de58a7504f39ea51641ab82cb5cfR450 added a call to `analyze` in `SpatialRDD.setRawSpatialRDD`. It makes join query using Spark SQL analyzes the dataframes 3 times (where only 1 analyze on the dominant side is needed). This patch removes redundant calls to `analyze`.
Passing existing tests. …

[SEDONA-349] Fix performance regression for spatial join

---

common/src/main/java/org/apache/sedona/common/raster/CRSSerializer.java
common/src/test/java/org/apache/sedona/common/raster/CRSSerializerTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-386. The PR name follows the format `[SEDONA-XXX] my subject`.
Fix a silly mistake in CRS deserialization code: we should use `InflaterInputStream` instead of `DeflaterInputStream` to decompress the stream.
Added test to cover the case where cache was not hit when deserializing CRS objects.

[SEDONA-386] Fixed CRS deserialization when cache was not hit

---

common/src/main/java/org/apache/sedona/common/raster/MapAlgebra.java
common/src/test/java/org/apache/sedona/common/raster/MapAlgebraTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/MapAlgebra.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-397. The PR name follows the format `[SEDONA-XXX] my subject`.
- Moved RS_Add, RS_Subtract, RS_Multiply, RS_Divide, RS_MultiplyFactor, RS_Modulo, RS_SquareRoot, RS_BitwiseAND, RS_BitwiseOR, RS_NormalizeDifference, RS_Mean, RS_Mode, RS_FetchRegion, RS_GreaterThan, RS_GreaterThanEqual, RS_LessThan, RS_LessThanEqual, RS_CountValue, RS_LogicalDifference, RS_LogicalOver, RS_Normalize.
- With the existing tests and new tests
- Yes, I have updated the documentation update if needed.

[SEDONA-397] Move Map Algebra functions

---

common/src/main/java/org/apache/sedona/common/raster/MapAlgebra.java
common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java
common/src/test/java/org/apache/sedona/common/raster/RasterBandEditorsTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterBandEditors.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-398. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add RS_AddBand
- Add Number[] instead of double[] to support generics that are numeric
- Move copyRasterAndAppendBand & copyRasterAndReplaceBand to RasterUtils
- Reorder subsection 'Raster based operators' in Raster-operations.md
- Passed existing and new tests

[SEDONA-398] Add RS_AddBand

---

docs/api/sql/Raster-operators.md
docs/api/sql/Raster-visualizer.md

- `show` function escapes special characters, this messes up with functions that return string with special characters.

[DOCS] Mention behavior of string returning functions

---

common/src/main/java/org/apache/sedona/common/raster/RasterBandAccessors.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-366. The PR name follows the format `[SEDONA-XXX] my subject`.
The current implementation of `RS_Count` calls `GridCoverage2D.evaluate` for each pixel, which calls `getTile` method for each pixel. This is very slow for some implementations of RenderedImage. In this patch, we get the raster of the image and iterate through the samples, which is much faster.
Passes existing tests.

[SEDONA-366] Fix performance issue of RS_Count

---

python/sedona/spark/__init__.py
python/sedona/sql/types.py
python/tests/sql/test_raster.py
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/UDT/RasterUDT.scala

- Yes. https://issues.apache.org/jira/browse/SEDONA-406
`RasterUDT` does not have a corresponding PySpark implementation, which will lead to errors when printing pyspark dataframes. For example, if we run `df` to print the pyspark dataframe in jupyter notebook, it will raise an exception:
```
File /opt/spark/python/pyspark/sql/dataframe.py:2022, in DataFrame.dtypes(self)
2001 @property
2002 def dtypes(self) -> List[Tuple[str, str]]:
2003     """Returns all column names and their data types as a list.
2004 
2005     .. versionadded:: 1.3.0
(...)
2020     [('age', 'bigint'), ('name', 'string')] …
```

[SEDONA-406] Add a dummy implementation of UDT RasterType to get rid of errors when representing pyspark dataframes containing raster fields.

---

.pre-commit-config.yaml
codespell.txt
docs/tutorial/viz.md
spark/common/src/main/scala/org/apache/sedona/viz/sql/operator/VizPartitioner.scala

- update `codespell.txt` ignored words list
- ran `pre-commit autoupdate` to update the hooks
- fixed the spelling errors

[DOCS] Fix spelling; pre-commit autoupdate

---

common/src/main/java/org/apache/sedona/common/raster/RasterAccessors.java
common/src/test/java/org/apache/sedona/common/raster/RasterAccessorsTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterAccessors.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-411. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add RS_Rotation
- Add RS_GeoTransform
- Passed new tests

[SEDONA-411] Add RS_Rotation

---

docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/expressions/FunctionsGeoTools.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
python/tests/sql/test_function.py
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-415. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add support to make `sourceCRS` an optional parameter
- Passed new test cases.

[SEDONA-415] Add optional parameter to ST_Transform

---

python/sedona/spark/__init__.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-419. The PR name follows the format `[SEDONA-419] my subject`.
Remove SedonaKepler and SedonaPyDeck from the `__init__.py` file.
Users who use `from sedona.spark import *` to do SedonaKepler/SedonaPyDeck visualization will need to explicitly import
```
from sedona.maps.SedonaKepler import SedonaKepler
from sedona.maps.SedonaPyDeck import SedonaPyDeck
```
Passed all unit tests

[SEDONA-419] Remove SedonaKepler and SedonaPyDeck from `sedona.spark import *`

---

common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
common/src/test/java/org/apache/sedona/common/raster/RasterBandEditorsTest.java
docs/api/sql/Raster-operators.md
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-422. The PR name follows the format `[SEDONA-XXX] my subject`.
- RS_SetBandNoDataValue: add `null` support, to remove the existing noDataValue.
- RS_Clip: set the noDataValue to the raster
- Passed new test cases

[SEDONA-422] Add a feature in RS_SetBandNoDataValue and fix NoDataValue in RS_Clip

---

docs/community/contributor.md

[DOCS] contributor.md: fix typo - change `Spark` to `Sedona`

---

docs/api/sql/Overview.md
docs/api/viz/sql.md
docs/community/develop.md
docs/setup/flink/install-scala.md
docs/setup/install-scala.md
docs/setup/maven-coordinates.md

Standardized the filename to all lowercase for `pom.xml` in Markdown files.
And a single whitespace change.
All done in the "docs" folder

[DOCS] Fix filename casing for `pom.xml`

---

pom.xml
spark/common/pom.xml

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-424. The PR name follows the format `[SEDONA-XXX] my subject`.
It is better to mark non-central dependencies as provided. jt-jiffle will be bundled in geotools-wrapper in the next release (1.5.1).
Please follow this thread in the sedona mailing list for why this change is necessary: https://lists.apache.org/thread/o4sf32tm1761f32hfckh1x70tl5clc0t
Passing existing tests

[SEDONA-424] Specify jt-jiffle as a provided dependency

---

R/tests/testthat/test-data-interface-raster.R
common/src/main/java/org/apache/sedona/common/raster/PixelFunctions.java
common/src/test/java/org/apache/sedona/common/raster/FunctionsTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/PixelFunctions.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-425. The PR name follows the format [SEDONA-XXX] my subject.
- Add a RS_Values() variant to accept Grid coordinates
- Add a RS_Value() variant to accept Grid coordinates
- Passing new tests

[SEDONA-425] Add RS_Values and RS_Value to accept grid coordinates

---

common/src/main/java/org/apache/sedona/common/raster/RasterAccessors.java
common/src/test/java/org/apache/sedona/common/raster/RasterAccessorsTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterAccessors.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-427. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add RS_RasterToWorldCoord
- Passed all new tests
- Yes, I am adding a new API. I am using the [current SNAPSHOT version number](https://github.com/apache/sedona/blob/e2d3c02081d07f558fb40ba7e02ac6b2680b9d45/pom.xml#L29) in since `vX.Y.Z` format.

[SEDONA-427] Add RS_RasterToWorldCoord

---

common/src/main/java/org/apache/sedona/common/raster/PixelFunctions.java
common/src/main/java/org/apache/sedona/common/raster/PixelRecord.java
common/src/test/java/org/apache/sedona/common/raster/FunctionsTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/PixelFunctions.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-435. The PR name follows the format `[SEDONA-XXX] my subject`.
- Implements Raster operator RS_PixelAsPolygons
- Yes, I am adding a new API. I am using the [current SNAPSHOT version number](https://github.com/apache/sedona/blob/a64972027aa4c0fea354898da67a2dd4e6cde46b/pom.xml#L29) in since `vX.Y.Z` format.

[SEDONA-435] Add RS_PixelAsPolygons

---

common/src/main/java/org/apache/sedona/common/raster/PixelFunctions.java
common/src/main/java/org/apache/sedona/common/raster/PixelRecord.java
common/src/test/java/org/apache/sedona/common/raster/FunctionsTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/PixelFunctions.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-432. The PR name follows the format `[SEDONA-XXX] my subject`.
- Implements Raster operator RS_PixelAsCentroids
- Yes, I am adding a new API. I am using the [current SNAPSHOT version number](https://github.com/apache/sedona/blob/a64972027aa4c0fea354898da67a2dd4e6cde46b/pom.xml#L29) in since `vX.Y.Z` format.

[SEDONA-432] Add RS_PixelAsCentroids

---

common/src/main/java/org/apache/sedona/common/raster/PixelFunctionEditors.java
common/src/test/java/org/apache/sedona/common/raster/FunctionEditorsTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-436. The PR name follows the format `[SEDONA-XXX] my subject`.
- fix the bug that didn't update the values at the expected region, it was updating it at the beginning of the raster.
- passed existing tests

[SEDONA-436] Fix RS_SetValues bug

---

docs/api/sql/Parameter.md
spark/common/src/main/java/org/apache/sedona/core/utils/SedonaConf.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-454. The PR name follows the format `[SEDONA-XXX] my subject`.
Experiments showed that STRtree has better performance in most of cases, and does not have index efficiency problems when indexing points (see [SEDONA-453](https://issues.apache.org/jira/browse/SEDONA-453)). We consider changing the default value of `sedona.global.indextype` from `quadtree` to `rtree` to achieve better out-of-box performance when running spatial joins using SQL queries.
Passing existing tests.
- Yes, I have updated the …

[SEDONA-454] Change the default value of sedona.global.indextype from quadtree to rtree

---

common/src/main/java/org/apache/sedona/common/raster/MapAlgebra.java
common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java
common/src/test/java/org/apache/sedona/common/raster/MapAlgebraTest.java
docs/api/sql/Raster-map-algebra.md
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/MapAlgebra.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-449. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add support for two raster inputs in RS_MapAlgebra
- passed new and existing tests

[SEDONA-449] Add two raster column support to RS_MapAlgebra

---

common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
common/src/test/java/org/apache/sedona/common/raster/RasterBandEditorsTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterBandEditors.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-448. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add replace option to RS_SetBandNoDataValue
- passed existing and new tests

[SEDONA-448] RS_SetBandNoDataValue should have `replace` option

---

python/sedona/maps/SedonaMapUtils.py
python/tests/maps/test_sedonakepler_visualization.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-456. The PR name follows the format `[SEDONA-XXX] my subject`.
This PR makes dataframes with geometry columns not named "geometry" being visualized correctly when using geopandas >= 0.13.0. Please refer to the [JIRA ticket](https://issues.apache.org/jira/browse/SEDONA-456) for details.
Upgrading the geopandas version to 0.13.2 (manually) and passing existing tests.

[SEDONA-456] Fix kepler.gl integration for geopandas >= 0.13

---

spark/common/src/main/scala/org/apache/sedona/spark/SedonaContext.scala
spark/spark-3.0/src/test/scala/org/apache/sedona/sql/geoparquetIOTests.scala
spark/spark-3.4/src/test/scala/org/apache/sedona/sql/geoparquetIOTests.scala
spark/spark-3.5/src/test/scala/org/apache/sedona/sql/geoparquetIOTests.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-440]. The PR name follows the format `[SEDONA-XXX] my subject`.
File formats that support nested predicate pushdown are configured by `spark.sql.optimizer.nestedPredicatePushdown.supportedFileSources`, a comma-separated list of data source names. The default value is `parquet,orc`. This patch appends "geoparquet" to the list when creating SedonaContext to enable nested predicate pushdown for GeoParquet.
Add a new test case.

[SEDONA-440] Enable nested predicate pushdown support for GeoParquet

---

.github/linters/.markdown-lint.yml
docs/community/release-manager.md

https://github.com/DavidAnson/markdownlint/blob/main/doc/md005.md
Standardized the markdown by enabling rule MD005.

[DOCS] Enable markdownlint rule MD005

---

.github/linters/.markdown-lint.yml
docs/community/release-manager.md

https://github.com/DavidAnson/markdownlint/blob/main/doc/md037.md
Standardized and formatted the Markdown correctly.
Tested by visual inspection.
Before:
After:
as seen here:
https://github.com/jbampton/sedona/blob/enable-markdownlint-rule-md037/docs/community/release-manager.md#3-use-svn-to-update-keys

[DOCS] Enable markdownlint rule MD037

---

common/src/main/java/org/apache/sedona/common/Predicates.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
common/src/test/java/org/apache/sedona/common/PredicatesTest.java
common/src/test/java/org/apache/sedona/common/TestBase.java
docs/api/flink/Predicate.md
docs/api/sql/Predicate.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Predicates.java
flink/src/test/java/org/apache/sedona/flink/PredicateTest.java
python/sedona/sql/st_predicates.py
python/tests/sql/test_dataframe_api.py
python/tests/sql/test_predicate.py
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Predicates.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_predicates.scala
spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/predicateTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/projects/SEDONA/issues/SEDONA-369 The PR name follows the format `[SEDONA-XXX] my subject`.
- Add ST_DWithin
- Add PredicatesTest.java for correctness test cases in Java
- Added a TestBase.java to reuse helpers between PredicatesTest and FunctionsTest.java
- Added new tests
- Yes, I am adding a new API. I am using the [current SNAPSHOT version number](https://github.com/apache/sedona/blob/99239524f17389fc4ae9548ea88756f8ea538bb9/pom.xml#L29) in since `vX.Y.Z` format.

[SEDONA-369] Add ST_DWithin

---

common/src/main/java/org/apache/sedona/common/raster/RasterConstructors.java
common/src/main/java/org/apache/sedona/common/utils/ImageUtils.java
common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java
common/src/test/java/org/apache/sedona/common/raster/RasterConstructorsTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/InferredExpression.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterConstructors.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-460. The PR name follows the format `[SEDONA-XXX] my subject`.
Add `RS_Tile` and `RS_TileExplode`. These functions are Similar to [ST_Tile](https://postgis.net/docs/en/RT_ST_Tile.html) in PostGIS.
Add new tests for these newly added functions.
- Yes, I am adding a new API. I am using the [current SNAPSHOT version number](https://github.com/apache/sedona/blob/99239524f17389fc4ae9548ea88756f8ea538bb9/pom.xml#L29) in since `vX.Y.Z` format.

[SEDONA-460] Add RS_Tile and RS_TileExplode

---

docs/tutorial/sql.md

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-458. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add UDF examples in SQL tutorial.

[SEDONA-458] The docs should have examples for UDF

---

docs/tutorial/sql.md
python/tests/sql/test_geoparquet.py
spark/spark-3.0/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
spark/spark-3.0/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataDataSource.scala
spark/spark-3.0/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataPartitionReaderFactory.scala
spark/spark-3.0/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataScan.scala
spark/spark-3.0/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataScanBuilder.scala
spark/spark-3.0/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataTable.scala
spark/spark-3.0/src/test/scala/org/apache/sedona/sql/GeoParquetMetadataTests.scala
spark/spark-3.4/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
spark/spark-3.4/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataDataSource.scala
spark/spark-3.4/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataPartitionReaderFactory.scala
spark/spark-3.4/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataScan.scala
spark/spark-3.4/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataScanBuilder.scala
spark/spark-3.4/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataTable.scala
spark/spark-3.4/src/test/scala/org/apache/sedona/sql/GeoParquetMetadataTests.scala
spark/spark-3.5/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataDataSource.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataPartitionReaderFactory.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataScan.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataScanBuilder.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataTable.scala
spark/spark-3.5/src/test/scala/org/apache/sedona/sql/GeoParquetMetadataTests.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-455. The PR name follows the format `[SEDONA-XXX] my subject`.
This patch adds a new data source named `geoparquet.metadata` implemented using DataSourceV2 API. It produces a dataframe containing GeoParquet metadata for each data file. Here is an example resulting dataframe loaded from geoparquet.metadata:
```
+-----------------+------------+--------------+------------------------------------------------------------------+
|path             |version     |primary_column|columns …
```

[SEDONA-455] geoparquet.metadata data source for inspecting GeoParquet metadata

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-461. The PR name follows the format `[SEDONA-XXX] my subject`.
Adds vector function ST_IsValidReason
- Returns text stating if the geometry is valid. If not, it provides a reason why it is invalid.
- Passed new and existing tests
- Yes, I am adding a new API. I am using the [current SNAPSHOT version number](https://github.com/prantogg/sedona/blob/f37bb46e101fac2aa1c62ace2f56818c51c17a03/pom.xml#L29) in since `vX.Y.Z` format.

[SEDONA-461] Add ST_IsValidReason

---

.github/linters/.markdown-lint.yml

https://github.com/DavidAnson/markdownlint/blob/main/doc/md009.md
Previous commits have already removed the trailing whitespace
Enabled a markdownlint rule to check for trailing whitespace
or
`pre-commit run markdownlint --all-files`

[DOCS] Enable markdownlint rule MD009

---

.github/linters/.markdown-lint.yml

https://github.com/DavidAnson/markdownlint#rules--aliases
Added the markdownlint rule descriptions as comments for convenience
Added some extra documentation as comments
Tested by visual inspection and also ran:
which runs the Markdown linter.

[DOCS] Add rule descriptions to the markdownlint config file

---

snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestBase.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctions.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsV2.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestPredicatesV2.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/GeometrySerde.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFsV2.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/annotations/UDFAnnotations.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/annotations/UDTFAnnotations.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/ddl/ArgSpecBuilder.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/ddl/Constants.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/ddl/DDLGenerator.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/ddl/UDFDDLGenerator.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/ddl/UDTFDDLGenerator.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/udtfs/ST_SubDivideExplodeV2.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-459. The PR name follows the format `[SEDONA-XXX] my subject`.
Added UDFsV2 which overload all ST functions with native Snowflake Geometry type. Now SedonaSnow functions can directly interact with Snowflake native ST functions. Users can mix-match Sedona / Snowflake ST functions together in the same SQL query, without additional WKB serialization like Snowflake `ST_AsWKB` and `to_geometry`
Example:
```
SELECT ST_AsText(SEDONA.ST_ReducePrecision(ST_GeometryFromWKT('POINT(1.123456789 2.123456789)'), 3))
``` …

[SEDONA-459] Open-source Sedona Snowflake (SedonaSnow): Overload ST functions to enable direct interaction with Snowflake native ST functions. PR 2/4

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/main/java/org/apache/sedona/common/utils/GeomUtils.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctions.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsV2.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestPredicates.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestPredicatesV2.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFsV2.java
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-459. The PR name follows the format `[SEDONA-XXX] my subject`.
The following functions have been added to Sedona Snowflake
1. GeometryType
2. ST_CoordDim
3. ST_MakePoint
4. ST_Dimension
5. ST_ClosestPoint
6. ST_IsCollection
7. ST_MakeLine
8. ST_Polygon
9. ST_LineLocatePoint
10. ST_VoronoiPolygons
11. ST_FrechetDistance
12. ST_Affine
13. ST_BoundingDiagonal
14. ST_Angle
15. ST_Degrees
16. ST_HausdorffDistance
17. ST_DWithin
18. ST_IsValidReason
Among them, the following functions have been overloaded with …

[SEDONA-459] Open-source Sedona Snowflake (SedonaSnow): Add new ST functions added in 1.5.0 and 1.5.1. PR 3/4

---

common/src/main/java/org/apache/sedona/common/raster/RasterConstructors.java
docs/api/sql/Raster-writer.md
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterConstructors.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasterIOTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-466. The PR name follows the format `[SEDONA-XXX] my subject`.
- Expose the `useGeometryExtent` parameter to user and RS_AsRaster support 6 parameters now.
- A new `asRaster` function with 6 parameters.  Old `asRaster` and `asRasterwithRasterExtent` functions are revised accordingly.
- Add new tests to test the new parameter.
- Add relative docs and example aboput the new parameter.
- Passed added tests and old relevant tests

[SEDONA-466] Add new parameter `useGeometryExtent` to RS_AsRaster

---

.github/linters/.markdown-lint.yml
docs/api/flink/Function.md

https://github.com/DavidAnson/markdownlint/blob/main/doc/md030.md
Standardized the Markdown and enabled rule MD030
or
`pre-commit run markdownlint --all-files`

[DOCS] Enable markdownlint rule MD030

---

docs/api/sql/Optimizer.md
docs/setup/install-scala.md
docs/tutorial/sql-pure-sql.md
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
spark/common/src/test/scala/org/apache/sedona/sql/BroadcastIndexJoinSuite.scala
spark/common/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/predicateJoinTestScala.scala

- Yes, I am adding a new API. I am using the [current SNAPSHOT version number](https://github.com/apache/sedona/blob/99239524f17389fc4ae9548ea88756f8ea538bb9/pom.xml#L29) in since `vX.Y.Z` format.

Update the base

---

spark/common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetMetaData.scala
spark/spark-3.0/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataPartitionReaderFactory.scala
spark/spark-3.0/src/test/scala/org/apache/sedona/sql/GeoParquetMetadataTests.scala
spark/spark-3.4/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataPartitionReaderFactory.scala
spark/spark-3.4/src/test/scala/org/apache/sedona/sql/GeoParquetMetadataTests.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataPartitionReaderFactory.scala
spark/spark-3.5/src/test/scala/org/apache/sedona/sql/GeoParquetMetadataTests.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-470. The PR name follows the format `[SEDONA-XXX] my subject`.
This PR makes geoparquet files with null or missing crs fields show different results when inspecting using geoparquet.metadata file format. Please refer to the JIRA ticket for details.
This is done by adding a postprocessing after parsing the geo metadata using json4s. I've not found any other way yet so I decided to keep it that way.
Add new tests and also tested manually using Apache Spark 3.5.
- No, this PR does not affect any public API …

[SEDONA-470] Distinguish between missing or null crs from the result of geoparquet.metadata

---

python/sedona/core/jvm/config.py

The removed lines prevent the application developer using this library to ignore these warnings with e.g. `pytest -W
ignore::DeprecationWarning`
- No
Removing some code that changes the application filters configuration

[SEDONA-474] python: remove manipulation of warnings config

---

docs/setup/overview.md
docs/setup/snowflake/install.md
docs/tutorial/snowflake/sql.md
mkdocs.yml

Fixed a bunch of deadlinks and wrong formats in the docs.
Passed local build

[DOCS] Fix deadlinks in docs

---

docs/tutorial/sql.md
python/sedona/maps/SedonaKepler.py
python/sedona/maps/SedonaPyDeck.py
python/sedona/spark/__init__.py
python/setup.py

This updates the Sedona python package with three new extras: `kepler-map`, `pydeck-map`, and an `all` extras. 
It also moves the import of the optional dependencies `kepler` and `pydeck` inside the functions where they are used. This avoids logging unnecessary warnings like those described in #1222.
I tested the addition of the extras by doing local installs of the module in a virtual environment. The changes to `SedonaKepler` and `SedonaPyDeck` have been tested in the CI.
- Yes, I have updated the …

[SEDONA476] Expose kepler & pydeck as extras

---

.github/workflows/python-wheel.yml

Bump cibuildwheel to 2.16.5 to fix the incompatibility issue caused by new GitHub Windows image: https://github.com/pypa/cibuildwheel/issues/1748
Pass the GitHub CI

[DOCS] Bump cibuildwheel version to 2.16.5

---

common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java
common/src/test/java/org/apache/sedona/common/raster/RasterBandEditorsTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-477. The PR name follows the format `[SEDONA-XXX] my subject`.
The result of RS_Clip returns GridCoverage2D objects containing JAI images with non-zero origin when `crop = true`. This will bring a full range of problems when handling such GridCoverage2D objects, because lots of band operation code assumes that the JAI images have zero origin, and the `BufferedImage` of AWT also does not allow images with non-zero origin, which make it difficult to construct image objects from in-memory buffer.
We decide …

[SEDONA-477] Shift the origin of clip results to zero

---

common/src/main/java/org/apache/sedona/common/raster/MapAlgebra.java
common/src/test/java/org/apache/sedona/common/raster/MapAlgebraTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/MapAlgebra.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-475. The PR name follows the format `[SEDONA-XXX] my subject`.
Adds RS_NormalizeAll, to normalize values in all bands of a raster between a given normalization range. 
Key features - 
- **Flexible Normalization Range**: Optionally specify normalization range through `minLim` and `maxLim`. By default, the values are normalized to range [0, 255].
- **Handling Uniform Bands**: For bands where all pixel values are identical, normalized values are set to lower limit of normalization range.
- **Handling …

[SEDONA-475] Add RS_NormalizeAll

---

common/src/main/java/org/apache/sedona/common/raster/MapAlgebra.java
common/src/test/java/org/apache/sedona/common/raster/MapAlgebraTest.java
docs/api/sql/Raster-operators.md

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-479. The PR name follows the format `[SEDONA-XXX] my subject`.
Fixes incorrect behavior of RS_Normalize for certain arrays and handles uniform arrays. 
Passes new and existing tests

[SEDONA-479] Update RS_Normalize

---

spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/raster/RasterFileFormat.scala
spark/common/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasterIOTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-494. The PR name follows the format `[SEDONA-494] my subject`.
Fix the issue that raster data source cannot write to HDFS.
Thanks for the solution provided by @MyqueWooMiddo
1. Passed existing tests.
2. Passed the test of writing data to a miniHDFS cluster

[SEDONA-494] Raster data source cannot write to HDFS

---

spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/raster/RasterFileFormat.scala
spark/common/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasterIOTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-495. The PR name follows the format `[SEDONA-495] my subject`.
Create a new FileSystem connection per task instead of using a shared FileSystem connection among all tasks on an executor.
Modified the test data to have multiple partitions (tasks) and passed local tests

[SEDONA-495] Raster data source uses shared FileSystem connections which lead to race condition

---

.github/dependabot.yml

This will reduce the number of open pull requests for version updates at any one time.
Might help to reduce spam like content on the mailing list.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-496. The PR name follows the format `[SEDONA-XXX] my subject`.
Reduce the open pull requests limit to 2

[SEDONA-496] Dependabot: reduce the open pull requests limit to 2

---

spark/common/src/main/java/org/apache/sedona/core/formatMapper/shapefileParser/ShapefileReader.java
spark/common/src/test/java/org/apache/sedona/core/formatMapper/shapefileParser/shapes/ShapefileReaderTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-497]. The PR name follows the format `[SEDONA-XXX] my subject`.
We won't concatenate the schema of all shapefiles when inferring the `fieldNames` property of the resulting SpatialRDD. This behavior is strange so I changed it to check if all the shapefiles have consistent schema. If there's any concern regarding this change please let me know.
Add new tests for reading multiple shapefiles.

[SEDONA-497] Fix incorrect fieldNames property of SpatialRDD read from a directory containing multiple shapefiles

---

pom.xml
spark-shaded/pom.xml

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-473. The PR name follows the format `[SEDONA-XXX] my subject`.
- Remove ucar from spark-shaded pom
- Passed existing tests

[SEDONA-473] Remove ucar from spark-shaded pom

---

spark/common/src/main/java/org/apache/sedona/core/formatMapper/shapefileParser/shapes/ShapeInputFormat.java
spark/common/src/test/java/org/apache/sedona/core/formatMapper/shapefileParser/shapes/ShapefileReaderTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-500. The PR name follows the format `[SEDONA-XXX] my subject`.
Fix problems when generating splits for directories containing multiple shapefiles. This fixes the following issues:
1. Reading fails with errors such as "shape record loses attributes in .dbf file at ID=2387"
2. Geometry values and other fields do not match.
3. Not all records were read into SpatialRDD
Add additional assertion to the `testReadMultipleShapeFilesByMultiPartitions` test case.
- No, this PR does not affect any public API so no …

[SEDONA-500] Fix failures and data consistency problems when reading multiple shapefiles in one directory

---

python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-501. The PR name follows the format `[SEDONA-XXX] my subject`.
Map Python ST_Split to Java ST_Split.
I updated unit tests. I could not get the polygon/polygon test data (overlapping_polys) to yield a deterministic result, so I added some test data (multipoint_splitting_line) that is identical to the documentation example: https://sedona.apache.org/1.5.1/api/sql/Function/?h=st_#st_split
FYI: The non-deterministic behaviour on splitting polygons with polygons seem just to be the choice for start/end of the …

[SEDONA-501] ST_Split maps to wrong Java-call

---

common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-505. The PR name follows the format `[SEDONA-XXX] my subject`.
The following RS functions do not perform implicit CRS transformation when the geometry has SRID=0:
* RS_ZonalStats
* RS_ZonalStatsAll
* RS_WorldToRasterCoord
* RS_WorldToRasterCoordX
* RS_WorldToRasterCoordY
This behavior is inconsistent with other raster functions such as RS_Value, RS_Intersects, and RS_Clip. We'll change the behavior of listed functions to treat geometries with SRID=0 as if they were in EPSG:4326 and perform implicit CRS …

[SEDONA-505] Fix handling of geometries with SRID=0 in some raster functions

---

common/src/main/java/org/apache/sedona/common/raster/RasterOutputs.java
common/src/test/java/org/apache/sedona/common/raster/RasterOutputTest.java
docs/api/sql/Raster-visualizer.md
docs/api/sql/Raster-writer.md
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterOutputs.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-507. The PR name follows the format `[SEDONA-XXX] my subject`.
RS_AsImage only produces PNG images for rasters with integral band data, and produces TIFF images for rasters with floating point band data. TIFF cannot be displayed on many mainstream browsers, so we should not use TIFF to visualize rasters.
This PR make RS_AsPNG work for all types of band data, so that RS_AsImage won't produce TIFF base64 output.
* If the band data type is byte, we try converting it to PNG directly. This will preserve the …

[SEDONA-507] RS_AsImage and RS_AsPNG could properly handle non-integral band data

---

common/src/main/java/org/apache/sedona/common/raster/RasterBandAccessors.java
common/src/test/java/org/apache/sedona/common/raster/RasterBandAccessorsTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterBandAccessors.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

This PR depends on https://github.com/apache/sedona/pull/1256
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-506. The PR name follows the format `[SEDONA-XXX] my subject`.
Add an optional `lenient` parameter to `RS_ZonalStats` and `RS_ZonalStatsAll`. The default value is `true`. When `lenient` is set to `true`, zonal stats functions won't raise exceptions when the ROI does not intersect with the raster, and return null in such cases.
Add tests for lenient mode.

[SEDONA-506] Lenient mode for RS_ZonalStats and RS_ZonalStatsAll

---

python/sedona/raster_utils/SedonaUtils.py
python/sedona/spark/__init__.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-476. The PR name follows the format `[SEDONA-XXX] my subject`.
Fix how we import `SedonaKepler` and `SedonaPyDeck` in `sedona/spark/__init__.py`, so that we can call `sedona.spark.SedonaKepler.create_map` after `import sedona.spark`, instead of `sedona.spark.SedonaKepler.SedonaKepler.create_map`.
This PR also contains a fix for https://github.com/apache/sedona/issues/1253, so that `import sedona.spark` won't require IPython to be present.
Tested manually in a virtual environment.
- No, this PR does not …

[SEDONA-476] Fixed package names of SedonaKepler and SedonaPyDeck; do not require IPython to be installed to `import sedona.spark`

---

common/src/main/java/org/apache/sedona/common/raster/RasterConstructors.java
common/src/test/java/org/apache/sedona/common/raster/RasterConstructorsTest.java
docs/api/sql/Raster-loader.md
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterConstructors.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-517. The PR name follows the format `[SEDONA-XXX] my subject`.
Add a new raster constructor `RS_MakeRaster` for constructing a raster using specified band data. The width, height, geo-reference information, and CRS will be the same as the given reference raster.
Add new unit test.
- Yes, I am adding a new API. I am using the [current SNAPSHOT version number](https://github.com/apache/sedona/blob/99239524f17389fc4ae9548ea88756f8ea538bb9/pom.xml#L29) in since `vX.Y.Z` format.

[SEDONA-517] RS_MakeRaster

---

docs/setup/emr.md
docs/setup/release-notes.md
docs/tutorial/geopandas-shapely.md
docs/tutorial/sql.md

Update statements about Shapely 2 support.
Previewed locally.

[DOCS] Update statements about Shapely 2 support

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/tests/sql/test_function.py
spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-521. The PR name follows the format `[SEDONA-XXX] my subject`.
- Change the output of `ST_H3ToGeom` from a single MultiPolygon to an array of Polygons, each Polygon representing an H3 cell.
- Passed new and existing tests.

[SEDONA-521] Change ST_H3ToGeom Behavior

---

docs/tutorial/viz.md
docs/tutorial/zeppelin.md

Fixed a link and fixed some grammar.

[DOCS] Fix grammar and fix link

---

.pre-commit-config.yaml

https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#check-ast
https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#detect-aws-credentials
https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#trailing-whitespace
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-525. The PR name follows the format `[SEDONA-XXX] my subject`.
Added two more hooks to our pre-commit framework.
Standardized the `trailing-whitespace` hook
Ran locally:
- No, this PR does not affect any public API so no need to …

[SEDONA-525] Add two more pre-commit hooks

---

.github/workflows/docker-build.yml
.github/workflows/example.yml
.github/workflows/java.yml
.github/workflows/python.yml
.github/workflows/r.yml

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-526. The PR name follows the format `[SEDONA-XXX] my subject`.
Upgraded to actions/setup-java version 4.
"The major breaking change in V2 is the new mandatory distribution input."
"Use the zulu keyword if you would like to continue using the same distribution as in V1."
https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md

[SEDONA-526] Upgrade `actions/setup-java` to `v4`

---

docs/setup/cluster.md

Fixed some grammar and spelling.

[DOCS] Fix grammar and spelling in `docs/setup/cluster.md`

---

.editorconfig

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-529. The PR name follows the format `[SEDONA-XXX] my subject`.
This PR adds a basic `.editorconfig` file.  Most editors / IDEs already have support for editor config.
https://editorconfig.org/
https://github.com/editorconfig/editorconfig/wiki/Projects-Using-EditorConfig
"What is EditorConfig?
EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles …

[SEDONA-529] Add basic `EditorConfig` file

---

spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/optimization/ExpressionUtils.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/OptimizableJoinCondition.scala
spark/common/src/test/scala/org/apache/sedona/sql/SpatialJoinSuite.scala
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-532. The PR name follows the format `[SEDONA-XXX] my subject`.
Refactored the code for detecting spatial join predicates in join conditions. Now we are capable of handling complex join conditions such as `ST_Intersects(geom1, geom2) AND expr1 AND expr2`.
Added new tests and manually tested the query mentioned in the JIRA ticket.

[SEDONA-532] Correctly handle complex join conditions

---

Makefile

This PR adds two more Makefile targets.
It makes it much easier to run the commands with the Makefile file
Ran the Make commands

[DOCS] Add two targets to the Makefile for building docs

---

docs/api/flink/Constructor.md
docs/api/snowflake/vector-data/Constructor.md
docs/api/sql/Constructor.md

- Rearrange Constructor pages for each engine in alphabetic order.

[DOCS] Reorder Constructor page

---

.github/linters/.markdown-lint.yml
docs/api/sql/Raster-operators.md
docs/setup/release-notes.md

https://github.com/DavidAnson/markdownlint/blob/main/doc/md004.md
Standardized some Markdown files
`markdownlint --fix --config=.github/linters/.markdown-lint.yml docs`

[DOCS] Enable markdownlint rule `MD004`

---

.github/linters/.markdown-lint.yml

https://github.com/DavidAnson/markdownlint/blob/main/doc/md042.md
Adds another check or test to our Markdown linting framework.
Just enabled the rule.  Seems we already passed the test.

[DOCS] Enable markdownlint rule `MD042`

---

.github/linters/.markdown-lint.yml
docs/api/flink/Constructor.md
docs/api/flink/Function.md
docs/api/sql/Constructor.md
docs/api/sql/Function.md
docs/tutorial/rdd.md

Now testing for `MD051` -  Link fragments should be valid.
https://github.com/DavidAnson/markdownlint/blob/main/doc/md051.md

[DOCS] Enable markdownlint rule `MD051`

---

Makefile
docs/setup/compile.md

Added the missing install instructions.
See:
https://github.com/apache/sedona/blob/dc7e5c91c1641edbcdf8bacd3d12a20f14745aca/.github/workflows/docs.yml#L33
Installed with pip; ran mkdocs serve;

[DOCS] Add `pip install mkdocs-jupyter` to setup

---

.github/workflows/python-extension.yml

- No, this is a CI update.
The latest version of `setuptools` introduced a [breaking change](https://github.com/pypa/setuptools/issues/4300): the name of sdist package changed from `apache-sedona-*.tar.gz` to `apache_sedona-*.tar.gz`. We have to update the command for installing Python source package to pickup whatever package file setuptools has generated.
Passing CI

[CI] Change command for installing python source package

---

python/sedona/core/SpatialRDD/spatial_rdd.py
python/sedona/core/jvm/config.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-531. The PR name follows the format `[SEDONA-531] my subject`.
1. Remove the version check, `since`, in Sedona Python.
2. Add the correct way to detect Sedona version
Passed existing tests

[SEDONA-531] Remove the version check in Sedona Spark Python

---

python/sedona/core/jvm/config.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-534. The PR name follows the format `[SEDONA-534] my subject`.
1. Move the error message to info level
2. Stop printing the stackstrace

[SEDONA-534] Disable Python warning message of finding jars

---

.github/workflows/docker-build.yml
docs/api/snowflake/vector-data/Function.md
docs/api/sql/Raster-operators.md
docs/api/sql/Visualization_SedonaKepler.md
docs/community/develop.md
docs/community/release-manager.md
docs/community/rule.md
docs/community/vote.md
docs/setup/emr.md
docs/setup/install-python.md
docs/setup/release-notes.md
docs/setup/snowflake/install.md
docs/tutorial/rdd.md
docs/tutorial/snowflake/sql.md

Fixed grammar and spelling.
Visually spell checked and ran pre-commit locally.

[DOCS] Fix grammar and spelling

---

.github/CODEOWNERS

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-536. The PR name follows the format `[SEDONA-XXX] my subject`.
Added a CODEOWNERS file

[SEDONA-536] Add CODEOWNERS file

---

.github/workflows/docs.yml

https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#example-only-run-job-for-specific-repository
When a contributor syncs their fork from the upstream and pushes back to origin master on GitHub the docs build currently fails as seen in the next two links:
https://github.com/jbampton/sedona/actions/runs/8780798846/job/24091461356
https://github.com/furqaankhan/sedona/actions/runs/8725430958/job/23938384642
Here is an image of the failure:
Probably the worst part about …

[DOCS] Skip docs deploy on forks

---

.github/linters/.markdown-lint.yml
R/README.md
docs/community/develop.md
docs/community/release-manager.md
docs/tutorial/python-vector-osm.md

https://github.com/DavidAnson/markdownlint/blob/main/doc/md001.md
Now testing for markdownlint rule `MD001`.  Heading levels should only increment by one level at a time.
Also some small improvements to markup and ordering of headings.  Added links to JetBrains tools and RStudio. 

[DOCS] Improve docs and enable markdownlint rule `MD001`

---

.github/linters/.markdown-lint.yml
docs/api/flink/Function.md
docs/api/snowflake/vector-data/Function.md
docs/api/sql/Function.md
docs/community/contributor.md
docs/community/publication.md
docs/community/release-manager.md
docs/setup/databricks.md

https://github.com/DavidAnson/markdownlint/blob/main/doc/md032.md
Now testing for markdownlint rule `MD032` - Lists should be surrounded by blank lines
Visual check of the markup.
Ran:
Ran:
`markdownlint --config=.github/linters/.markdown-lint.yml docs --fix`

[DOCS] Enable markdownlint rule `MD032`

---

.github/linters/codespell.txt
.pre-commit-config.yaml

https://github.com/pre-commit/pre-commit-hooks
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-538. The PR name follows the format `[SEDONA-XXX] my subject`.
Added four more checks or tests to our pre-commit framework.

[SEDONA-538] Add four more pre-commit hooks

---

snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestBase.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-541. The PR name follows the format `[SEDONA-541] my subject`.
Use a random string as the snowflake db name to allow concurrent testing

[SEDONA-541] Allow concurrent snowflake testers

---

docs/tutorial/snowflake/sql.md
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestBase.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsGeography.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/ddl/UDFDDLGenerator.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-539. The PR name follows the format `[SEDONA-539] my subject`.
1. Sedona Snowflake DDL generator produces DDL for snowflake geography type functions
2. Add a single test to verify if the geography type works.
Passed existing tests and the new test.
Tested at: https://github.com/wherobots/sedona-snowflake-tester/pull/22

[SEDONA-539] Support Snowflake geography type

---

.github/linters/ruff.toml
.pre-commit-config.yaml

https://github.com/astral-sh/ruff-pre-commit
Currently just running Ruff's linter.
Used the default Ruff config file and just added code entries to the `ignore` array.
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-544. The PR name follows the format `[SEDONA-XXX] my subject`.
fixes #1367 
Just getting setup with a basic config file in this PR.
In future we can decide more on formatting and on checking for more "codes".
By having the ruff check we stop regressions in Python syntax and formatting.
https://docs.astral.sh/ruff/configuration/
Ran …

[SEDONA-544] Add `ruff-pre-commit` for `Python` linting

---

.github/linters/ruff.toml
.pre-commit-config.yaml
python/tests/maps/test_sedonapydeck.py
python/tests/sql/test_function.py

Comparison to true should be 'if cond is true:' or 'if cond:'.
https://www.flake8rules.com/rules/E712.html
https://peps.python.org/pep-0008/#programming-recommendations
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-546. The PR name follows the format `[SEDONA-XXX] my subject`.
Standardized the Python code for best practice.
Ran  `pre-commit run --all-files`

[SEDONA-546] Python linting enable rule `E712`

---

.github/workflows/java.yml
.github/workflows/python.yml
.github/workflows/r.yml
R/R/dependencies.R
common/src/main/java/org/apache/sedona/common/utils/TelemetryCollector.java
common/src/test/java/org/apache/sedona/common/telemetry/TelemetryTest.java
docs/asf/telemetry.md
flink/src/main/java/org/apache/sedona/flink/SedonaContext.java
mkdocs.yml
python/sedona/spark/SedonaContext.py
spark/common/src/main/scala/org/apache/sedona/spark/SedonaContext.scala
spark/common/src/main/scala/org/apache/sedona/sql/utils/SedonaSQLRegistrator.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-547. The PR name follows the format `[SEDONA-547] my subject`.
Apache Sedona uses Scarf to collect anonymous usage data to help us understand how the software is being used and how we can improve it. You can opt out of telemetry collection by setting the environment variable `SCARF_NO_ANALYTICS` or `DO_NOT_TRACK` to `true` on your local machine, or the driver machine of your cluster.
Scarf fully supports the GDPR and is allowed by [the Apache Software Foundation privacy …

[SEDONA-547] Use scarf to collect telemetry data

---

common/src/main/java/org/apache/sedona/common/raster/serde/Serde.java
spark/common/src/main/scala/org/apache/sedona/sql/utils/RasterSerializer.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/AggregateFunctions.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-543. The PR name follows the format `[SEDONA-XXX] my subject`.
- In RS_Union_aggr, moves class level members like `referenceRaster` to data buffer.
- Passes existing tests

[SEDONA-543] Fixes RS_Union_aggr throwing referenceRaster is null error when run on cluster

---

docs/api/snowflake/vector-data/AggregateFunction.md
docs/api/snowflake/vector-data/Function.md
docs/api/sql/Constructor.md
docs/api/sql/DataFrameAPI.md
docs/api/sql/Raster-affine-transformation.md
docs/api/sql/Raster-loader.md
docs/api/sql/Raster-operators.md
docs/api/sql/Raster-visualizer.md
docs/api/sql/Raster-writer.md
docs/tutorial/rdd.md
mkdocs.yml

Fixed the following docs:
1. Added explanation of raster affine transformation so the meaning of ScaleX, ScaleY, SkewX, SkewY is better explained
2. Fixed the example queries of SedonaSnow table functions
3. Added necessary `import` statements for SedonaUtils.display_image
4. Added an example of how to set up `sedona.global.charset` for shapefile reader
Passed local doc build

[DOCS] Fix docs of SedonaSnow, Affine transformation, SedonaUtils, Shapefile charset

---

python/Pipfile
python/setup.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-550. The PR name follows the format `[SEDONA-550] my subject`.
Updated the following file to remove the upper bound of supported geopandas versions
1. Update `setup.py`
2. Update `Pipfile`
Note: Pandas `2.0` has compatibility issues with some Spark versions. Have to fail back to `1.5.3`
Pending tests in the CI

[SEDONA-550] Remove the version upper bound of Pandas, GeoPandas

---

.github/linters/ruff.toml
python/sedona/utils/geometry_serde_general.py

E741 - Do not use variables named 'I', 'O', or 'l'
https://www.flake8rules.com/rules/E741.html
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-552. The PR name follows the format `[SEDONA-XXX] my subject`.
Cleaned up the Python code

[SEDONA-552] Enable Python lint rule `E741`

---

spark/common/src/main/scala/org/apache/sedona/spark/SedonaContext.scala
spark/common/src/main/scala/org/apache/sedona/sql/RasterRegistrator.scala
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/sedona/sql/UDF/RasterUdafCatalog.scala
spark/common/src/main/scala/org/apache/sedona/sql/UDF/UdfRegistrator.scala
spark/common/src/main/scala/org/apache/sedona/sql/utils/SedonaSQLRegistrator.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/UDT/RasterUdtRegistratorWrapper.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-478. The PR name follows the format `[SEDONA-478] my subject`.
1. Refactor the raster registration flow so raster functions which relies on GeoTools become optional.
2. The RasterUDT and Raster UDAF will be registered only if GeoTools coverage exists
3. Regular raster UDF will still be registered anyways but they will not block the registration process since they will not be loaded unless someone explicitly call them.
- No, this PR does not affect any public API so no need to change …

[SEDONA-478] Sedona 1.5.1 context initialization fails without GeoTools coverage

---

common/src/main/java/org/apache/sedona/common/raster/MapAlgebra.java
common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
common/src/main/java/org/apache/sedona/common/raster/serde/Serde.java
common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/AggregateFunctions.scala

The current RS_Union_Aggr keeps redundant data within buffers. This PR eliminates them.
We've also removed all the boxing/unboxing of pixel data for RS_AddBand.
Passing existing tests

[SEDONA-549] Fix memory bloat issue of RS_Union_Aggr when working with non-double band data

---

docs/setup/databricks.md
docs/setup/emr.md
docs/setup/fabric.md
docs/setup/release-notes.md
docs/setup/wherobots.md

1. Updated the release notes again
2. Added Java 11 tutorial on different platform

[DOCS] Update 1.6.0 release notes with Java 11 tutorial

---

python/sedona/maps/SedonaMapUtils.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-556. The PR name follows the format `[SEDONA-556] my subject`.
https://github.com/apache/sedona/pull/1229 tried to eliminate the warning message of KeplerGL and DeckGL. This was done by removing the try-catch of import error message. This try-catch also hides the GeoPandas error accidentally in the past. The removal of this interception hence makes GeoPandas a required dependency.
This PR moves the `import geopandas` statement to the function that actually needs.
- No, this PR does …

[SEDONA-556] Hidden requirement for geopandas in apache-sedona 1.5.2

---

docs/setup/release-notes.md

[DOCS] Add 1.5.3 release notes

---

flink/pom.xml
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
flink/src/test/java/org/apache/sedona/flink/PredicateTest.java

This PR bumps Flink from 1.14.6 to 1.19.0 and there are 3 major changes
- Bump Flink to 1.19.0
- Remove useless flink-connector-kafka(for the newer version jackson-bind may break tests)
- Repair tests using deprecated interface

[SEDONA-557] Bump Flink from 1.14.x to 1.19.0

---

.github/workflows/example.yml
.github/workflows/java.yml
.github/workflows/python-wheel.yml
.github/workflows/python.yml
.github/workflows/r.yml
R/tests/testthat/test-data-interface-raster.R

Add the yml file path to each yml file itself

[CI] Ensure each yml change triggers the action

---

docs/api/sql/Visualization_SedonaPyDeck.md
python/sedona/maps/SedonaPyDeck.py
python/sedona/sql/st_constructors.py
python/tests/maps/test_sedonapydeck.py
python/tests/sql/test_dataframe_api.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-558. The PR name follows the format `[SEDONA-XXX] my subject`
- Adds the optional parameters `map_style`, and `map_provider` as data members to the pdk map object. 
eg: map_p.map_style = map_style
- The current behavior of PyDeck doesn't update the map object with the additional configuration added via data members.
- The default `map_style` is 'dark' and `map_provider` is 'carto'. If you configure `map_style` to 'satellite' it will not change the `map_provider` to Mapbox or Google Maps API. 
- Expose …

[SEDONA-558] Fix and improve SedonaPyDeck behavior

---

binder/Pipfile
binder/Pipfile.lock

This is a follow-up PR of https://github.com/apache/sedona/pull/1421. The dependency installation fails randomly when installing dependencies from Pipfile, and `keplergl` installation fails for most of the time.
When Pipfile is present and there's no Pipfile.lock file, the dependency installation process is initiated by `pipenv install --skip-lock --system --dev`. This will run several `pip install` commands in parallel, which is the source of all sorts of random failures. Each individual `pip install` …

[DOCS] Add Pipfile.lock file to binder configuration

---

.github/workflows/docker-build.yml
docker/sedona-spark-jupyterlab/.dockerignore
docker/sedona-spark-jupyterlab/build.sh
docker/sedona-spark-jupyterlab/sedona-jupyterlab.Dockerfile.dockerignore
docker/sedona-spark-jupyterlab/sedona-jupyterlab.dockerfile
docker/sedona-spark-jupyterlab/sedona-jupyterlab.dockerfile.dockerignore
docker/sedona-spark-jupyterlab/start.sh
docker/sedona.sh

- No, this is a CI update. The PR name follows the format `[CI] my subject`.
* Supports building docker images for Spark 3.5
* Automatically pickup GeoTools version when building docker images for latest (probably snapshot) version of Sedona
* Add dockerignore file to reduce the size of build context
* Check if RAM is sufficient to run driver + executor and show hints for tuning DRIVER_MEM and EXECUTOR_MEM
* Add `SPARK_WORKER_MEMORY` config to ensure the worker has enough memory to be allocated
* Allow terminating the container using Ctrl-C
* Fix matrix declaration for docker build workflow
* …

[CI] Docker build improvements

---

spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/SpatialIndexExec.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/TraitJoinQueryBase.scala
spark/common/src/test/scala/org/apache/sedona/sql/RasterJoinSuite.scala
spark/common/src/test/scala/org/apache/sedona/sql/SpatialJoinSuite.scala
spark/common/src/test/scala/org/apache/sedona/sql/SphereDistanceJoinSuite.scala
spark/common/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-560. The PR name follows the format `[SEDONA-XXX] my subject`.
Spatial join involving dataframes containing 0 partitions may fail. This is because of the inappropriate handling of such edge cases. This PR resolves such problems.
We've also refactored the code for setting up environments to run spatial join tests to be more compact and readable.
Add new tests.

[SEDONA-560] Properly handle dataframes containing 0 partitions when running spatial join

---

spark/common/src/main/java/org/apache/sedona/core/formatMapper/shapefileParser/ShapefileRDD.java
spark/common/src/main/java/org/apache/sedona/core/showcase/Example.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-561. The PR name follows the format `[SEDONA-XXX] my subject`.
1. This PR fixed the examples in the core package to use the correct file start/end offsets and to use the latest shapefile RDD loader.
2. It added `null` handling in the format mapper
Passed existing tests.

[SEDONA-561] Fix the examples in the core.showcase package

---

spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/UDT/GeometryUDT.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/UDT/RasterUDT.scala
spark/common/src/test/scala/org/apache/sedona/sql/GeometryUdtTestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/RasterUDTSuite.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-580. The PR name follows the format `[SEDONA-XXX] my subject`.
* Implement `equals` and `hashCode` for RasterUDT to ensure that newly created instances of RasterUDT class are equal to the RasterUDT case class.
* Fix `hashCode` for GeometryUDT
Add new tests and manually test on external systems.

[SEDONA-580] New instances of RasterUDT object should equal to the RasterUDT case object

---

python/sedona/maps/SedonaKepler.py
python/tests/maps/test_sedonakepler_visualization.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-581. The PR name follows the format `[SEDONA-XXX] my subject`.
- Drop the raster column if it exists to prevent serialization errors with Kepler.
- Add unit tests

[SEDONA-581] SedonaKepler fails to reload if a raster column exists

---

docs/setup/compile.md
docs/setup/glue.md
mkdocs.yml

I am addressing this github issue: https://github.com/apache/sedona/issues/1399
This PR proposes adding an AWS Glue setup tutorial to the Sedona documentation website
* built and ran the docs site locally.
* followed the tutorial using the wherobots jars in an account other than the one hosting the jars bucket.

[DOCS] add glue tutorial

---

spark/common/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala

- Added default Spark configurations in `TestBaseScala` trait.
- Provided a method `defaultSparkConfig` for default configurations.
- Allowed subclasses to override `sparkConfig` to add or modify Spark configurations.
- Updated initialization of Spark session and Spark context to use the provided configurations.
- Included comments to explain how to override configurations in subclasses.
- Ensured that default configurations are preserved if not overridden by subclasses.
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-568. The PR name follows the …

[SEDONA-568] Refactor TestBaseScala to allow customizable Spark configurations

---

common/src/main/java/org/apache/sedona/common/raster/RasterConstructors.java
common/src/test/java/org/apache/sedona/common/raster/RasterBandAccessorsTest.java
common/src/test/java/org/apache/sedona/common/raster/RasterConstructorsTest.java
spark/common/src/test/scala/org/apache/sedona/sql/rasterIOTest.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-605. The PR name follows the format `[SEDONA-XXX] my subject`.
Fix the code to compute the width and height of the rasterization result. Please refer to the JIRA ticket for a detailed explanation of this problem.
This patch fixes `RS_AsRaster`, `RS_ZonalStats` and `RS_ZonalStatsAll`.
Add new tests for RS_AsRaster, updated assertions for existing RS_AsRaster and zonal stats tests since the bound and width/height will be slightly different from before.
- No, this PR does not affect any public API so no …

[SEDONA-605] Fix rasterization when useGeometryExtent=false

---

python/Pipfile

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-609. The PR name follows the format `[SEDONA-609] my subject`.
Numpy 2.0.0 is released as the major release of numpy on June 16, 2024. As of right now, the pandas version still has compatible with numpy 2.0. So, to avoid issues when installing pandas with pip, you should pin numpy < 2.
All builds should be fixed and run successfully.

[SEDONA-609] Fix python 3.12 build issue caused by binary compatibility issues with numpy 2.0.0

---

.github/labeler.yml

Labels the `binder` folder.  Best to have all files and folders labeled.
To complete this PR we need to add the new label for `binder` on the repo issues page:
https://github.com/apache/sedona/labels
Ran locally:

[DOCS] Label the `binder` directory with the PR labeler

---

spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/raster/RasterFileFormat.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-611. The PR name follows the format `[SEDONA-XXX] my subject`.
Fix writing rasters to S3 on EMR by re-using the FileSystem object instead of creating new instances. Re-using the FileSystem instance is a common pattern, while creating new FileSystem instances is prone to errors, since some implementations hold transient state required by follow-up operations, and that transient states cannot be accessed by newly created instances.
Passing existing tests, testing manually on emr-7.1.0.
- No, this PR …

[SEDONA-611] Fix writing rasters to S3 on EMR

---

.asf.yaml
.github/linters/.yaml-lint.yml
.github/linters/codespell.txt
.github/workflows/docker-build.yml
.github/workflows/docs.yml
.github/workflows/example.yml
.github/workflows/java.yml
.github/workflows/python-extension.yml
.github/workflows/python-wheel.yml
.github/workflows/python.yml
.github/workflows/r.yml
.pre-commit-config.yaml
R/_pkgdown.yml

https://github.com/adrienverge/yamllint
https://yamllint.readthedocs.io/en/stable/
https://yamllint.readthedocs.io/en/stable/integration.html#integration-with-pre-commit
https://yamllint.readthedocs.io/en/stable/rules.html
Also ran `pre-commit autoupdate` to update the hooks.
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-613. The PR name follows the format `[SEDONA-XXX] my subject`.
Added another check or test to our pre-commit framework for YAML files.  Linted some YAML files as well.
Ran locally: …

[SEDONA-613] Add pre-commit hook `yamllint`

---

docs/setup/glue.md

AWS Glue supports pulling jars from urls, not just S3, so I have revised the Glue tutorial to use links to maven rather than having users stage jars in s3. This is simpler for users.
- build site and visually reviewed
- followed instructions from tutorial to ensure they work

[DOCS] AWS Glue Tutorial: replace s3 instructions with maven links

---

flink/src/test/java/org/apache/sedona/flink/FunctionTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-621. The PR name follows the format `[SEDONA-XXX] my subject`.
Cleaned up some Java code.

[SEDONA-621] Remove redundant call to `toString()`

---

docs/api/sql/Visualization_SedonaPyDeck.md
python/sedona/maps/SedonaPyDeck.py
python/tests/maps/test_sedonapydeck.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-622. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add type error if a user provides a non-numeric column to 
create_choropleth_map's plot_col parameter.
- Add a `stroked` parameter to let the user decide if they want their polygons/points to have a border.
- Passed existing tests

[SEDONA-622] Improve SedonaPyDeck behavior

---

spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/DistanceJoinExec.scala
spark/common/src/test/scala/org/apache/sedona/sql/SpatialJoinSuite.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-624. The PR name follows the format `[SEDONA-XXX] my subject`.
The query plan canonicalization phase creates temporary physical nodes whose attributes cannot be bound to relations, and then calls withNewChildren to replace the bad relations with the correct relations. `DistanceJoinExec` binds distance expression to the relation eagerly, which makes the physical node creation fail. We change the reference binding to be lazily evaluated to get rid of this problem.
Add new tests that would fail without …

[SEDONA-624] Bind references in distance expression to relations lazily to avoid exception in query plan canonicalization

---

common/src/main/java/org/apache/sedona/common/Constructors.java
common/src/main/java/org/apache/sedona/common/Functions.java
common/src/main/java/org/apache/sedona/common/FunctionsGeoTools.java
common/src/main/java/org/apache/sedona/common/geometryObjects/Circle.java
common/src/main/java/org/apache/sedona/common/geometrySerde/GeometrySerializer.java
common/src/main/java/org/apache/sedona/common/raster/GeometryFunctions.java
common/src/main/java/org/apache/sedona/common/simplify/BaseSimplifier.java
common/src/main/java/org/apache/sedona/common/simplify/GeometryCollectionSimplifier.java
common/src/main/java/org/apache/sedona/common/simplify/LineStringSimplifier.java
common/src/main/java/org/apache/sedona/common/simplify/PolygonSimplifier.java
common/src/main/java/org/apache/sedona/common/subDivide/GeometrySubDivider.java
common/src/main/java/org/apache/sedona/common/subDivide/PivotFinder.java
common/src/main/java/org/apache/sedona/common/utils/FormatUtils.java
common/src/main/java/org/apache/sedona/common/utils/GeomUtils.java
common/src/main/java/org/apache/sedona/common/utils/GeometryForce3DTransformer.java
common/src/main/java/org/apache/sedona/common/utils/H3Utils.java
common/src/test/java/org/apache/sedona/common/ConstructorsTest.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/sql/Constructor.md
flink/src/main/java/org/apache/sedona/flink/expressions/Constructors.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/GeometrySerde.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Constructors.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_constructors.scala
spark/common/src/test/scala/org/apache/sedona/sql/PreserveSRIDSuite.scala
spark/common/src/test/scala/org/apache/sedona/sql/constructorTestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-626. The PR name follows the format `[SEDONA-XXX] my subject`.
This PR makes geometries returned by ST functions having correct SRIDs.
* For geometry manipulation functions, the SRID of the output geometry should be the same as the input geometry.
* For `ST_Transform`, the SRID of the output geometry is determined by the target CRS.
Aggregation functions are not changed, making them behave correctly requires collecting the SRIDs of input geometries, which requires significant changes to the …

[SEDONA-626] Make ST functions return geometries with correct SRIDs

---

python/tests/sql/test_dataframe_api.py
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/sedona/sql/UDF/UdfRegistrator.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/AggregateFunctions.scala
spark/common/src/test/scala/org/apache/sedona/sql/aggregateFunctionTestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala

Switch to JTS `OverlayNGRobust.union` function to perform geometry union and add geometry cache capability.
https://locationtech.github.io/jts/javadoc/org/locationtech/jts/operation/overlayng/OverlayNGRobust.html
All existing unit tests should pass.

[SEDONA-630] Improve ST_Union_Aggr performance

---

docs/api/sql/Raster-writer.md
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/raster/RasterFileFormat.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/raster/RasterOptions.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasterIOTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-632. The PR name follows the format `[SEDONA-XXX] my subject`.
Writing large amounts of raster files to distributed file systems or object store is super slow, because the output committer has to move files from temporary locations to their target locations. Users will see all the tasks are completed but the driver is stuck at the committing phase.
This patch an option `useDirectCommitter` to the raster format. By default `useDirectCommitter` is true, and the raster format will use a direct committer …

[SEDONA-632] Use direct committer when writing raster files using `df.write.format("raster")`

---

python/sedona/sql/__init__.py
python/sedona/sql/st_aggregates.py
python/sedona/sql/st_constructors.py
python/sedona/sql/st_functions.py
python/sedona/sql/st_predicates.py
python/tests/sql/test_st_function_imports.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-628. The PR name follows the format `[SEDONA-XXX] my subject`.
Bug fix so that importing st dataframe functions works as documented
added a unit test
Specifically, this change aligns functionality with existing documented API

[SEDONA-628] fix python st df function imports from sedona.sql

---

python/sedona/sql/st_functions.py
python/tests/sql/test_st_function_imports.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-545. The PR name follows the format `[SEDONA-XXX] my subject`.
Fix a problem introduced by https://github.com/apache/sedona/pull/1371, `from sedona.spark import GeometryType` imports the GeometryType function defined in st_functions rather than `sedona.sql.types.GeometryType`. 
Add a new test that imports GeometryType from sedona.spark and verify that it should be a user-defined type.

[SEDONA-545] Fix importing GeometryType from sedona.spark

---

docs/api/flink/Constructor.md
docs/api/snowflake/vector-data/Constructor.md
docs/api/sql/Constructor.md

Explicitly state that `ST_GeomFromGML` only supports GML 1 and GML 2. GML 3 is not supported
Viewed locally using `mkdocs serve`.

[DOCS] State that ST_GeomFromGML only supports GML 1 and GML 2.

---

docs/api/sql/Optimizer.md
spark/common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetSpatialFilter.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/optimization/SpatialFilterPushDownForGeoParquet.scala
spark/spark-3.0/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetFileFormat.scala
spark/spark-3.0/src/test/scala/org/apache/sedona/sql/GeoParquetSpatialFilterPushDownSuite.scala
spark/spark-3.0/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala
spark/spark-3.4/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetFileFormat.scala
spark/spark-3.4/src/test/scala/org/apache/sedona/sql/GeoParquetSpatialFilterPushDownSuite.scala
spark/spark-3.4/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetFileFormat.scala
spark/spark-3.5/src/test/scala/org/apache/sedona/sql/GeoParquetSpatialFilterPushDownSuite.scala
spark/spark-3.5/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-637. The PR name follows the format `[SEDONA-XXX] my subject`.
Spatial filters pushed down to the GeoParquet scan node are visible in the query plan. For example, the following query
```python
df.where("ST_Intersects(geometry, ST_Point(1, 1))").explain()
```
Produces the following query plan
```
== Physical Plan ==
Filter (isnotnull(geometry#218) AND  **org.apache.spark.sql.sedona_sql.expressions.ST_Intersects**  )
+- FileScan geoparquet [id#217L,geometry#218,bbox#219] Batched: false, DataFilters: …
```

[SEDONA-637] Show spatial filters pushed to GeoParquet scans in the query plan; allow disabling spatial filter pushdown

---

common/src/main/java/org/apache/sedona/common/utils/TelemetryCollector.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-638. The PR name follows the format `[SEDONA-XXX] my subject`.
The telemetry collector sends requests to the scarf server synchronously, which may block the initialization of SedonaContext when internet access is restricted (see https://github.com/apache/sedona/issues/1512). This PR sends the telemetry requests in a separate thread to avoid blocking the SedonaContext initialization.
Tested manually. Internet access restriction was simulated using iptables.
- No, this PR does not affect any public API …

[SEDONA-638] Submit telemetry asynchronously without blocking the initialization of SedonaContext

---

common/src/main/java/org/apache/sedona/common/utils/GeometrySplitter.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-639. The PR name follows the format `[SEDONA-XXX] my subject`.
The algorithm we used before computes the intersection points of the input and the blade and splits the input using the intersection points. The problem is that the intersection point may not perfectly lie on the input LineString due to precision issues of the overlay algorithm, so the input LineString won't be split correctly.
This PR uses a more robust algorithm for splitting LineStrings using LineString blades. It simply computes the …

[SEDONA-639] Fix GeometrySplitter accuracy issues when splitting LineStrings

---

spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/AggregateFunctions.scala
spark/common/src/test/scala/org/apache/sedona/sql/aggregateFunctionTestScala.scala

This PR fixes the ENCODER_NOT_FOUND error for ST_Union_Aggr outputEncoder

[SEDONA-630] Fix the ENCODER_NOT_FOUND error for ST_Union_Aggr outputEncoder

---

R/DESCRIPTION
R/R/dependencies.R

Adapting the package to the split of the shaded vars by version. Before it would always call jar 3.0_2.12, now it gets 3.1, 3.2 etc. accordingly
Tested locally, R tests and github actions can't capture this because of the development version that is being tested by those

[SEDONA-642] R - Update to jar naming logic

---

docs/api/flink/Constructor.md
docs/api/snowflake/vector-data/Constructor.md
flink/src/main/java/org/apache/sedona/flink/expressions/Constructors.java
flink/src/test/java/org/apache/sedona/flink/ConstructorTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-643. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add the missing function signatures
- Add docs for the new signatures
- Remove redundant ST_GeomFromEWKB docs
- add new tests

[SEDONA-643] [DOCS] Fix Flink constructor functions signatures & remove redundant docs

---

spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Constructors.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/InferredExpression.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Predicates.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/collect/ST_Collect.scala
spark/common/src/test/scala/org/apache/sedona/sql/constructorTestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-607. The PR name follows the format `[SEDONA-XXX] my subject`.
This patch is based on https://github.com/apache/sedona/pull/1525, it generates enhanced error messages when the input arguments of geometry functions are not literal. The input arguments may help troubleshoot the cause of the errors.
Note: we originally planned to extract auxiliary fields from input rows and attach them to the error messages, but actually this is hard to implement since we don't know the types of columns that are not part …

[SEDONA-607] Fix error message enhancements for geometry functions

---

spark/common/src/main/java/org/apache/sedona/viz/core/ColoringRule.java
spark/common/src/main/java/org/apache/sedona/viz/core/VisualizationOperator.java
spark/common/src/main/java/org/apache/sedona/viz/extension/coloringRule/GenericColoringRule.java
spark/common/src/main/java/org/apache/sedona/viz/extension/coloringRule/LinearFunction.java
spark/common/src/main/java/org/apache/sedona/viz/extension/coloringRule/PiecewiseFunction.java
spark/common/src/main/java/org/apache/sedona/viz/extension/visualizationEffect/ChoroplethMap.java
spark/common/src/main/java/org/apache/sedona/viz/extension/visualizationEffect/HeatMap.java

normailized -> normalized
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-649. The PR name follows the format `[SEDONA-XXX] my subject`.
Fixed spelling.

[SEDONA-649] Fix spelling in Java files

---

docs/setup/databricks.md

Fixed the path of the workspace init script.
Previewed the doc site locally

[DOCS] Fix minor issues of Databricks setup guide based on my recent experience

---

spark/spark-3.0/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefilePartition.scala
spark/spark-3.0/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefilePartitionReaderFactory.scala
spark/spark-3.0/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefileScan.scala
spark/spark-3.1/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefilePartition.scala
spark/spark-3.1/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefilePartitionReaderFactory.scala
spark/spark-3.1/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefileScan.scala
spark/spark-3.2/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefilePartition.scala
spark/spark-3.2/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefilePartitionReaderFactory.scala
spark/spark-3.2/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefileScan.scala
spark/spark-3.3/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefilePartition.scala
spark/spark-3.3/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefilePartitionReaderFactory.scala
spark/spark-3.3/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefileScan.scala
spark/spark-3.4/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefilePartition.scala
spark/spark-3.4/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefilePartitionReaderFactory.scala
spark/spark-3.4/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefileScan.scala
spark/spark-3.5/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefilePartition.scala
spark/spark-3.5/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefilePartitionReaderFactory.scala
spark/spark-3.5/src/main/scala/org/apache/sedona/sql/datasources/shapefile/ShapefileScan.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-646. The PR name follows the format `[SEDONA-XXX] my subject`.
`org.apache.spark.sql.execution.datasources.FilePartition` on DBR is not binary compatible with the open-source Apache Spark, so we define our own `InputPartition` subclass to get rid of this problem.
Manually tested on DBR 15.4 LTS.

[SEDONA-646] Fix DBR compatibility problem for shapefile reader

---

docker/sedona-spark-jupyterlab/requirements.txt

Resolves #1572
- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-609. The PR name follows the format `[SEDONA-XXX] my subject`.
Use numpy v1 inside container to prevent issues with (geo)pandas, see https://github.com/apache/sedona/issues/1572
Built image and ran `python3 -c 'import pandas as pd'`.

[SEDONA-609] Pin numpy to v1

---

docs/api/sql/NearestNeighbourSearching.md

Update knn join documents for filter pushdown.
doc only

[DOC] Update docs to explain the case of filtering after KNN

---

python/Pipfile

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-650. The PR name follows the format `[SEDONA-XXX] my subject`.
fixing the fiona version so that the integration between geopandas and fiona is not broken in python 3.8
unit tests. They detected this issue originally as well.

[SEDONA-650] keep fiona version below 1.10.0

---

docs/api/sql/Parameter.md
spark/common/src/main/java/org/apache/sedona/core/utils/SedonaConf.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-651. The PR name follows the format `[SEDONA-651] my subject`.
Add the `spark` prefix to all existing configs and allow them to co-exist in the config.
Users can set via both methods `sedona.` or `spark.sedona.` but when both options present, the parameter set through `sedona` prefix will override the parameter set through `spark.sedona` prefix.
Passed existing tests

[SEDONA-651] Add spark prefix to all sedona spark config

---

common/src/main/java/org/apache/sedona/common/raster/RasterBandEditors.java
common/src/test/java/org/apache/sedona/common/raster/RasterBandEditorsTest.java
docs/api/sql/Raster-operators.md
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/raster/RasterBandEditors.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-653. The PR name follows the format `[SEDONA-XXX] my subject`.
Add an optional lenient parameter to `RS_Clip`. The default value is true. When lenient is set to true, `RS_Clip` won't throw exceptions when the raster and geometry do not intersect, but return NULL instead.
Passing newly added tests.

[SEDONA-653] Add a lenient mode for RS_Clip and make it lenient by default

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/snowflake/vector-data/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
python/tests/sql/test_function.py
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctions.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsV2.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFsV2.java
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-654. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add ST_RotateY
- Add new unit tests

[SEDONA-654] Add ST_RotateY

---

common/src/main/java/org/apache/sedona/common/Predicates.java
docs/api/sql/NearestNeighbourSearching.md
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
spark/common/src/test/scala/org/apache/sedona/sql/KnnJoinSuite.scala

This PR prevents users to spark optimizer to use ST_KNN or ST_AKNN is used as UDF.
KnnJoinSuite

[SEDONA-648] Throw unsupported operation exception when ST_KNN is used as UDF

---

.pre-commit-config.yaml
docs/usecases/contrib/PostgresqlConnectionApacheSedona.ipynb

Updated the pre-commit hooks and fixed a Python lint error.
First updated the `pre-commit` config and then ran locally:
- `git add .`
- `pre-commit run --all-files`
which produced an error from `ruff` for Python `E402` seen in the image below:
Then fixed the lint error and ran:
- `git add .`
- `pre-commit run --all-files` again

[DOCS] pre-commit autoupdate; fix Python lint error

---

mkdocs.yml

Add the following line in features to enable code copying feature:
- content.code.copy
The code sections should have  a copy button as the following attached image.

[DOCS] Update mkdocs.yml with code copying feature for website

---

docs/api/sql/Optimizer.md
docs/community/contributor.md
docs/community/publication.md
docs/community/release-manager.md
docs/community/rule.md
docs/setup/databricks.md
docs/tutorial/raster.md
docs/tutorial/snowflake/sql.md
docs/tutorial/sql-pure-sql.md
docs/tutorial/zeppelin.md

Standardized whitespace and fixed word capitalization. 

[DOCS] Standardize whitespace in Markdown files

---

.pre-commit-config.yaml

https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#check-docstring-first
Adds another check/test to our pre-commit framework.
Ran locally:

[DOCS] Add pre-commit hook `check-docstring-first`

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/snowflake/vector-data/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
python/tests/sql/test_function.py
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctions.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsV2.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFsV2.java
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
spark/common/src/test/scala/org/apache/sedona/sql/PreserveSRIDSuite.scala
spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-658. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add ST_Simplify
- Add new unit tests

[SEDONA-658] Add ST_Simplify

---

docs/api/sql/Raster-writer.md

The example to write raster dataframe as GeoTIFF files are incorrect. This PR fixes the examples.
Manually verified the correctness of the examples locally; viewed the rendered doc locally.
- This is a documentation update.

[DOCS] Fix the examples in the documentation of raster writer

---

.pre-commit-config.yaml

https://github.com/pre-commit/pre-commit-hooks/releases/tag/v5.0.0
pre-commit-hooks now requires pre-commit>=3.2.0
https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#check-illegal-windows-names
Added another check/test to our pre-commit framework and updated the hooks
Ran locally: `pre-commit run --all-files`

[DOCS] Upgrade pre-commit min version; add hook; pre-commit autoupdate

---

.pre-commit-config.yaml

https://github.com/gitleaks/gitleaks
Adding another check/test to our pre-commit framework.
gitleaks is a popular tool that helps with security.
Added another pre-commit hook for testing.
Ran locally `pre-commit run --all-files`

[CI] Add pre-commit hook `gitleaks` to detect and prevent hardcoded secrets

---

common/src/main/java/org/apache/sedona/common/utils/GeomUtils.java
common/src/main/java/org/apache/sedona/common/utils/H3Utils.java

[DOCS] Fix spelling in Java files

---

spark/common/src/main/scala/org/apache/sedona/sql/utils/Adapter.scala
spark/common/src/main/scala/org/apache/sedona/sql/utils/RasterSerializer.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastQuerySideKNNJoinExec.scala
spark/common/src/test/scala/org/apache/sedona/sql/SpatialJoinSuite.scala
spark/common/src/test/scala/org/apache/sedona/sql/constructorTestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/predicateTestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- No
Cleaned up some Scala files.

[DOCS] Remove unneeded trailing semicolons from Scala files

---

.github/linters/.yaml-lint.yml
R/_pkgdown.yml
mkdocs.yml

https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments
https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments_indentation
- No.
Enabled checking for two more rules for our YAML linter.
Ran locally: `pre-commit run --all-files`

[CI] Enable `yamllint` rules `comments` and `comments-indentation`

---

.pre-commit-config.yaml
pyproject.toml

https://github.com/PyCQA/bandit
https://bandit.readthedocs.io/en/latest/start.html#version-control-integration
https://bandit.readthedocs.io/en/latest/config.html
This PR is skipping four bandit tests.
https://bandit.readthedocs.io/en/latest/plugins/index.html#complete-test-plugin-listing
- No.
Added another check/test to our pre-commit framework.
Currently skipping 4 bandit checks and we can address these issues if needed in follow up PRs.
None of the 4 skipped checks were reported as high security.
B608 has been skipped it was reported as a possible medium …

[CI] Add pre-commit hook `bandit` to find Python security issues

---

docker/sedona-spark-jupyterlab/requirements.txt
docker/sedona-spark-jupyterlab/sedona-jupyterlab.dockerfile

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-665. The PR name follows the format `[SEDONA-665] my subject`.
Ping rasterio version to < 1.4.0 in Docker.
Ubuntu 22.04 comes with GDAL 3.4.1 but rasterio 1.4.0+ requires GDAL 3.5. This leads to the failure of recent docker build.

[SEDONA-665] Ping rasterio version to < 1.4.0 in Docker

---

.pre-commit-config.yaml
python/src/geomserde_speedup_module.c
python/src/pygeos/c_api.h

https://clang.llvm.org/docs/ClangFormat.html
https://clang.llvm.org/docs/ClangFormatStyleOptions.html#basedonstyle
Standardizes the C code to one consistent format.
https://github.com/pre-commit/mirrors-clang-format
https://github.com/ssciwr/clang-format-wheel
- No.
Ran ClangFormat.
From the repo root on Linux I ran:
`find python/ -name *.c -o -name *.h | xargs clang-format -i --style=Google`

 [CI] Add pre-commit hook ClangFormat; format C files with style `Google`

---

docs/api/stats/sql.md
docs/tutorial/sql.md
python/sedona/stats/outlier_detection/__init__.py
python/sedona/stats/outlier_detection/local_outlier_factor.py
python/tests/stats/test_local_outlier_factor.py
spark/common/src/main/scala/org/apache/sedona/stats/outlierDetection/LocalOutlierFactor.scala
spark/common/src/test/scala/org/apache/sedona/sql/TestBaseScala.scala
spark/common/src/test/scala/org/apache/sedona/stats/outlierDetection/LocalOutlierFactorTest.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-661. The PR name follows the format `[SEDONA-XXX] my subject`.
This PR add a Local Outlier Factor function to the scala and python APIs
unit tests. I have performed some benchmarking to check for reasonable scalability 
TODO

[SEDONA-661] add local outlier factor implementation.

---

docs/community/contributor.md

Some changes are:
- word capitalization
- fixing table layouts
- ordering the PMC list
- minor fixups in wording
- No:
Clean up the contributors page.

[DOCS] Clean up the community contributors page

---

.github/workflows/docker-build.yml

- No:
1. `macos-12` is being deprecated by GitHub and starts to break sometimes: https://github.com/actions/runner-images/issues/10721
2. Recent QEMU release 9.10 breaks the Colima runtime on both macos and macos 13 (see https://github.com/douglascamata/setup-docker-macos-action/issues/37, and https://github.com/douglascamata/setup-docker-macos-action/issues/41).
After numerous attempts, the MacOS build sometimes can finish now but still occasionally crash. Therefore, this PR will remove macos build and we plan to add it …

[CI] Remove macos from Docker build

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/snowflake/vector-data/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
python/tests/sql/test_function.py
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctions.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsV2.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFsV2.java
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
spark/common/src/test/scala/org/apache/sedona/sql/PreserveSRIDSuite.scala
spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-666. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add ST_Scale and ST_ScaleGeom
- Passed new Tests

[SEDONA-666] add ST_Scale and ST_ScaleGeom

---

docker/sedona-spark-jupyterlab/requirements.txt
docs/community/contributor.md

- No:
Added John as committer and did some fixups
Checking Whimsy Sedona roster
https://whimsy.apache.org/roster/committee/sedona

[DOCS] Add `John Bampton` as `Committer`

---

docs/community/contributor.md

Gitter is no longer available and new conversations are held on Discord.
- No:

[DOCS] Change Gitter to Discord

---

spark/spark-3.4/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetFileFormat.scala
spark/spark-3.4/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetRowConverter.scala
spark/spark-3.4/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetSchemaConverter.scala
spark/spark-3.4/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetWriteSupport.scala
spark/spark-3.4/src/test/scala/org/apache/sedona/sql/geoparquetIOTests.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetRowConverter.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetSchemaConverter.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetWriteSupport.scala
spark/spark-3.5/src/test/scala/org/apache/sedona/sql/geoparquetIOTests.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-669. The PR name follows the format `[SEDONA-XXX] my subject`.
Ports code for supporting the TimestampNTZ type added since Spark 3.4 to GeoParquet code, so that GeoParquet reader/writer won't throw exceptions when reading/writing parquet files containing timestamp_ntz columns.
* Added a new test case for testing the timestamp_ntz data type.
* Tested on DBR 15.4 LTS to ensure no binary compatibility issues were introduced. …

[SEDONA-669] Fix timestamp_nz for GeoParquet reader and writer

---

spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/geojson/GeoJSONFileFormat.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/geojson/SparkCompatUtil.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-670. The PR name follows the format `[SEDONA-XXX] my subject`.
This PR works around an internal method incompatibility between open-source Apache Spark and DBR. The readFile method defined by open-source Apache Spark is:
```scala
def readFile(
conf: Configuration,
file: PartitionedFile,
parser: JacksonParser,
schema: StructType): Iterator[InternalRow]
```
While this function on DBR takes an extra `Option[_]` parameter:
```scala
def readFile(
conf: Configuration,
file: PartitionedFile,
parser: …
```

[SEDONA-670] Fix GeoJSON reader for DBR

---

.github/workflows/license-templates/LICENSE.txt
.pre-commit-config.yaml
pyproject.toml

refs #1647
- No:
This PR adds another check/test/hook to our pre-commit framework
So far just targets TOML files.
Using pre-commit we can auto add license headers to files on `git commit` or when running `pre-commit run --all-files`
Tested with pre-commit both before and after the license header was added.

[CI] pre-commit: auto add license templates to headers of TOML files

---

.pre-commit-config.yaml

This PR fully removes the commented out `isort` code
- No
refs #1665 

Remove `isort` from the `.pre-commit-config.yaml`

---

.asf.yaml
.github/dependabot.yml
.github/labeler.yml
.github/linters/.markdown-lint.yml
.github/linters/.yaml-lint.yml
.github/workflows/docker-build.yml
.github/workflows/docs.yml
.github/workflows/example.yml
.github/workflows/first-interaction.yml
.github/workflows/java.yml
.github/workflows/labeler.yml
.github/workflows/lint.yml
.github/workflows/python-extension.yml
.github/workflows/python-wheel.yml
.github/workflows/python.yml
.github/workflows/r.yml
.pre-commit-config.yaml
R/_pkgdown.yml
mkdocs.yml

refs #1647 
refs #1657 
- No:
Using pre-commit to auto add license headers to all YAML files.
Ran `pre-commit run --all-files` before and after the license headers were added.

[CI] pre-commit: auto add license headers to all YAML files

---

common/src/main/java/org/apache/sedona/common/sphere/Spheroid.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-672. The PR name follows the format `[SEDONA-XXX] my subject`.
ST_LengthSpheroid didn't consider Polygons with holes (interior rings). This bug fix addresses that issue.
Eg:
WKT:
```
POLYGON((-122.33 47.61, -122.32 47.62, -122.31 47.61, -122.30 47.62, -122.29 47.61, -122.30 47.60, -122.31 47.59, -122.32 47.60, -122.33 47.61), (-122.315 47.605, -122.305 47.615, -122.295 47.605, -122.305 47.595, -122.315 47.605))
```
old output:                   `17363.913692009628`
output after changes: …

[SEDONA-672] Bug fix for ST_LengthSpheroid 

---

.github/workflows/docs.yml
.github/workflows/java.yml
.github/workflows/python-wheel.yml
.github/workflows/r.yml

- No:
> actions/upload-artifact@v3 is scheduled for deprecation on November 30, 2024. [Learn more.](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) Similarly, v1/v2 are scheduled for deprecation on June 30, 2024. Please update your workflow to use v4 of the artifact actions. This deprecation will not impact any existing versions of GitHub Enterprise Server being used by customers.
Use upload-artifact v4. The Python cross-platform build code was copied from cibuildwheel github …

[CI] Upgrade upload-artifact to v4

---

python/tests/serialization/test_serializers.py

- No.
Fixed a typo
https://www.merriam-webster.com/thesaurus/inferable

[DOCS] Fix spelling in a Python file

---

python/sedona/raster/sedona_raster.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-674. The PR name follows the format `[SEDONA-XXX] my subject`.
There are 2 changes in this PR:
1. Specify `GDAL_MEM_ENABLE_OPEN=YES` when opening the MEM:: dataset. This is required since GDAL 3.10. See https://gdal.org/en/latest/drivers/raster/mem.html for details.
2. Use the `SPATIALREFERENCE` parameter to load MEM:: dataset when using GDAL 3.7 or later. This is a better way of attaching CRS information for in-memory raster data.
* Passing existing tests.
* GDAL 3.10 is tested manually in local …

[SEDONA-674] Update the sedona-raster python module to support GDAL 3.10

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-675. The PR name follows the format `[SEDONA-XXX] my subject`.
- This PR implements ST_InterpolatePoint
- ST_InterpolatePoint returns the interpolated measure value of a linear measured LineString at the point closest to the specified point.

[SEDONA-675] Add ST_InterpolatePoint

---

common/src/main/java/org/apache/sedona/common/geometrySerde/GeometrySerde.java
common/src/test/java/org/apache/sedona/common/geometrySerde/EnvelopeSerdeTest.java

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-677. The PR name follows the format `[SEDONA-XXX] my subject`.
Fix the deserialization of null envelopes. Null envelopes won't be deserialized as valid unit envelopes after applying this fix.
Passing newly added tests.

[SEDONA-677] Fix kryo deserialization of null envelopes

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/main/java/org/apache/sedona/common/sphere/Spheroid.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/snowflake/vector-data/Function.md
docs/api/sql/Function.md
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctions.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsV2.java
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-679. The PR name follows the format `[SEDONA-XXX] my subject`.
- Removes support for polygonal geometries in ST_Length and ST_Length2D
- ST_Perimeter is for Polygonal geometries.
- Passed CI

[SEDONA-679] Fix ST_LengthSpheroid behavior

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/snowflake/vector-data/Function.md
docs/api/sql/Function.md
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/tests/sql/test_function.py
python/tests/streaming/spark/test_constructor_functions.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-678. The PR name follows the format `[SEDONA-XXX] my subject`.
- Removes support for polygonal geometries in ST_Length and ST_Length2D
- ST_Perimeter is for Polygonal geometries.
- Passed CI

[SEDONA-678] Fix ST_Length and ST_Length2D behavior

---

.github/workflows/python.yml
docs/tutorial/raster.md
python/sedona/sql/types.py
python/setup.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-680. The PR name follows the format `[SEDONA-680] my subject`.
This is to address several issues reported by users: #1688 #1574 #1607 
1. Move rasterio dependency to optional dependencies
2. Add explanation in doc

[SEDONA-680] Remove rasterio from mandatory dependencies

---

pom.xml

[SEDONA-681] Bump GeoTools version from 28.2 to 28.5

---

docs/community/publish.md
docs/setup/release-notes.md
mkdocs.yml
python/tests/stats/__init__.py

- No:
1. Added release notes for 1.7.0
2. Added the missing header

[DOCS] Prepare release notes for Sedona 1.7.0

---

R/DESCRIPTION
R/R/dependencies.R
python/sedona/version.py
zeppelin/package.json

[DOCS] Bump Sedona Python, R and Zeppelin version to 1.7.0

---

.github/workflows/java.yml
spark/spark-3.3/src/main/scala/org/apache/sedona/sql/datasources/geopackage/GeoPackageScanBuilder.scala

Make the source code compile on Spark 3.3 and enable CI to compile it

[SEDONA-682] Sedona Spark 3.3 does not compile on Scala 2.13

---

pom.xml
spark-shaded/pom.xml

* exclude some repetitive dependencies, https://github.com/apache/sedona/issues/1584

[SEDONA-682] exclude some dependencies.

---

.pre-commit-config.yaml
Makefile

- No:
Using pre-commit to auto add license headers to all Makefile files.
refs #1657 
refs #1674 
refs #1647 
Ran `pre-commit run --all-files` before and after the license headers were added.

[CI] Auto add license to Makefiles with pre-commit

---

pyproject.toml

https://github.com/codespell-project/codespell?tab=readme-ov-file#using-a-config-file
This file has mainly be added for convenience for when running codespell directly on the repo root.
So if you have codespell installed locally you can run `codespell` and it will use the config settings.
- No
Ran `codespell` from the repo root.

[DOCS] Add `codespell` to `pyproject.toml`

---

docs/tutorial/sql-pure-sql.md

- No:
Replace the wrong geotools version with sedona.current_geotools

[DOCS] Fix wrong GeoTools link

---

.pre-commit-config.yaml

- No:  - this is a CI update. The PR name follows the format `[CI] my subject`
Remove the R check in pre-commit to make pre-commit always self-contained.
Passed locally

[CI] Revert R check in pre-commit

---

spark/common/src/main/java/org/apache/sedona/core/spatialPartitioning/KDB.java
spark/common/src/test/java/org/apache/sedona/core/spatialOperator/JoinQueryDeduplicationTest.java

https://stackoverflow.com/questions/1082050/linking-to-an-external-url-in-javadoc
Was using IntelliJ IDE and these minor Javadoc issues were listed.
- No:
Small clean up of Javadoc comments.

[DOCS] Standardize Javadoc comments for links

---

docs/api/sql/Function.md
python/sedona/sql/st_functions.py
python/sedona/stats/clustering/dbscan.py
python/sedona/stats/outlier_detection/local_outlier_factor.py
python/sedona/stats/weighting.py
python/tests/sql/test_dataframe_api.py
spark/common/pom.xml
spark/common/src/main/java/org/apache/sedona/core/utils/SedonaConf.java
spark/common/src/main/scala/org/apache/sedona/spark/SedonaContext.scala
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/sedona/stats/Weighting.scala
spark/common/src/main/scala/org/apache/sedona/stats/clustering/DBSCAN.scala
spark/common/src/main/scala/org/apache/sedona/stats/outlierDetection/LocalOutlierFactor.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/GeoStatsFunctions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/optimization/ExtractGeoStatsFunctions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/plans/logical/EvalGeoStatsFunction.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/geostats/EvalGeoStatsFunctionExec.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/geostats/EvalGeoStatsFunctionStrategy.scala
spark/common/src/test/scala/org/apache/sedona/sql/GeoStatsSuite.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-689. The PR name follows the format `[SEDONA-XXX] my subject`.
Adding a SQL Interface for the Geostats functions
Unit tests. I also performed some manual testing in a distributed runtimes with some "real" datasets

[SEDONA-689] Geostats SQL

---

spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastObjectSideKNNJoinExec.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastQuerySideKNNJoinExec.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/KNNJoinExec.scala
spark/common/src/test/scala/org/apache/sedona/sql/KnnJoinSuite.scala

This PR add additional verification to the KNN join queries to make sure that the number of neighbors (k) must be equal or greater than 1. This is to fix the bug reported in SEDONA-688.
The following unit test is added:
KnnJoinSuite::it("KNN Join should verify the correct parameter k is passed to the join function")

[SEDONA-688] Verify KNN parameter K must be equal or larger than 1

---

spark/common/src/main/java/org/apache/sedona/core/joinJudgement/KnnJoinIndexJudgement.java
spark/common/src/main/java/org/apache/sedona/core/knnJudgement/EuclideanItemDistance.java
spark/common/src/main/java/org/apache/sedona/core/knnJudgement/HaversineItemDistance.java
spark/common/src/main/java/org/apache/sedona/core/knnJudgement/SpheroidDistance.java
spark/common/src/main/java/org/apache/sedona/core/spatialOperator/JoinQuery.java
spark/common/src/main/java/org/apache/sedona/core/wrapper/UniqueGeometry.java
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastObjectSideKNNJoinExec.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastQuerySideKNNJoinExec.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/JoinQueryDetector.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/KNNJoinExec.scala
spark/common/src/test/scala/org/apache/sedona/sql/KnnJoinSuite.scala

This PR is to broadcast the query side data to objects and then on the reducing process, group, sort and reduce it to global knn results. We also include an optimization that avoid repartitioning the broadcast side in this task.
New tests are added to KNNJoinSuit.

[SEDONA-690] Optimize query side broadcast knn join

---

docs/tutorial/sql.md
python/sedona/maps/SedonaKepler.py
python/sedona/maps/SedonaMapUtils.py
python/sedona/maps/SedonaPyDeck.py

Documentation or error messages that refer to `sedona[optional-extra]` were updated to `apache-sedona[optional-extra]`.
These changes are in error messages that were not tested.
- Yes, I have only updated the documentation.

[SEDONA-694] Use apache-sedona instead of sedona when referring to pypi Sedona

---

docs/api/flink/Function.md
docs/api/snowflake/vector-data/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
python/tests/sql/test_function.py
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctions.java
snowflake-tester/src/test/java/org/apache/sedona/snowflake/snowsql/TestFunctionsV2.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFsV2.java
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-693. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add ST_Perimeter2D
- fixes #1746 
- add new unit tests

[SEDONA-693] Add ST_Perimeter2D

---

common/src/main/java/org/apache/sedona/common/utils/GeometryDuplicateCoordinateRemover.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-698. The PR name follows the format `[SEDONA-XXX] my subject`.
- fix a bug that doesn't allow Polygon to have 4 coordinates
- add new unit tests

[SEDONA-698] Fix ST_RemoveRepeatedPoints

---

CONTRIBUTING.md

Fixes #1728.
Adds a CONTRIBUTING file, as recommended by GitHub.
N/A.

[DOCS] add contributing file

---

spark/spark-3.3/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataPartitionReaderFactory.scala
spark/spark-3.4/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataPartitionReaderFactory.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/v2/geoparquet/metadata/GeoParquetMetadataPartitionReaderFactory.scala

[SEDONA-699] Fix issue with not closing parquet files.

---

spark/common/src/main/scala/org/apache/sedona/stats/Weighting.scala
spark/common/src/main/scala/org/apache/sedona/stats/clustering/DBSCAN.scala
spark/common/src/main/scala/org/apache/sedona/stats/outlierDetection/LocalOutlierFactor.scala
spark/common/src/main/scala/org/apache/sedona/util/DfUtils.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-697. The PR name follows the format `[SEDONA-XXX] my subject`.
making getGeometryColumnName a public function
unit tests for geostats will still cover this
while technically this function is publicly available in the code now, I'm not sure it warrants being considered a "public API".

[SEDONA-697] Make getGeometryColumnName a public function

---

spark/common/src/main/java/org/apache/sedona/core/spatialPartitioning/quadtree/ExtendedQuadTree.java
spark/common/src/main/scala/org/apache/sedona/sql/utils/GeometrySerializer.scala
spark/common/src/test/scala/org/apache/sedona/sql/KnnJoinSuite.scala

This PR fix the bug that when query side dataset contains null or empty geometries, KNN join fails.
KnnJoinSuite adds two new unit tests

[SEDONA-700] Fix ST_KNN fails on null and empty geometries

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/sql/Function.md
flink/src/main/java/org/apache/sedona/flink/Catalog.java
flink/src/main/java/org/apache/sedona/flink/expressions/Functions.java
flink/src/test/java/org/apache/sedona/flink/FunctionTest.java
python/sedona/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
python/tests/sql/test_function.py
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
spark/common/src/test/scala/org/apache/sedona/sql/PreserveSRIDSuite.scala
spark/common/src/test/scala/org/apache/sedona/sql/dataFrameAPITestScala.scala
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-701. The PR name follows the format `[SEDONA-XXX] my subject`.
- Add ST_LineSegments
- Add new unit tests

[SEDONA-701] Add ST_LineSegments

---

docs/api/sql/Stac.md
spark/common/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
spark/common/src/main/scala/org/apache/sedona/spark/SedonaContext.scala
spark/common/src/main/scala/org/apache/spark/sql/execution/datasource/stac/TemporalFilter.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacBatch.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacDataSource.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacPartition.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacPartitionReader.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacScan.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacScanBuilder.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacTable.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacUtils.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/optimization/SpatialFilterPushDownForGeoParquet.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/optimization/SpatialTemporalFilterPushDownForStacScan.scala
spark/common/src/test/resources/datasource_stac/collection-items.json
spark/common/src/test/resources/datasource_stac/collection.json
spark/common/src/test/resources/datasource_stac/core-item.json
spark/common/src/test/resources/datasource_stac/extended-item.json
spark/common/src/test/resources/datasource_stac/nested/nested-collection.json
spark/common/src/test/resources/datasource_stac/nested/nested-item.json
spark/common/src/test/resources/datasource_stac/nested/nested-items.json
spark/common/src/test/resources/datasource_stac/simple-item.json
spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacBatchTest.scala
spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacDataSourceTest.scala
spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacPartitionReaderTest.scala
spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacTableTest.scala
spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacUtilsTest.scala

This PR adds an STAC (SpatioTemporal Asset Catalog) collection reader to Sedona. The reader will fetch STAC items and load them into a Sedona DataFrame. The data can be sourced from static JSON files, GeoParquet, or external services, such as Earth Search by Element84.
Unit tests under: org.apache.spark.sql.sedona_sql.io.stac

[SEDONA-704] Add the STAC datasource reader

---

.github/workflows/python.yml
python/sedona/sql/dataframe_api.py
python/tests/sql/test_dataframe_api.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-706. The PR name follows the format `[SEDONA-XXX] my subject`.
* Fixes https://github.com/apache/sedona/issues/1771
* Make Spark Connect tests run on GitHub Actions. They were skipped for all Spark versions before, this patch enables the tests for Spark 3.4 and 3.5.
* Add a new multi threaded test that would fail without this patch
* Passing CI

[SEDONA-706] Fix Python dataframe api for multi-threaded environment

---

docs/setup/databricks.md

- No:
https://github.com/apache/sedona/issues/1784 reports that `geopandas==0.11.1` raises an exception when reading files. We should update the PyPI dependency guide to use newer versions of packages.
Manually tested on DBR 15.4 LTS

[DOCS] Update PyPI dependency versions in Databricks Setup guide

---

docs/tutorial/rdd.md
docs/tutorial/sql.md
python/sedona/register/java_libs.py
python/sedona/utils/adapter.py
python/sedona/utils/structured_adapter.py
python/tests/sql/test_structured_adapter.py
spark/common/src/main/java/org/apache/sedona/core/spatialRDD/SpatialRDD.java
spark/common/src/main/scala/org/apache/sedona/sql/utils/Adapter.scala
spark/common/src/main/scala/org/apache/sedona/stats/Weighting.scala
spark/common/src/main/scala/org/apache/sedona/stats/clustering/DBSCAN.scala
spark/common/src/main/scala/org/apache/sedona/stats/outlierDetection/LocalOutlierFactor.scala
spark/common/src/main/scala/org/apache/sedona/util/DfUtils.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/adapters/StructuredAdapter.scala
spark/common/src/test/scala/org/apache/sedona/sql/structuredAdapterTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-703. The PR name follows the format `[SEDONA-XXX] my subject`.
1. Introducing the StructuredAdapter class to smooth the conversion among RDDs, DataFrames, and SpatialRDDs
The following stores InternalRow in geom.userData
* SpatialRDD to DF
* DF to SpatialRDD
* SpatialPairRDD to DF
* SpatialRDD to spatialPartitionedDF
The following stores Row in geom.userData
* SpatialRDD to RowRDD
* RowRDD to SpatialRDD
2. Deprecating the old Adapter class which relies on a string field to serialize objects
3. …

[SEDONA-703] Introducing the StructuredAdapter class

---

docs/tutorial/sql.md
python/sedona/core/SpatialRDD/spatial_rdd.py
python/tests/spatial_rdd/test_spatial_rdd.py
python/tests/sql/test_structured_adapter.py
python/tests/test_base.py
spark/common/src/main/java/org/apache/sedona/core/spatialPartitioning/GenericUniquePartitioner.java
spark/common/src/main/java/org/apache/sedona/core/spatialPartitioning/IndexedGridPartitioner.java
spark/common/src/main/java/org/apache/sedona/core/spatialPartitioning/SpatialPartitioner.java
spark/common/src/main/java/org/apache/sedona/core/spatialRDD/SpatialRDD.java
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/adapters/StructuredAdapter.scala
spark/common/src/test/java/org/apache/sedona/core/spatialPartitioning/GenericUniquePartitionerTest.java
spark/common/src/test/resources/.gitignore
spark/common/src/test/scala/org/apache/sedona/sql/structuredAdapterTestScala.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-705. The PR name follows the format `[SEDONA-705] my subject`.
After SEDONA-695 (https://github.com/apache/sedona/pull/1751), we will have the ability to do partitioned writes! To be useful in most contexts, we also need the ability to create those partitions assigning a unique partition to each feature (i.e., don't introduce duplicates).
- Added a set of `spatialPartitioningWithoutDuplicates()` functions to match `spatialPartitioning()`
- Added a `GenericUniqueSpatialPartitioner` that wraps an …

[SEDONA-705] Add unique partitioner wrapper to enable partitioned writes with Sedona

---

python/sedona/maps/SedonaMapUtils.py
python/sedona/raster_utils/SedonaUtils.py

https://github.com/apache/sedona/pull/1767 introduces an efficient way to get Geopandas DataFrame via PyArrow. This PR is  to utilize this function in SedonaKepler and others.
Pass existing tests

[SEDONA-708] Sedona should use PyArrow to get GeoPandas

---

spark/common/src/main/scala/org/apache/sedona/sql/UDF/AbstractCatalog.scala
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-708. The PR name follows the format `[SEDONA-XXX] my subject`.
This separates out the Catalog class into an Abstract class that holds logic and the Catalog class that holds function definitions. This allows Sedona users to build their own Catalogs with custom ST functions.
Existing unit tests provide coverage
Generally we are not documenting these semi-internal APIs. I can add docstrings if we want

[SEDONA-708] Separate Catalog implementation into AbstractCatalog and Catalog

---

.pre-commit-config.yaml

Under bandit settings it lists the additional dependency for toml files
https://bandit.readthedocs.io/en/latest/config.html#bandit-settings
- No  this is a CI update. The PR name follows the format `[CI] my subject`
Update the hooks.
First ran `pre-commit autoupdate` to update the hooks and then ran `pre-commit run --all-files` and got the error below:
Added the new dependency for TOML files and now pre-commit passes

[CI] pre-commit autoupdate; configure `bandit[toml]` dependency

---

.pre-commit-config.yaml
R/R/apache.sedona-package.R
R/R/bounding_box.R
R/R/data_interface.R
R/R/dependencies.R
R/R/imports.R
R/R/sdf_interface.R
R/R/spatial_index_op.R
R/R/spatial_join_op.R
R/R/spatial_partitioner.R
R/R/spatial_queries.R
R/R/spatial_rdd.R
R/R/viz.R
R/tests/testthat.R
R/tests/testthat/helper-initialize.R
R/tests/testthat/test-apply-spatial-partitioner.R
R/tests/testthat/test-bounding-box.R
R/tests/testthat/test-build-index.R
R/tests/testthat/test-crs-transform.R
R/tests/testthat/test-data-interface-raster.R
R/tests/testthat/test-data-interface.R
R/tests/testthat/test-dbplyr-integration.R
R/tests/testthat/test-init.R
R/tests/testthat/test-sdf-interface.R
R/tests/testthat/test-spatial-join.R
R/tests/testthat/test-spatial-queries.R
R/tests/testthat/test-spatial-rdd-aggregation-fns.R
R/tests/testthat/test-viz.R

Using pre-commit to auto add missing license headers to R files on git commit.
Standardizes the white spacing in the R licenses.
Similar PRs in the past for other file types.
Ran pre-commit run --all-files both before and after the license headers were added.

[CI] pre-commit: standardize and auto add license to R files

---

.pre-commit-config.yaml

Adds another hook that will auto add license headers to files on git commit for `.c` and `.h` files.
We already had the correct license headers in all `.c` and `.h` files so this is just adding a check/test.
This should enforce standards and stop regressions.
Ran pre-commit.

[CI] pre-commit: auto add license headers to `.c` and `.h` files

---

.asf.yaml

https://github.com/apache/infrastructure-asfyaml?tab=readme-ov-file#assigning-the-github-triage-role-to-external-collaborators
"Projects may assign external (non-committer) collaborators the triage role for their repository."
- No
Cleans up the outside collaborators list.
refs #1803 
Committers already have write access and can triage issues and PRs.

.asf.yaml: remove committer jbampton from collaborators

---

Makefile
requirements-docs.txt

This update refactors the docsinstall target in the Makefile to use a predefined requirements-docs.txt file instead of dynamically creating it. This ensures better dependency management, simplifies maintenance, and aligns with best practices for handling Python package installations.

[DOCS] Improve Makefile by Using requirements-docs.txt for Documentation Dependencies

---

.pre-commit-config.yaml

Added another check/hook/test to our pre-commit framework.  This hook will auto add a license header to Java files on git commit if they are missing the license.  So far all Java files seem to have the correct license so this is just a check to stop regressions and keep the code base standardized.  Small piece of automation to auto add missing license headers.
Added the license hook and then ran pre-commit for all files.  No Java files were modified.  I did test by changing / modifying a Java license and it did fail …

[CI] pre-commit: auto add license check for Java files

---

docs/tutorial/files/geojson-sedona-spark.md
docs/tutorial/files/geojson_sedona_spark.md
mkdocs.yml

- No:
Adds a dedicated geojson page to explain how to use this file format with Sedona.
All code snippets were run locally.  It's a docs page.
- Yes, this is a documentation update for existing functionality.

[DOCS] Add geojson docs

---

spark/spark-3.3/src/main/scala/org/apache/sedona/sql/parser/SedonaSqlParser.scala
spark/spark-3.4/src/main/scala/org/apache/sedona/sql/parser/SedonaSqlParser.scala
spark/spark-3.5/src/main/scala/org/apache/sedona/sql/parser/SedonaSqlParser.scala

This PR change the spark parser order to use delegate parser first. 
unit tests all pass

[SEDONA-716] Change the spark parser order to use delegate parser first

---

Makefile
docker/docs/Dockerfile
docs/tutorial/geopandas-shapely.md
python/sedona/utils/geoarrow.py
python/tests/test_base.py
python/tests/utils/test_arrow_conversion_geopandas_to_sedona.py

[SEDONA-714] Add geopandas to spark arrow conversion.

---

docs/tutorial/files/geopackage-sedona-spark.md
docs/tutorial/sql.md
mkdocs.yml

This adds a documentation page for the existing GeoPackage reader.
All code in the post was tested locally.
- Yes, I have updated the documentation for the existing functionality.

[DOCS] add geopackage docs

---

python/sedona/utils/geoarrow.py
python/tests/utils/test_geoarrow.py

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-717. The PR name follows the format `[SEDONA-717] my subject`.
Closes #1815
This PR makes some minor updates to ensure that Arrow collection does not fail for empty results (which can be confusing when, for example, maps are created).
I investigated two other things I have noticed recently involving failed Kepler map renders, but I don't think they are specifically related to Arrow conversion.
- I have noticed a failure `Can't clean for JSON: Decimal('123')`, which I think started to occur because we …

[SEDONA-717] Fix `dataframe_to_arrow()` for zero-row results

---

docs/tutorial/files/geojson-sedona-spark.md
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/geojson/GeoJSONFileFormat.scala
spark/common/src/test/scala/org/apache/sedona/sql/geojsonIOTests.scala

- Yes, the URL of the associated JIRA ticket is https://issues.apache.org/jira/browse/SEDONA-718. The PR name follows the format `[SEDONA-XXX] my subject`.
Currently, the GeoJSON writer will only use the column named "geometry" as the geometry field of the GeoJSON, users have to use `.option("geometry.column", "geom")` to specify other geometry columns. This is very common where a DataFrame contains only `geom` field but not `geometry` field, and we want to support writing such DataFrames as GeoJSON out of box.
We want to make the GeoJSON writer a bit smarter by automatically detecting …

[SEDONA-718] Auto Detect geometry column in GeoJSON writer

---

spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacBatch.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacPartitionReader.scala

- Fix STAC reader option issues when itemsLimitMax is less than the itemsLimitPerRequest
- Add retry logic to the partition reader
unt tests under stac package

[SEDONA-704] Fix STC reader option issues and add retry logic

---

common/src/main/java/org/apache/sedona/common/utils/RasterUtils.java
common/src/test/java/org/apache/sedona/common/raster/FunctionsTest.java
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

The world coordinates were silently casted from double to float when getting world coordinates from grid coordinates. This affects the precision of `RS_RasterToWorldCoord*`, `RS_PixelAsPolygon`, etc.
Updated the expected results of tests to more precise coordinates.

[SEDONA-722] Fix precision loss problems caused by casting world coordinates from double to float

---

docs/tutorial/files/stac-sedona-spark.md
python/sedona/stac/collection_client.py
python/tests/stac/test_client.py
python/tests/stac/test_collection_client.py
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacBatch.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacDataSource.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacPartitionReader.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacScan.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacScanBuilder.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacTable.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/io/stac/StacUtils.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/optimization/SpatialTemporalFilterPushDownForStacScan.scala
spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacBatchTest.scala
spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacDataSourceTest.scala
spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacPartitionReaderTest.scala
spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacUtilsTest.scala

This PR adds a few optimizations to the STAC reader;
- add spatial and temporal to fetching items when stac is loaded from a server
- pass hadoop configuration to the partition reader instead of creating them for each row
- push down limit sql statement when no spatial or temporal filters are used
- push down limit from python api when no spatial or temporal filters are used
- refactor the get_items and get_dataframe function to use a common internal function
- use st_intersects instead of st_contains for python api to be consistent with the …

[SEDONA-704] Optimize STAC reader and fix few issues

---

common/src/main/java/org/apache/sedona/common/raster/RasterBandAccessors.java
common/src/test/java/org/apache/sedona/common/raster/RasterBandAccessorsTest.java
spark/common/src/test/scala/org/apache/sedona/sql/rasteralgebraTest.scala

- Yes, and the PR name follows the format `[SEDONA-724] my subject`.
When the ROI barely intersects with the input raster's extent and the `allTouched` argument is false then this causes the pixel data to be empty. That breaks the zonalMode method which assumes there will be pixel data.
Add better error handling and a shortcut for RS_ZonalStatsAll to skip unnecessary stats compute (saves ~6% time).
- add unit tests

[SEDONA-724] Fix RS_ZonalStats and RS_ZonalStatsAll edge case bug

---

spark/common/src/main/scala/org/apache/sedona/sql/SedonaSqlExtensions.scala

This PR try to inject the Sedona SQL parser but gracefully handle initialization failures.
This prevents extension loading errors from causing the SparkSession initialization to fail, allowing the application to continue running without the Sedona parser extension.
SQL unit tests

[GH-1868] Fix spark sql extension load failure when parser failed to load

---

.asf.yaml

- No:
Recently ASF Infra automated the process of GitHub discussion and hence accidentally disabled all GitHub discussion. This is to re-enable it via .asf.yml

[DOCS] Re-enable GitHub discussion due to ASF Infra change

---

.asf.yaml

- No:
Add a notification target for GitHub Discussion otherwise it won't take effect

[DOCS] Add notification target for GitHub Discussions

---

.pre-commit-config.yaml
examples/spark-sql/src/main/scala/RddExample.scala
examples/spark-sql/src/main/scala/SqlExample.scala
examples/spark-sql/src/main/scala/VizExample.scala

Following on from previous PRs which used pre-commit to auto add licenses headers to files.
A few Scala files seemed to have a different license header format so standardized those.
Bascially another check / hook / test we can have.
Ran `pre-commit run --all-files` before and after the license headers were added.
Visual inspection seems some of these licenses were different.

[CI] pre-commit(scala): auto add and standardize license headers

---

docs/tutorial/concepts/spatial-joins.md
docs/tutorial/files/geojson-sedona-spark.md
docs/tutorial/files/geopackage-sedona-spark.md
docs/tutorial/files/geoparquet-sedona-spark.md
docs/tutorial/files/shapefiles-sedona-spark.md

Formatted some code blocks with black
refs #1797 
Markdown edits only so with visual inspection.

[DOCS] Format Python Markdown codeblocks with black

---

.asf.yaml
.github/linters/.yaml-lint.yml
.github/workflows/docker-build.yml
.github/workflows/docs.yml
.github/workflows/first-interaction.yml
.github/workflows/labeler.yml
.github/workflows/lint.yml
.github/workflows/python.yml
.github/workflows/r.yml
.pre-commit-config.yaml
.prettierignore
.prettierrc
R/_pkgdown.yml
mkdocs.yml

[CI] Add prettier pre-commit hook and format YAML files

---

.github/CODEOWNERS

People with write permissions for the repository can create or edit the CODEOWNERS file and be listed as code owners.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
See the link below for an example of how a CODEOWNERS file works:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file
I am a committer with write access and I work on the …

[CI] Update CODEOWNERS add @jbampton for pre-commit config

---

spark/common/src/main/java/org/apache/sedona/core/monitoring/EnvelopeAccumulator.java

https://github.com/apache/sedona/issues/1886
Add an EnvelopeAccumulator to allow developers to expose the spatial extent of the data in each stage/task to the user through the spark ui.
Manual - Unit Tests to come.

[GH-1886] Create EnvelopeAccumulator class

---

common/src/main/java/org/apache/sedona/common/utils/FormatUtils.java

We use "splitted" a lot more than "splited".
So this PR just makes the usage consistent.
- No
Making spelling of terms consistent.

chore: standardize spelling in Java code

---

.github/CODEOWNERS

The linter config files work with the pre-commit config.
So adding @jbampton as one of the default reviewers.
Added reviewers for the Makefile as well.
An example of how a CODEOWNERS file works:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file

[CI] Update CODEOWNERS add reviewers for linters

---

.pre-commit-config.yaml
python/sedona/core/jvm/config.py
python/sedona/geopandas/base.py
python/sedona/geopandas/geodataframe.py
python/sedona/maps/SedonaPyDeck.py
python/sedona/raster/meta.py
python/sedona/raster/raster_serde.py
python/sedona/sql/dataframe_api.py
python/sedona/utils/decorators.py
python/sedona/utils/geometry_serde.py
python/sedona/utils/geometry_serde_general.py
python/sedona/utils/meta.py
python/setup.py
python/tests/core/test_avoiding_python_jvm_serde_df.py
python/tests/geopandas/test_geodataframe.py
python/tests/geopandas/test_geoseries.py
python/tests/geopandas/test_sjoin.py
python/tests/sql/test_function.py
python/tests/stats/test_dbscan.py

"A tool (and pre-commit hook) to automatically upgrade syntax for newer versions of the language."
https://github.com/asottile/pyupgrade
- No
Added another check/test to our pre-commit framework.
Ran locally: `pre-commit run --all-files`

[CI] Add pre-commit hook `pyupgrade` to auto upgrade Python syntax

---

.github/workflows/java.yml
docs/tutorial/sql.md
python/sedona/sql/functions.py
python/tests/utils/test_pandas_arrow_udf.py
spark/common/src/main/scala/org/apache/sedona/spark/SedonaContext.scala
spark/common/src/main/scala/org/apache/sedona/sql/UDF/PythonEvalType.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategies/SedonaArrowEvalPython.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/udf/ExtractSedonaUDFRule.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/udf/SedonaArrowEvalPython.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/udf/SedonaArrowStrategy.scala
spark/spark-3.5/src/test/scala/org/apache/spark/sql/udf/StrategySuite.scala
spark/spark-3.5/src/test/scala/org/apache/spark/sql/udf/TestScalarPandasUDF.scala

- Yes, `SEDONA-721`.
Sedona vectorized geometry udfs (scalar only now)
unit tests
yes

[SEDONA-721] Add Sedona vectorized udf for Python

---

mkdocs.yml

- No:
This PR adds `referrerpolicy="no-referrer-when-downgrade"` attribute to the tracking pixel. The HTTP request sent by browser will have full URL with path in the Referer header.
`mkdocs serve` locally and observe that the HTTP request has Referer header containing the full URL.

[DOCS] Fix Referer of matomo tracking pixel

---

docs/setup/databricks.md

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #1905.
Databricks runtimes based on Spark 3.5.x are widely used for now, and there have been multiple users encountering spark version mismatch errors when installing Sedona to their DBR cluster. We bump the Spark version in the doc to get rid of similar issues.
Previewed locally

[GH-1905] Increment Spark minor version in Databricks setup guide

---

spark/common/src/main/java/org/apache/sedona/core/joinJudgement/InMemoryKNNJoinIterator.java
spark/common/src/main/java/org/apache/sedona/core/joinJudgement/KnnJoinIndexJudgement.java
spark/common/src/main/java/org/apache/sedona/core/spatialOperator/JoinQuery.java
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastObjectSideKNNJoinExec.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/BroadcastQuerySideKNNJoinExec.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/strategy/join/KNNJoinExec.scala
spark/common/src/test/scala/org/apache/sedona/sql/KnnJoinSuite.scala

This PR change the default distance metric to use Haversine distance when use_spheroid = true. It also refactors the join index judgement code to be more readable.
KNNTestSuit

[SEDONA-690] Set default metric to use Haversine for KNN join and code refactoring

---

python/sedona/geopandas/base.py
python/sedona/geopandas/geodataframe.py
python/sedona/geopandas/geoseries.py

This PR refactor the GeoSeries python wrapper so that the code can be simplified, e.g.,
```
def area(self) -> "GeoSeries":
return self._process_geometry_column("ST_Area", rename="area")
def buffer(
self,
distance,
resolution=16,
cap_style="round",
join_style="round",
mitre_limit=5.0,
single_sided=False,
**kwargs,
):
return self._process_geometry_column(
"ST_Buffer", rename="buffer", distance=distance
)
```
test_geoseries.py

[SEDONA-720] Refactor GeoPandas Series implementation

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java

- https://github.com/apache/sedona/issues/1922
- Check for nullity of geometry in the x/y/z/m functions (common/srcmain/java/org/apache/sedona/common/Functions.java), so that their invocation on empty geometries returns null.
- Created emptyPoint() test on common/src/test/java/org/apache/sedona/common/FunctionsTest.java

[GH-1922] ST_X/Y/Z ON null geometries

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/test/java/org/apache/sedona/common/FunctionsTest.java
docs/api/flink/Function.md
docs/api/snowflake/vector-data/Function.md
docs/api/sql/Function.md
spark/common/src/test/scala/org/apache/sedona/sql/PreserveSRIDSuite.scala
spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala

- https://github.com/apache/sedona/issues/1761
Throws InvalidArgumentException when maxVertices is lower that 5.
- Created 'subdivideInvalidMaxVertices' test in common/src/test/java/org/apache/sedona/common/FunctionsTest.java
- Created test in in spark/common/src/test/scala/org/apache/sedona/sql/functionTestScala.scala
- Yes, I have updated the documentation (ST_Subdivide/ST_SubdivideExplode) in both docs/api/sql/Function.md and docs/api/flink/Function.md

[GH-1761] error when invalid ST_Subdivide maxVertices argument

---

.github/workflows/python-extension.yml

- No:
Reported by @Kontinuation
> Sometimes pipenv goes crazy and creates a virtual environment containing a 32-bit python interpreter. We explicitly specify the python executable to get rid of this issue. I have not found similar issues being reported yet and don't know why pipenv's behavior changed.

[CI] Fix failed Python build extension CI

---

python/sedona/utils/geoarrow.py

Move geopandas import to a type checking block to prevent a hidden dependency on it.
`import sedona.spark` now works

[GH-1910] Import geopandas only when type checking

---

python/sedona/maps/SedonaMapUtils.py

Fixes #1931 
I have moved the import of `packaging.version.parse` to the try-except block that `geopandas` is imported in, as `packaging` is already a dependency of `geopandas`
Local test by successfully running
```py
from sedona.spark import SedonaContext
import pyspark.sql.functions as sf
SedonaContext.create(spark)
spark.range(10).withColumn("geom", sf.expr("ST_POINT(id, id)")).show()
```

[GH-1931] Move packaging module import to geopandas try-except block

---

common/pom.xml
pom.xml
spark-shaded/pom.xml
spark/common/pom.xml

This PR shades jiffle into sedona-common to workaround problems encountered on runtimes with low janino version. Please refer to https://github.com/apache/sedona/discussions/1945 for details.
This PR is mostly taken from https://github.com/apache/sedona/pull/1919, which shades jiffle and antlr. This PR shades janino additionally.
Jiffle should be removed from geotools-wrapper (see https://github.com/jiayuasu/geotools-wrapper/pull/12), since now it is shaded into sedona-common and shipped with sedona-spark-shaded jar.
Tested manually on DBR 15.4 …

[GH-1945] Shade Jiffle and its dependencies

---

.github/workflows/docs.yml
.github/workflows/first-interaction.yml
.github/workflows/pyflink.yml
.github/workflows/python-wheel.yml
.github/workflows/r.yml

[CI] gha: set default workflow permissions

---

python/sedona/spark/maps/SedonaKepler.py

This PR fixes #2002, adding three params to the KeplerGl constructor, including height, use_arrow, and show_docs.
https://docs.kepler.gl/docs/keplergl-jupyter#keplergl

[GH-2002] Add params to KeplerGl constructor

---

docs/setup/compile.md

#2010
Fixes to this page: https://sedona.apache.org/latest/setup/compile
- Update Python and Java version
- Add instructions for installing Spark
- Make it as friendly as possible for readers to simply copy-paste instructions to run
- Move some content to a new line, instead of unintentionally continuing on the previous one.   
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

[DOCS] Fix issues in the Compile Sedona source code page to make it easy to setup dev environment

---

python/sedona/geopandas/geodataframe.py
python/tests/geopandas/test_geodataframe.py

- #2007
Fixed `Geodataframe.__init__()`'s behavior to properly handle Sedona Geopandas and pandas-on-pyspark input types.
Also made it so any column with geometry type is converted to wkb, instead of only gpd.GeoSeries
Added tests

[GH-2007] Geopandas.Dataframe: Fix constructor for pandas-on-pyspark and Sedona Geopandas input types

---

python/sedona/geopandas/geoseries.py
python/tests/geopandas/test_geoseries.py
python/tests/geopandas/test_match_geopandas_series.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2025
Implement is_valid and is_empty
Added tests

[GH-2025] Geopandas.GeoSeries: Implement is_valid, is_empty, is_simple

---

python/sedona/geopandas/geoseries.py
python/tests/geopandas/test_geoseries.py
python/tests/geopandas/test_match_geopandas_series.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2039
- Implement from_wkb, from_wkt, from_xy
- Implement a hacky fix for the` __init__` constructor so it now correctly calls `super().__init__` without failing on the ps.Series or sgpd.Series cases.
Added tests

[GH-2039] Geopandas.GeoSeries: Implement from_wkb, from_wkt, from_xy + temp __init__ fix

---

common/pom.xml
flink-shaded/pom.xml
flink/pom.xml
flink/src/test/java/org/apache/sedona/flink/TestBase.java
pom.xml
snowflake/pom.xml
spark-shaded/pom.xml
spark/common/pom.xml
spark/spark-3.4/pom.xml
spark/spark-3.5/pom.xml
spark/spark-4.0/pom.xml

As discussed in https://github.com/apache/sedona/issues/1996#issuecomment-2995332894, we have switched s2 dependency to our own `org.datasyslab:s2-geometry-library`. This may cause conflicts if there's `com.google.geometry:s2-geometry` packages in the runtime environment. We decided to shade it into runtime jars to get rid of possible conflicts.
`org.datasyslab:s2-geometry-library` depends on a recent version of Guava, which is incompatible with the Guava jar shipped with Apache Spark, so we have to shade guava into runtime jars as well.
We have …

[GH-1996] Shade S2 and Guava into runtime JARs

---

python/sedona/geopandas/geoseries.py
python/tests/geopandas/test_geoseries.py
python/tests/geopandas/test_match_geopandas_series.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2049
- Retain index information in queries (`SPARK_DEFAULT_INDEX_NAME`)
- Select `NATURAL_ORDER_COLUMN_NAME` to prevent having to regenerate it (slight perf improvement)
Added tests
- No, no need. This was fixing buggy behavior.

[GH-2049] Retain index information in query results

---

.github/workflows/java.yml
docs/api/sql/Function.md
python/sedona/spark/sql/st_functions.py
python/tests/sql/test_dataframe_api.py
spark/common/pom.xml
spark/common/src/main/java/org/apache/sedona/core/utils/SedonaConf.java
spark/common/src/main/scala/org/apache/sedona/sql/UDF/Catalog.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/Functions.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/LibPostalUtils.scala
spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/expressions/st_functions.scala
spark/common/src/test/java/org/apache/sedona/core/utils/SedonaConfTest.java
spark/common/src/test/scala/org/apache/sedona/sql/AddressProcessingFunctionsTest.scala
spark/common/src/test/scala/org/apache/sedona/sql/GeoStatsSuite.scala

- Yes, and the PR name follows the format `[GH-2074] my subject`. Closes [#2074](https://github.com/apache/sedona/issues/2074)
This add ExpandAddress and ParseAddress functions backed by libpostal, including support for code gen.
Unit Tests

[GH-2074] Add libpostal integration

---

python/src/geom_buf.c
python/tests/utils/test_geomserde_speedup.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2122 
SRID was not deserialized correctly in the Python extension. This PR fix it.
The new geometry serialization format was introduced before we support Shapely 2.0, Shapely 1.8 does not support SRID back then so SRID serialization in Python extension was only implemented but not tested.
**ATTENTION**: This patch only fixes the C extension (fast implementation), there's a slower fallback implementation in pure Python (https://github.com/apache/sedona/blob/master/python/sedona/spark/utils/geometry_serde_general.py) not supporting …

[GH-2122] Fix deserialization of geometry SRID in python

---

python/sedona/geopandas/geodataframe.py
python/sedona/geopandas/geoseries.py
python/tests/geopandas/test_geodataframe.py
python/tests/geopandas/test_geoseries.py
python/tests/geopandas/test_match_geopandas_dataframe.py
python/tests/geopandas/test_match_geopandas_series.py
python/tests/geopandas/test_sjoin.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2095
- Implement scalable workaround by manually implementing logic for `ps.Series` from `ps.Series` instead of calling `to_pandas()`
- Revert the changes from https://github.com/apache/sedona/pull/2080
- It didn't work properly with the once we used proper ps.Series because the serialization format conflicted.
- After digging into the C code, it turns out the serialization method does include the SRID information, I just needed to know how to access it.
- Modify tests to avoid small edge cases that we no longer handle
- Remove shapely …

[GH-2095] Geopandas: Implement Scalable workaround and store as geometries instead of EWKB

---

python/sedona/spark/stac/collection_client.py
python/tests/stac/test_collection_client.py

Fixed a bug where the STAC reader would return 0 items when a tuple was passed as the datetime
parameter, while the same data as a list would return expected results.
Problem
The CollectionClient.load_items_df() method only checked for list type when handling datetime
parameters, causing tuples to be ignored and resulting in no temporal filtering being applied.
Before:
t = ("2025-01-01", "2025-02-01")
items = client.search(datetime=t)  # Returns 0 items
After:
t = ("2025-01-01", "2025-02-01")
items = …

[GH-2125] Fix STAC reader to accept tuples for datetime parameter

---

python/sedona/geopandas/geoseries.py
python/tests/geopandas/test_geoseries.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2134
Fix minor bug where get_crs logic won't work if first element is null
Added a test

[GH-2134] Fix bug where get_crs logic won't work if first element is null

---

spark/common/src/main/scala-spark-3/org/apache/spark/sql/sedona_sql/DataFrameShims.scala

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2140 
Make DataFrameShims available from the `org.spark.sql` package instead of only the `sedona_sql` package
unit tests
These APIs are in my mind pseudo public - accessible but undocumented. it is probably best to keep them that way for now

[GH-2140] make DataFrameShims usable outside of sedona

---

python/sedona/spark/stac/collection_client.py

The fix sanitizes exception handling by:
1. Logging only exception type names instead of full messages
2. Using `from None` to prevent exception chaining
3. Maintaining generic user-facing error messages
stac reader tests

[GH-2152] fix: prevent information disclosure through exception messages in STAC client

---

.pre-commit-config.yaml

Zip files should not be allowed in the repository as they are hard to track and have security implications
Added another hook to our pre-commit framework.
Tested by adding a ZIP file locally and then ran `pre-commit run --all-files` and this hook failed.
When there are no ZIP files the hook passes.

[CI] pre-commit add hook `check-zip-file-is-not-committed`

---

common/src/main/java/org/apache/sedona/common/utils/GeomUtils.java
snowflake/src/main/java/org/apache/sedona/snowflake/snowsql/UDFs.java
spark/common/src/main/java/org/apache/sedona/core/spatialRDD/SpatialRDD.java
spark/common/src/main/scala/org/apache/sedona/python/wrapper/translation/CircleSerializer.scala
spark/common/src/main/scala/org/apache/sedona/python/wrapper/translation/GeometrySerializer.scala
spark/spark-3.4/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetWriteSupport.scala
spark/spark-3.4/src/test/scala/org/apache/sedona/sql/geoparquetIOTests.scala
spark/spark-3.5/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetWriteSupport.scala
spark/spark-3.5/src/test/scala/org/apache/sedona/sql/geoparquetIOTests.scala
spark/spark-4.0/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/GeoParquetWriteSupport.scala
spark/spark-4.0/src/test/scala/org/apache/sedona/sql/geoparquetIOTests.scala

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2176 
* Refactored code to always use `GeomUtils.createWKBWriter`, which returns a WKB writer using the native byte order.
* Removed redundant WKB serde in some snowflake UDFs.
* Passing existing tests
* Add a new test to verify that the GeoParquet files written by sedona has native byte order
* Snowflake integration test passes: https://github.com/wherobots/sedona-snowflake-tester/pull/56
- No, this PR does not affect any public API so no need to change the documentation. However, this change might be breaking, so we'd better add this to …

[GH-2716] Always use native byte order when writing WKBs

---

python/sedona/doc/_static/color-scheme-info.md
python/sedona/doc/_static/custom.css
python/sedona/doc/_templates/layout.html
python/sedona/doc/conf.py
python/sedona/doc/index.rst
python/sedona/doc/sedona.rst
python/sedona/spark/maps/SedonaPyDeck.py
python/sedona/spark/sql/st_functions.py
python/sedona/spark/stac/client.py
python/sedona/spark/stac/collection_client.py

- No:
1. Fixed duplicate toctree references - Removed duplicate entries from sedona.rst that were already in index.rst
2. Created missing _static directory - The build was expecting this directory but it didn't exist
3. Fixed NumPy 2.0 compatibility issue - Added mock imports for pyspark.pandas modules that were failing due to deprecated
np.NaN usage
4. Fixed docstring formatting errors in:
- ST_Angle function - Fixed indentation and list formatting
- ST_WeightedDistanceBandColumn - Converted @param to :param format
- …

[DOC] Clean up the Sphinx documentation build warnings and errors

---

.pre-commit-config.yaml
scripts/pre-commit/check_makefiles_for_tabs.sh

Manual stage hook we can run on Linux and Mac Machines.  Also can run on the GitHub Actions CI and we have another PR for that here #2197 
In future we can implement the pre-commit hooks into Docker and there is issue #2202 
Makefiles utilize tabs for indentation in command lines, also known as recipes, due to a historical design decision in the original make utility. This specific use of tabs serves a crucial purpose:
Distinguishing Recipes:
The leading tab character acts as a clear signal to make that the line is a command to be …

[CI] pre-commit: add hook to check Makefiles are indented with tabs

---

.pre-commit-config.yaml
docs/api/sql/Visualization-SedonaKepler.md
docs/api/sql/Visualization-SedonaPyDeck.md
docs/api/stats/sql.md
docs/setup/databricks.md
docs/setup/fabric.md
docs/setup/glue.md
docs/tutorial/concepts/distance-spark.md
docs/tutorial/flink/pyflink-sql.md
docs/tutorial/geopandas-shapely.md
docs/tutorial/rdd.md
docs/tutorial/sql.md

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2182 
- Added `blacken-docs` as a pre-commit hook in `.pre-commit-config.yaml`
- Ensured correct formatting of all existing documentation files using `blacken-docs`
- Fixed markdown fenced block spacing issues flagged during the pre-commit run
- Ran `pre-commit run --all-files` locally, confirmed all hooks passed
- Verified formatting changes in markdown and code blocks
- CI checks expected to confirm consistency

[GH-2182] Add blacken-docs with pre-commit to run Black on Python code blocks in documentation files

---

spark/common/src/main/scala/org/apache/spark/sql/sedona_sql/optimization/SpatialFilterPushDownForGeoParquet.scala
spark/spark-3.4/src/test/scala/org/apache/sedona/sql/GeoParquetSpatialFilterPushDownSuite.scala
spark/spark-3.5/src/test/scala/org/apache/sedona/sql/GeoParquetSpatialFilterPushDownSuite.scala
spark/spark-4.0/src/test/scala/org/apache/sedona/sql/GeoParquetSpatialFilterPushDownSuite.scala

This PR adds catalyst optimizer rule to push down spatial filters with `ST_DWithin` and `ST_DistanceSpheroid`
- Adds support for Spheroidal distance in distance filter logic using ST_Buffer
- To avoid false positives when pruning with spheroidal buffer - inflates the buffer by +3%
- Removes Circle based pruning for points - expands envelope instead …

[SEDONA-741] Make ST_DWithin and ST_DistanceSpheroid filters to push down

---

python/sedona/spark/geopandas/base.py
python/sedona/spark/geopandas/geoseries.py
python/tests/geopandas/test_geoseries.py
python/tests/geopandas/test_match_geopandas_series.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2231
Implement is_ring
Added tests

[GH-2231] Implement is_ring

---

python/sedona/doc/index.rst

- No:
The pre-commit hook `rst-backticks` was failing because RST requires double backticks for inline code, not single backticks. This is a common mistake when writing RST documentation.
pre-commit run rst-backticks --files python/sedona/doc/index.rst
please run this after https://github.com/apache/sedona/pull/2220 merged

[DOC] Fix RST formatting: Use double backticks for inline code in documentation

---

python/sedona/doc/index.rst
python/sedona/doc/sedona.rst
python/sedona/doc/sedona.spark.geopandas.api.rst
python/sedona/doc/sedona.spark.geopandas.rst
python/sedona/doc/sedona.spark.geopandas.tools.rst
python/sedona/doc/sedona.spark.rst

- No:
- Updated Sphinx documentation to reflect the module reorganization from `sedona.geopandas` to
`sedona.spark.geopandas` (PR #2225)
- Created new RST documentation files for the relocated geopandas module under sedona.spark
- Fixed RST formatting issue with single backticks
- Documentation builds successfully: `make clean && make html`
- Pre-commit hooks pass: `pre-commit run rst-backticks`
- All module references resolve correctly in generated documentation

[DOC] Fix documentation structure after moving sedona.geopandas to sedona.spark.geopandas

---

.pre-commit-config.yaml

https://github.com/pre-commit/pygrep-hooks/tags
https://github.com/pre-commit/pygrep-hooks
This PR adds some checks for the RST codebase helping to keep it standardized and correct
As described above
I excluded one RST file from one hook `python/sedona/doc/index.rst` since it caused a pre-commit failure with one error.
I was unsure about this one small issue so used an exclude.
We can possibly remove the exclude in future PRs.  I am not exactly sure what the error message means since the `toctree` does …

[CI] pre-commit: add three hooks that target `RST` files

---

python/sedona/__init__.py
python/sedona/core/spatialOperator/__init__.py
python/sedona/raster_utils/SedonaUtils.py
python/sedona/sql/__init__.py
python/sedona/stac/__init__.py
python/sedona/stats/clustering/dbscan/__init__.py
python/sedona/stats/hotspot_detection/getis_ord/__init__.py
python/sedona/stats/weighting/__init__.py
python/sedona/utils/__init__.py
python/sedona/utils/structured_adapter/__init__.py
python/tests/test_path_compatibility.py
python/tests/test_path_compatibility_all.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2252 
* Fixed all missing warnings
* Removed wrong warnings in `from sedona.spark import SedonaContext`
* Unified all warning messages
Passed locally and manually tests

[GH-2252] Deprecation warnings pop up in the wrong place

---

README.md
mkdocs.yml

- No:
1. Added "Sedona Python: api/pydocs" to mkdocs.yml in three locations:
- Under "Install with Apache Spark" section (after "Install Sedona R")
- Under "Programming Guides > Sedona with Apache Spark" section (after "Sedona R")
- Under "API Docs > Sedona with Apache Spark" section (after "Sedona R")
2. Added a link in README.md to point to the Python API documentation alongside the existing R documentation link.
Python doc should be able to see on all three pages mentioned above.

[DOC] Add the Python documentation links to the main navigation

---

python/sedona/spark/geopandas/geodataframe.py
python/sedona/spark/geopandas/geoseries.py
python/tests/geopandas/test_geoseries.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2266
- Removed an unnecessary check (eager `.crs` query) in `to_crs`. This was causing a non-neglible slow-down, when calling `to_crs`. Sedona's ST_Transform will naturally catch cases when crs is not set instead. This also makes `to_crs` lazy like `set_crs` is.
- Also adds a missing `keep_name=True` to `to_crs` query
Existing tests still pass

[GH-2266] Geopandas: Remove unnecessary old_crs check and in `to_crs`

---

python/sedona/spark/geopandas/geoseries.py
python/tests/geopandas/test_geoseries.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2264
Geopandas supports inputting a geodataframe as "other" for row wise opeartions like this:
```python
geoseries.difference(df)
```
This PR adds support for this. Previously, we could only accomplish this behavior by accessin the active geometry column directly.
```python
geoseries.difference(df.geometry)
```
Added test
- No, this PR does not affect any public API so no need to change the documentation. Geopandas doesn't explicitly mention in their documentation, so I don't see the need for us to either.

[GH-2264] Geopandas: Support other of type GeoDataframe in row_wise_operations

---

python/sedona/spark/geopandas/geodataframe.py
python/tests/geopandas/test_geodataframe.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2269
- Previously, `df.copy()` would just return `self`, causing operations that rely on `.copy()` to actually modify the geodataframe object in place unintentionally. This PR fixes that. The implementation exactly follows the pyspark pandas implementation with the exception that I wrap it with GeoDataframe and manually set the active geometry column.
- Also I removed the logic for `deep=True` because that code actually errors. Also pyspark pandas does not implement that parameter either. We already had documentation to say that `deep` …

[GH-2269] Geopandas: Fix geodataframe.copy() to properly create a copy

---

python/sedona/spark/geopandas/geodataframe.py
python/sedona/spark/geopandas/geoseries.py

Incorrect Class References
- geoseries.py - Uses geopandas.GeoSeries.from_wkb() instead of Sedona's
GeoSeries.from_wkb()
- geoseries.py - Uses geopandas.GeoSeries.from_xy() instead of Sedona's GeoSeries.from_xy()
- geodataframe.py - Uses geopandas.GeoDataFrame() instead of Sedona's GeoDataFrame()
- geodataframe.py - Uses geopandas.read_file() instead of appropriate Sedona method
Missing Import Statements
- geoseries.py - Example uses pd.Series without import pandas as pd
- geodataframe.py - Missing from …

[GH-2273] Fix GeoPandas errors and issues in the examples

---

python/sedona/spark/geopandas/geodataframe.py
python/sedona/spark/geopandas/tools/sjoin.py
python/tests/geopandas/test_sjoin.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2279
Added support for covers and covered_by
Added tests

[GH-2279] Geopandas: Support sjoin with `covers` and `covered_by` predicates

---

common/src/main/java/org/apache/sedona/common/Functions.java
common/src/main/java/org/apache/sedona/common/jts2geojson/GeoJSONReader.java
common/src/main/java/org/apache/sedona/common/jts2geojson/GeoJSONWriter.java
common/src/main/java/org/apache/sedona/common/utils/FormatUtils.java
common/src/test/java/org/apache/sedona/common/jts2geojson/GeoJSONReaderTest.java
common/src/test/java/org/apache/sedona/common/jts2geojson/GeoJSONWriterTest.java
flink/src/test/java/org/apache/sedona/flink/ConstructorTest.java
flink/src/test/java/org/apache/sedona/flink/TestBase.java
spark/common/src/main/java/org/apache/sedona/core/spatialRDD/SpatialRDD.java
spark/common/src/test/java/org/apache/sedona/core/utils/testGeoJSON.java

- Yes, and the PR name follows the format `[GH-2294] my subject`. Closes #2294
* Copied some code from https://github.com/bjornharrtell/jts2geojson (MIT license)
* Added more comprehensive java tests
* Added XYZM support
Note that the GeoJSON standard does not define the behavior of the M dimension, and consequently does not cover XYZM or XYM. In this PR, we explicitly support only the XYZM case and disallow XYM by throwing exceptions. Allowing XYM would cause ambiguity with XYZ, which would be incorrect.
Add more test cases with XYZM and XYM
- Yes, I am adding a new API. I am using the [current SNAPSHOT …

[GH-2294] Introduce XYZM support in GeoJSON reader and writer

---

python/sedona/spark/geopandas/__init__.py
python/tests/geopandas/test_geodataframe.py
python/tests/geopandas/test_geopandas_base.py
python/tests/geopandas/test_geoseries.py
python/tests/geopandas/test_match_geopandas_dataframe.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2281
Previously, the user would need to set `ps.set_option("compute.ops_on_diff_frames", True)` to avoid erroring for many dataframe operations. Users shouldn't need to encounter errors for this being set to False by default. Setting it to False is primarily useful for sedona geopandas development to ensure we're not using unnecessary inefficiencies. Spark 4.0.0 also changed the default to True (which I like), so this PR is primarily to change the behavior for older versions. 
- Set `ps.set_option("compute.ops_on_diff_frames", True)` in …

[GH-2281] Geopandas: set ps option 'compute.ops_on_diff_frames' to True by default

---

python/sedona/spark/geopandas/io.py
python/tests/geopandas/test_io.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2277
Fixed a small bug where "Parquet" was specified instead of "GeoParquet" for writing.
Added tests to ensure format inference works along with other io tests that we should have and already pass

[GH-2277] Geopandas: Fix to_file inferring parquet format instead of geoparquet

---

spark/common/src/main/java/org/apache/sedona/sql/datasources/osmpbf/extractors/NodeExtractor.java
spark/common/src/test/scala/org/apache/sedona/sql/OsmReaderTest.scala

- Yes, and the PR name follows the format `[GH-2308] my subject`. Closes #2308
Use `double` to store the lon lat values
Added one more unit test to test the precision lost issue

[GH-2308] Fix the precision lost issue in OSM PBF reader

---

python/sedona/spark/geopandas/geoseries.py
python/sedona/spark/geopandas/sindex.py
python/tests/geopandas/test_sindex.py

- Yes, and the PR name follows the format `[GH-XXX] my subject`. Closes #2331
Unfortunately, Sedona doesn't have the exact same behavior for geopandas spatial index queries. Geopandas return indices, while Sedona returns actual geometries. It wouldn't be easy to modify Sedona to return the indices, nor does it make much sense to imo, since indexes would be very slow to maintain in a distributed environment.
- Additionally, this PR fixes an issue where we return [GeoData](https://github.com/apache/sedona/blob/e6e7c88bc8110bd10de36880ed8597313a3d8846/python/sedona/spark/utils/spatial_rdd_parser.py#L36) types …

[GH-2331] Geopandas: Document differences of sindex compared to gpd + sindex fixes

---

python/tests/stac/mock_fixtures.py
python/tests/stac/test_client.py
python/tests/stac/test_collection_client.py
python/tests/stac/test_mock_fixtures.py

This PR refactors the STAC tests to use mock clients instead of real external STAC servers, making the tests more reliable and faster.
- Added `test_mock_fixtures.py` with mock implementations of STAC Client and CollectionClient
- Refactored `test_client.py` to use `@patch` decorators with mock clients
- Refactored `test_collection_client.py` to use `@patch` decorators with mock clients
- All 34 STAC tests now use mocked responses instead of external servers
- No, this PR does not affect any public API so no need to change …

[GH-2348][Python] Make STAC tests resilient to external server failures

---

spark/common/src/test/resources/stac/collections/copernicus-dem.json
spark/common/src/test/resources/stac/collections/earthview-catalog.json
spark/common/src/test/resources/stac/collections/naip.json
spark/common/src/test/resources/stac/collections/sentinel-2-pre-c1-l2a.json
spark/common/src/test/resources/stac/collections/vegetation-collection.json
spark/common/src/test/resources/stac/collections/wildfire-collection.json
spark/common/src/test/resources/stac/items/sentinel-2-items.json
spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacBatchTest.scala
spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacDataSourceTest.scala
spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacPartitionReaderTest.scala
spark/common/src/test/scala/org/apache/spark/sql/sedona_sql/io/stac/StacTestUtils.scala

This PR makes STAC tests resilient to external server failures by implementing mock-based testing for Python and local test resources for Scala, ensuring tests run reliably without network dependencies.
- Created mock STAC collection JSON files in `/spark/common/src/test/resources/stac/`:
- 6 collection files (sentinel-2, vegetation, wildfire, copernicus-dem, naip, earthview)
- 1 items file with 10 mock STAC items
- Updated `StacDataSourceTest.scala` to use local mock files instead of remote URLs
- Updated …

[GH-2348] Fix STAC tests resilience to external server failures in Scala

---

.github/workflows/r.yml
R/tests/testthat/helper-initialize.R

Add retry logic with exponential backoff for Spark downloads to make the workflow resilient to temporary network issues.
test on ci run

[GH-2351] [CI] Fix R CI flakiness with Spark download from PySpark

---

python/sedona/spark/geopandas/geodataframe.py
python/sedona/spark/geopandas/geoseries.py
python/sedona/spark/geopandas/io.py
python/sedona/spark/geopandas/sindex.py
python/sedona/spark/geopandas/tools/sjoin.py

- No:
This PR standardizes comment formatting and consistency across the Sedona GeoPandas module to improve code readability and maintainability.
- **Fixed comment punctuation**: Added missing periods to end sentences consistently
- **Standardized technical terms**:
- **Improved docstring formatting**: Enhanced parameter documentation to follow NumPy style
- **Grammar and clarity fixes**: Corrected typos and improved sentence structure
- **Consistent comment style**: Applied uniform formatting across all files
All existing …

[DOCS] Fix comment and doc consistency issues in GeoPandas API

---

docs-overrides/main.html

- No:
Updates the homepage with links and some tweaks.
Tested locally with `mkdocs serve`.

[DOCS] update homepage links
